### ISSUE TITLE
Owncloud for ever or Nextcloud for next ?

### ISSUE THREAD

**Issue by jajaX** [owncloud/news#1004]
Hi (sorry again for my enlish)

all people here, I think, know the fork of Owncloud, Nextcloud.

I would like know if you think stay with owncloud or, for futur, support nextcloud ?

thanks ;)

**Comment by RealRancor** [comment]
Quoting from : http://owncloud.10557.n7.nabble.com/ownCloud-Project-Sorting-td17384.html

> Something very concrete that we have to solve: Bernhardt who developed
and maintained the news app for ownCloud so far, has decided to move on.
As a result,
   https://github.com/owncloud/news
needs a new maintainer to be kept at least in a working state with
upcoming ownCloud releases.
> 
> If you ever considered diving into ownCloud development, here is your
chance: Bernhard is still around and can (and I am sure will) help, and
the news app is a very popular one, so it is a smooth but very
interesting take off :-)

**Comment by jajaX** [comment]
Hi,

ok, thanks for your answner ;)

for this moment, I wait again...

**Comment by DeepDiver1975** [comment]
Let's see where the we go ....
