### ISSUE TITLE
Can't load news app on Owncloud 9.1

### ISSUE THREAD

**Issue by johnseekins** [owncloud/news#1011]
# IMPORTANT

Read and tick the following checkbox after you have created the issue or place an x inside the brackets ;)

* [x] I have read the [CONTRIBUTING.md](https://github.com/owncloud/news/blob/master/CONTRIBUTING.md) and followed the provided tips

## Explain the Problem
What problem did you encounter?

After fixing #1008, I received the following error when running `occ upgrade`:
``` bash
Updating <news> ...
PHP Fatal error:  require_once(): Failed opening required '/var/www/html/owncloud/apps/news/appinfo/../vendor/autoload.php' (include_path='/var/www/html/owncloud/3rdparty/pear/console_getopt:/var/www/html/owncloud/3rdparty/pear/pear_exception:/var/www/html/owncloud/3rdparty/pear/pear-core-minimal/src:/var/www/html/owncloud/3rdparty/pear/archive_tar:/var/www/html/owncloud/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/html/owncloud/lib/private:/var/www/html/owncloud/config:/var/www/html/owncloud/3rdparty:/var/www/html/owncloud/apps:.:/usr/share/pear:/usr/share/php:/var/www/html/owncloud') in /var/www/html/owncloud/apps/news/appinfo/app.php on line 16
bash-4.2$ php -v
PHP 7.0.8 (cli) (built: Jun 23 2016 16:24:08) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

## Steps to Reproduce
Explain what you did to encounter the issue
1.
2.
3.

## System Information
* News app version: 8.2.2
* ownCloud version: 9.1
* PHP version: 7.0.8
* Database and version: n/a
* Browser and version: n/a
* Distribution and version: CentOS 7

## Contents of owncloud/data/owncloud.log

```json

{"reqId":"GNfDwMOJQkYPw2Qhx5UY","remoteAddr":"","app":"PHP","message":"require_once(\/var\/www\/html\/owncloud\/apps\/news\/appinfo\/..\/vendor\/autoload.php): failed to open stream: No such file or directory at \/var\/www\/html\/owncloud\/apps\/news\/appinfo\/app.php#16","level":3,"time":"2016-07-25T14:32:01+00:00","method":"--","url":"--","user":"--"}
{"reqId":"GNfDwMOJQkYPw2Qhx5UY","remoteAddr":"","app":"PHP","message":"require_once(): Failed opening required '\/var\/www\/html\/owncloud\/apps\/news\/appinfo\/..\/vendor\/autoload.php' (include_path='\/var\/www\/html\/owncloud\/3rdparty\/pear\/console_getopt:\/var\/www\/html\/owncloud\/3rdparty\/pear\/pear_exception:\/var\/www\/html\/owncloud\/3rdparty\/pear\/pear-core-minimal\/src:\/var\/www\/html\/owncloud\/3rdparty\/pear\/archive_tar:\/var\/www\/html\/owncloud\/3rdparty\/phpseclib\/phpseclib\/phpseclib:\/var\/www\/html\/owncloud\/lib\/private:\/var\/www\/html\/owncloud\/config:\/var\/www\/html\/owncloud\/3rdparty:\/var\/www\/html\/owncloud\/apps:.:\/usr\/share\/pear:\/usr\/share\/php:\/var\/www\/html\/owncloud') at \/var\/www\/html\/owncloud\/apps\/news\/appinfo\/app.php#16","level":3,"time":"2016-07-25T14:32:01+00:00","method":"--","url":"--","user":"--"}
```

**Comment by Dragnucs** [comment]
I too have this issue. The application manager says that 'news' has been enabled. Refreshing the page, it is still not enabled.

In the logs:
```
Exception: {"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"news.page.index\" as such route does not exist.","Code":0,"Trace":"#0 \/usr\/share\/webapps\/owncloud\/lib\/private\/Route\/Router.php(320): Symfony\\Component\\Routing\\Generator\\UrlGenerator->generate('news.page.index', Array, 1)\n#1 \/usr\/share\/webapps\/owncloud\/lib\/private\/Route\/CachingRouter.php(59): OC\\Route\\Router->generate('news.page.index', Array, false)\n#2 \/usr\/share\/webapps\/owncloud\/lib\/private\/URLGenerator.php(67): OC\\Route\\CachingRouter->generate('news.page.index', Array)\n#3 \/usr\/share\/webapps\/owncloud\/apps\/news\/config\/appconfig.php(108): OC\\URLGenerator->linkToRoute('news.page.index')\n#4 \/usr\/share\/webapps\/owncloud\/lib\/private\/NavigationManager.php(63): OCA\\News\\Config\\AppConfig->OCA\\News\\Config\\{closure}()\n#5 \/usr\/share\/webapps\/owncloud\/lib\/private\/legacy\/app.php(690): OC\\NavigationManager->getAll()\n#6 \/usr\/share\/webapps\/owncloud\/lib\/private\/TemplateLayout.php(83): OC_App::getNavigation()\n#7 \/usr\/share\/webapps\/owncloud\/lib\/private\/legacy\/template.php(229): OC\\TemplateLayout->__construct('user', 'files')\n#8 \/usr\/share\/webapps\/owncloud\/lib\/public\/AppFramework\/Http\/TemplateResponse.php(156): OC_Template->fetchPage()\n#9 \/usr\/share\/webapps\/owncloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(112): OCP\\AppFramework\\Http\\TemplateResponse->render()\n#10 \/usr\/share\/webapps\/owncloud\/lib\/private\/AppFramework\/App.php(110): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files\\Controller\\ViewController), 'index')\n#11 \/usr\/share\/webapps\/owncloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(46): OC\\AppFramework\\App::main('ViewController', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#12 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#13 \/usr\/share\/webapps\/owncloud\/lib\/private\/Route\/Router.php(280): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#14 \/usr\/share\/webapps\/owncloud\/lib\/base.php(891): OC\\Route\\Router->match('\/apps\/files')\n#15 \/usr\/share\/webapps\/owncloud\/index.php(39): OC::handleRequest()\n#16 {main}","File":"\/usr\/share\/webapps\/owncloud\/3rdparty\/symfony\/routing\/Generator\/UrlGenerator.php","Line":130} 
```

**Comment by ungesundes-halbwissen** [comment]
+1 for NC 10 Beta

**Comment by sprnza** [comment]
The same issue here

**Comment by PsichoD** [comment]
+1

**Comment by sprnza** [comment]
Guys? Do you have any comment on this? Should I downgrade or something?

**Comment by goopen** [comment]
I'm having this issue aswell - is this project dropped in favor for nextcloud news? I see activity on the NC news app all time but last commit here was 2 months ago now. Can we get a word on this?

**Comment by BernhardPosselt** [comment]
I maintain the News app and moved to Nextcloud. Unless someone from ownCloud starts to work on this, consider the repo dead ;)

**Comment by Dragnucs** [comment]
Is there a way we can install the nextcloud version on owncloud?

On August 12, 2016 8:00:14 PM GMT+01:00, Bernhard Posselt <notifications@github.com> wrote:
>I maintain the News app and moved to Nextcloud. Unless someone from
>ownCloud starts to work on this, consider the repo dead ;)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/news/issues/1011#issuecomment-239532172

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by BernhardPosselt** [comment]
@Dragnucs the Nextcloud version should work just fine (for now) I think

**Comment by sprnza** [comment]
In a nutshell, what's wrong with ownCloud?

**Comment by Dragnucs** [comment]
Great. Thanks.

On August 12, 2016 8:18:44 PM GMT+01:00, Bernhard Posselt <notifications@github.com> wrote:
>@Dragnucs the Nextcloud version should work just fine (for now) I think
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/news/issues/1011#issuecomment-239536605

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by BernhardPosselt** [comment]
There are so many changes in Nextcloud compared to ownCloud however that I don't think this will hold for much longer. If you take a look at the commits in the ownCloud repo its basically only 3 active devs. 

Nextcloud can reuse ownCloud code, however ownCloud can't because of its proprietary license. So my personal take on that is that unless a miracle happens, ownCloud is dead. You can ofc continue to use it but the bugfix rate is probably way slower.

**Comment by BernhardPosselt** [comment]
Dead as in OpenOffice dead after the split.

**Comment by sprnza** [comment]
Thanks, I'll consider to move to NC10 then :)

**Comment by BernhardPosselt** [comment]
BTW: I put up a banner like here https://github.com/owncloud/news-updater but got contacted by ownCloud people that it's not ok since it's their repo. So I restored the old content and removed myself from the contributors file.

**Comment by johnseekins** [comment]
Solid answer.
