### ISSUE TITLE
Podcast stops playing when (re)loading a feed

### ISSUE THREAD

**Issue by icewind1991** [owncloud/news#156]
While listening to an audio podcast in a news reader, when (re)loading a feed the podcasts stops playing because the <audio> element gets removed.

A option might be to move the <audio> element outside the feed view when the audio is playing.

For long term, it might be nice to integrate it in the media app in a way. (if the media app ever gets fixed properly)

**Comment by pmk1c** [comment]
I don't think it should be integrated with the music app. The people behind elementaryOS made some good points on that: http://elementaryos.org/journal/why-a-music-app-shouldnt-be-a-podcast-app
