### ISSUE TITLE
Make feeds available to Thunderbird

### ISSUE THREAD

**Issue by IBBoard** [owncloud/news#194]
Unless I'm missing something, the News app can import and export OPML to allow you to have the same feeds in multiple feed readers (either importing existing ones into News when you first use it, or exporting them to apps when you can't reliably use News but can use something like a desktop app), but it doesn't expose those feeds in a way that you can subscribe to directly.

What I'd like to be able to do, for consistency between machines, is:
1) Add feeds to ownCloud News (e.g. add http://feeds.bbci.co.uk/sport/0/formula1/rss.xml)
2) Subscribe to that newly added feed in Thunderbird (e.g. http://owncloud.example.com/index.php/apps/news/feed/BBC_Sport_-_Formula_1 or some other generated URL)
3) ownCloud polls in the background and updates its copies of the feed, which are accessible via the web interface
4) Thunderbird fetches the feed from the ownCloud copy
5) (optional, but fantastic if possible) read and starred state of feeds in Thunderbird are synced with read/starred in ownCloud and all other clients that understand it

**Comment by Croydon** [comment]
Basically I would like to see the same thing realised as @IBBoard. Forgive my naive question since I never really used the news app, but for what is syncing with this app useful, when there is no bundling of the feeds and no syncing of the already-read-state?

**Comment by cosenal** [comment]
@Croydon the News app does sync everything with all apps that support our API (https://github.com/owncloud/news/wiki/API-1.2)
RSS is not meant for synchronizing read/starred states.
@IBBoard easy! convince Thunderbird folks to synchronize with our API ;-)

**Comment by IBBoard** [comment]
So are you suggesting that rather than have OwnCloud News follow the "Google Reader" API that a number of devs integrated into their apps as a defacto standard (which would mean that all of those apps instantly support feeds via OwnCloud News), we should instead be asking a behemoth the size of Mozilla to add support for a non-standardised API for a single app that a small number of people will use, when they already limit the number of core functions anyway?

Yeah, I can see that one working out well!

**Comment by cosenal** [comment]
I am sorry you're disappointed, but that is indeed what we have decided to do. For a discussion on why we didn't adopt Google Reader API, see #105 and other similar issues on the repo.

**Comment by IBBoard** [comment]
Meh, I've given up on the idea of having a Google Reader replacement that I can integrate with proper desktop apps and just make do with the web interface in a pinned tab.

If you'd have said "you need someone to write a plugin for Thunderbird to support our API" then that wouldn't have got a comment ;)

**Comment by cosenal** [comment]
@IBBoard I am actually not familiar with Thunderbird. Do they actually have a plugin system for the feed reader?

**Comment by IBBoard** [comment]
The feeds are just part of the app and the app does plugins. I looked in to it after posting this and being told "no". There was a skeleton plugin for adding a new feed type. I can code and it'd have been interesting to do, but I had enough on my plate and I didn't know Thunderbird plugin architecture enough to make it seem like something I'd make good progress on quickly.

And of course I now can't find that plugin because all of my Google searches go "With those keywords you *obviously* wanted this article on how to add a normal RSS feed to normal Thunderbird the really normal way. No? How about this one about how to add a normal RSS feed to normal Thunderbird the really normal way."

**Comment by Raydiation** [comment]
You can ofc always write your own app that uses the news apps tables and implements a Google reader api however I think you may run into issues because our implementation is quite different. You'd have to dig into the api yourself

**Comment by Raydiation** [comment]
BTW if you need help with creating an owncloud app that does this let me know, I'll help you out and walk you through the stuff. I'm a bit busy over the weekend (getting married ;D) but of you want to we can work on this next week.

For starting out you can take a look at https://github.com/Raydiation/feedcentral
