### ISSUE TITLE
Feed update should be possible without providing the admin password in plain text

### ISSUE THREAD

**Issue by schiessle** [owncloud/news#312]
I just looked up how to update my feeds with a cronjob: https://github.com/owncloud/news/wiki/Cron-1.2

Looks quite frightening to add my admin password in plain text to my crontab. Basically the cronjob just needs to take the feed URLs from the database, fetch the feeds and write them back to the db, right? Shouldn't this be possible with a dedicated update script which works without a password?

**Comment by BernhardPosselt** [comment]
BTW, added a new console API based on occ and implemented it in the updater. No user or password needed anymore if you go for that ;)
