### ISSUE TITLE
Sort order of feeds

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/news#368]
Currently there seems to be no sort order. There should be though, and preferably automatic (no crazy drag&drop sorting please …). Options would be:
1. Alphabetically. That’s not really contextual – but the sorting always stays the same which is good.
2. By unread count. This might give more importance to active feeds which isn’t necessarily good. And I don’t think focusing on the unread count too much is great either. Also, feeds will probably move around.
3. By latest article. This will make feeds move around, but in a way which might make more sense – because the »All articles« view is also sorted by latest article.

What do you think @Raydiation @cosenal? I’m unsure between 3 and 1.

Of course the sorting should also be for folders and the feeds inside folders.

**Comment by rakekniven** [comment]
Hello Bernhard, 
is your latest statement still valid.
My vote would be a custom order of feeds. Fixed. My top feeds manually arranged on top. 
No magic.
Any opinions?

**Comment by BernhardPosselt** [comment]
@rakekniven Usecase here is probably quick access to your most used feeds right?

**Comment by BernhardPosselt** [comment]
What about an additional feed button to "pin" the feeds to the top, something like the forum allows you to do? Those feeds would be on top and also ordered alphabetically (order by pinned, feed_name).

The thing is custom ordering is not only more challenging to implement but also needs additional stuff like allowing to reset the order etc. for something you might not even need/want to deal with ;)

**Comment by rakekniven** [comment]
Yes, most used feeds and most important feeds.
Pinning would to the same for me, so that idea would work.
