### ISSUE TITLE
Proposal for article enhancers

### ISSUE THREAD

**Issue by phedlund** [owncloud/news#374]
Call me old-fashioned but I would like to propose a system of using independent ini files for article enhancers and place these files in a dedicated folder. Something like this (for myenhancer.ini):

``` INI
[ArticleEnhancer]
name = MyEnhancer
url = example.com/feed
expression = extraction expression
```

Use PHP DirectoryIterator http://php.net/manual/en/class.directoryiterator.php to find the files. Then use http://php.net/manual/en/function.parse-ini-file.php to read individual files and generate relevant code.

Advantages: 
- Users can put their own enhancers in a specified directory.
- Enhancers can be added, modified, deleted, and distributed independently of core components.
- Enhancers can be shared or kept private.

**Comment by pank** [comment]
Sorry for bumping this.  I can start another issue if that's better.

I think this it's an excellent idea to let users have their own feed enhancers, *at least for testing purposes*.  I have a number of feeds where I would like to add enhancers, but at the moment it seeems hard to get into writing enhancers, as I need to setup my own instance of OC, install News, and import my feed before I can even start hacking.

How about having a monotoholitic file that is overwritten on updates to encourage patches, but still allow some testing of new enhancers?  It could even be for a single session, if you prefer.

For me, it would be particularly useful if testing was doable from a user account as I'm the admin of my main OC instance.

**Comment by Raydiation** [comment]
Sorry, I don't really get what you mean.

**Comment by cosenal** [comment]
@pank Let me interpret what you are asking for and try to answer it (correct me if I am wrong). From what I understand, you want to be able to write an article-enhancer without setting up a dev environment for oC.

You can do that just by modifying one of two files in your oC installation. As it's specified in the [wiki](https://github.com/owncloud/news/wiki/Article-Enhancers) The path of those files are:
`<your_Oc_path>/news/articleenhancer/regexenhancers.json`
and
`<your_Oc_path>/news/articleenhancer/xpathenhancers.json`

As you are the admin of the oC installation, I assume you have access to those files. (Even an installation through distribution packages will have those files). I still recommend you operate in a dev environment, as it will be easier to debug issues.

**Comment by pank** [comment]
that was a typo: I'm *not* admin for my OC.  Sorry.

I want to be able to relatively easily test article enhancers, from a user account, so that I can submit them upstream.

**Comment by cosenal** [comment]
Scratch what I said then.

> "setup my own instance of OC, install News, and import my feed..."

c'mon, that's not hard! 
And as I said, if you do that, it will be easier to debug things. And anyway, I don't see how you want to submit your enhancers upstream, if you don't have a fork of this repository first.

**Comment by Raydiation** [comment]
It's as easy as installing php, ocdev and running

    ocdec setup base
    cd core
    php -S localhost:8080

**Comment by Raydiation** [comment]
See https://github.com/owncloud/ocdev/blob/master/README.rst for how to install ocdev

**Comment by pank** [comment]
Alessandro Cosentino <notifications@github.com> writes:

>> "setup my own instance of OC, install News, and import my feed..."
>
> c'mon, that's not hard!

Mew.  I don't know anything about web-programming...

> And as I said, if you do that, it will be easier to debug things. And
> anyway, I don't see how you want to submit your enhancers upstream, if
> you don't have a fork of this repository first.

There's a big difference between forking a repo and do `format-patch` or
`request-pull` (which probably doens't work with github) and installing a
server and whatnot (but I think rhcloud would solve this step).

Thanks,
Rasmus

-- 
Dobbelt-A

**Comment by pank** [comment]
Bernhard Posselt <notifications@github.com> writes:

> See https://github.com/owncloud/ocdev/blob/master/README.rst for how to install ocdev

I guess I'd stick to rhcloud.com.  They have got this one:

   https://hub.openshift.com/quickstarts/4-owncloud

But this is a pretty steep requirement for something like contributing
article enhancers...

Anyway, I will look into this in the near future.

Thanks,
Rasmus

-- 
Hooray!

**Comment by bastei** [comment]
@pank RegExp and XPath are not specific things of the News app. Thus you can take the HTML source of a website and run the enhancers "outside" of the app. The other way round your can write regular and XPath expressions using other tools and they should work in the News app as enhancers. There are several addons for Firefox that can help you testing and creating such expressions, [HTML Regex Data Extractor](https://addons.mozilla.org/en-US/firefox/addon/html-regex-data-extractor) and [XPath Checker](https://addons.mozilla.org/en-US/firefox/addon/xpath-checker) for example. However, you must know how RegEx and XPath work.

@Raydiation @cosenal Do you test enhancers before merging them? :wink:
Maybe the [Article Enhancers Wish List](https://github.com/owncloud/news/wiki/Article-Enhancers-Wish-List) would be the right place for such non-tested contributions.?

**Comment by pank** [comment]
bastei <notifications@github.com> writes:

> @pank RegExp and XPath are not specific things of the News app. Thus
> you can take the HTML source of a website and run the enhancers
> "outside" of the app. The other way round your can write regular and
> XPath expressions using other tools and they should work in the News
> app as enhancers.

Thanks.  I will look into your suggestions.  That seems easier.  I know
regexp very well from projects that I participate in.  Xpath can't be too
hard...  I wrote a few when I used TTRSS without really understanding what
it was.

—Rasmus

-- 
⠠⠵

**Comment by Raydiation** [comment]
@bastei depends ;D but yes I should definitely test them everytime before merging them
