### ISSUE TITLE
Error when updating news in Owncloud 6.0.0a (type "bigserial" does not exist)

### ISSUE THREAD

**Issue by jcbrand** [owncloud/news#430]
Hi there

Yesterday I installed Owncloud 6.0.0a via the Debian repos.

Then, through the web UI I updated the News add-on. Now my owncloud instance is bricked.

Checking the owncloud log, the error comes down to this:

``` sql
owncloud=# ALTER TABLE "oc_news_folders" ALTER id TYPE BIGSERIAL;
ERROR:  type "bigserial" does not exist
```

Any idea how I can fix this?

Thanks

**Comment by MichaelSp** [comment]
and still not fixed upstream, since 5 years now :(
