### ISSUE TITLE
Prevent multiple loading of items

### ISSUE THREAD

**Issue by bastei** [owncloud/news#458]
The current behavior of syncing via API is the following:

* 1. API sync: load new item A, remember "lastModified"-timestamp
* cahnge read or starred status of item A (on the same device or elsewhere)
* 2. API sync: the whole item A loads again, as it was modified after the remembered timestamp

The result is that <b>every item is loaded everytime its read/starred status changes</b>. As every item is set to "read" at anytime, minimum loading is twice. That's <b>not good for mobile internet connections</b>.
<hr/>
Here is my suggestion:
Enable the client to say: "Hey server, give me your updates since yesterday, 3 pm. Oh and please don't send me the items older than the one with id 42 again, I already have them. Only give me the status-information of them."

The /items/updated route of the API gets <b>another parameter "lastKnownId"</b>, which is the last item-id the client knows of.
For every item that has a lower-equal id the server only sends the "unread", "starred" and "lastModified" parameters, since all the other parameter will never change in the life of an item.
<hr/>
Here is the example:

Items:
id: 1, lastModified: 10000
id: 2, lastModified: 30000
id: 3, lastModified: 15000
id: 4, lastModified: 20000

API Request:
items/updated?format=json&type=3&id=0&<b>lastModified=12</b>&<b>lastKnownId=3</b>

API Response:
```json
{
    "items": [

    // first all the items with id <= lastKnownId and item.lastModified > request.lastModified
    // these items are already on the device, so only send fields that cpuld have changed
    {
        "id": 2,
        "unread": false,
        "starred": true,
        "lastModified": 30000
    }, {
        "id": 3,
        "unread": true,
        "starred": false,
        "lastModified": 15000
    },

    // let's send the new items with id > lastKnownId and item.lastModified > request.lastModified
    {
        "id": 4,
        "guid": "http://www.unique.url",
        "guidHash": "88b150",
        "url": "http://www.item.url",
        "title": "Item title",
        "author": "Item author",
        "pubDate": 19,
        "body": "This is the items text. It is so huge, you don't want to load it multiple times! :)",
        "enclosureMime": null,
        "enclosureLink": null,
        "feedId": 1,
        "unread": true,
        "starred": false,
        "lastModified": 20000
    }]
}
```

**Comment by BernhardPosselt** [comment]
Moving this to the API 2.0 ticket: https://github.com/owncloud/news/issues/862

For identifying similar posts we now compute a hash over all relevant fields (content, url, title, enclosures). The sync client will also receive the fingerprints and send them to the server when syncing. If the fingerprint of the item that should be marked read/starred matches the one in the database, we can detect that we only need to send the actual status change. 

This is a more robust, faster and easier way to fix this issue :)
