### ISSUE TITLE
Desktop-Sync-Clients?

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/news#509]
Are there any for linux?
I could only find the Android-News-App.

**Comment by jangernert** [comment]
https://www.youtube.com/watch?v=oxBKhl9nc5Y
Will release a beta soon :)
http://jangernert.github.io/feedreader/

**Comment by jajaX** [comment]
Hi (sorry fo mya bad english)

very nice jangernert, but I can test/use it because I'm using kubuntu 14.04 :(

**Comment by jancborchardt** [comment]
@jangernert cool stuff! :) I’d be up for betatesting. It would especially be cool to have offline support (which kind of is the point of a desktop app for me), so I threw some more money at you ;) https://www.bountysource.com/issues/26359407-offline-mode
The mobile apps of @David-Development and @phedlund already do a great job at that.

**Comment by jangernert** [comment]
@jancborchardt thx, as you saw offline mode is already on my to-do-list. Regarding mobile apps: I guess you are talking about android apps? I'm on Jolla :D

**Comment by cosenal** [comment]
@jangernert Awesome, I will betatest right away. But please please, off-line mode! (Bountysource messed up my bitcoin transaction, one more bounty coming your way...)

Don't forget to add your app here: https://github.com/owncloud/core/wiki/Apps

**Comment by jancborchardt** [comment]
@jangernert yeah, [Android](https://play.google.com/store/apps/details?id=de.luhmer.owncloudnewsreader) ([source](https://github.com/owncloud/news-android-app)) and [iOS](https://itunes.apple.com/us/app/cloudnews-owncloud-news-reader/id683859706?mt=8) ([source](https://github.com/owncloud/news-ios-app)) :)
