### ISSUE TITLE
Error "1038 Out of sort memory, consider increasing server sort buffer size"

### ISSUE THREAD

**Issue by wwark** [owncloud/news#540]
Dear Support,

I have recently installed Owncloud in my NAS DS411 http://nas.findthebest.com/l/748346/Synology-DS111

I had an issue with this news app. I have got this fatal error when i tried to add a site to feed.
<br>Doctrine\DBAL\DBALException: An exception occurred while executing 'SELECT `feeds`._, COUNT(`items`.`id`) AS `unread_count` FROM `news_feeds` `feeds` LEFT JOIN `news_items` `items` ON `feeds`.`id` = `items`.`feed_id` AND (`items`.`status` & 2) = 2 WHERE `feeds`.`url_hash` = ? AND `feeds`.`user_id` = ? GROUP BY `feeds`.`id`, `feeds`.`user_id`, `feeds`.`url_hash`,`feeds`.`url`, `feeds`.`title`, `feeds`.`link`,`feeds`.`favicon_link`, `feeds`.`added`, `feeds`.`articles_per_update`,`feeds`.`folder_id`, `feeds`.`prevent_update`, `feeds`.`deleted_at`' with params ["_******_", "**_**"]: SQLSTATE[HY001]: Memory allocation error: 1038 Out of sort memory, consider increasing server sort buffer size</br>

My NAS has just 256 mo so maybe it is the problem.

Could yo please give me some hints to this error ?

Regards,
Wark.

**Comment by patlajan** [comment]
I experienced the same problem on a several thousand rows and even 128 MB buffer didn't solve it.
------------------------------------------------------
You have
GROUP BY feeds.id, feeds.user_id, feeds.url_hash,feeds.url, feeds.title, feeds.link,feeds.favicon_link, feeds.added, feeds.articles_per_update,feeds.folder_id, feeds.prevent_update, feeds.deleted_at.

I really doubt that is what you want. I can assume that you just want
GROUP BY feeds.id
------------------------------------------------------
So here's my question: Why having ->groupBy('feeds') produces this dreadful GROUP BY, instead of what you would expect GROUP BY $entity.$primary_key?

**Comment by Raydiation** [comment]
Full group by is needed by postgres ;)

Increase your buffer further

**Comment by patlajan** [comment]
Thanks for the answer Raydiation,
Any way to configure/override that behavior?

**Comment by Raydiation** [comment]
No, also I don't this is an issue, however feel free to tinker with it and please report your findings :)

**Comment by Raydiation** [comment]
You can also remove the thing, but test if it works on postgres https://github.com/owncloud/news/tree/master/db

**Comment by Raydiation** [comment]
Ok, tested on postgres and it still works fine :)

Can you check if it uses less ram?

**Comment by Raydiation** [comment]
> Adding to this, though, Postgres 9.1 allows to not list all columns if their table's primary key is part of the group by clause.

http://stackoverflow.com/questions/1769361/postgresql-group-by-different-from-mysql

**Comment by patlajan** [comment]
Raydiation,
Thank you for the answers

I'm on MySql. My idea was if there is a config to say "expandGroupBy" so I can set it to *false* and override this behavior, as I only want to group by the primary key.

I guess not. My other question is if there is a particular place that you can point me to look at if I eventually decide to make a fix for myself.

The alternative, of course, is to go through every query and change the groupBy statements but that is far from optimal.

**Comment by Raydiation** [comment]
I've already removed it, please test master

**Comment by patlajan** [comment]
Ok, thank you!
