### ISSUE TITLE
Accessing social media

### ISSUE THREAD

**Issue by onewaypub** [owncloud/news#587]
Here some ideas which could be a nice enhancement to owncloud news in the future. For example add access to facbook, twitter, xing data. With this you could load feeds from facebook, twitter and xing to the news app

**Comment by joeplus** [comment]
What do you mean in particular , e.g. for twitter? Authentication, Limits?

**Comment by joeplus** [comment]
Hehe, yep thats what I thought as well when reading through the APIs. Second token will be received by something like "login with twitter".

I will se what I can do, haven't been coding for a while and I am also new to the git thing as well. Seems like a big project to begin with, but we'll see how it goes and when I can find the time. Twitter would just be great for announcement for products and so on that just don't have a rss feed, which seems to decrease in my eyes. I also made some enhancers but I guess I have to create a PR for these as well to get them integrated (e.g. engadget.com).

That was actually a brilliant idea in my opinion, very helpful!
