### ISSUE TITLE
Updater packaging

### ISSUE THREAD

**Issue by BernhardPosselt** [owncloud/news#705]
I'm currently playing around with OBS (https://build.opensuse.org/package/show/home:raydiation/owncloud-news-updater) and RPM packages. This is the current status (still WIP, does not yet build): https://github.com/owncloud/news/blob/master/bin/updater/packaging/rpm/owncloud-news-updater.spec 

If someone is interested in providing deb packages feel free to join in, @bjoerns1983 any plans?

PS: We should probably move the updater into its own repository

@cosenal

**Comment by bjoerns1983** [comment]
Problem is that i have no idea of how to create deb packages, or how to use the OBS build system.
But i think the idea is good.

**Comment by BernhardPosselt** [comment]
Closing since the updater is now in a separate repo and people from all sorts of distros are basically working on this. Additionally, the newest version has been published to pypi which allows anyone on basically any distro to install the updater via pip.
