### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/news#707]
I'm getting the following almost every minute in the log from the systemd updater:

Jan  3 18:03:20 oc owncloud-news-updater: 2015-01-03 18:03:20,911 - ownCloud News Updater - ERROR - http://oc.localhost/index.php/apps/news/api/v1-2: Expecting value: line 1 column 1 (char 0) Trying again in 30 seconds

@Raydiation What's wrong here?

**Comment by Raydiation** [comment]
There is no reply, try to call the update api route with curl

**Comment by Raydiation** [comment]
Are you running the newest version btw?

**Comment by fossxplorer** [comment]
Hi, ok i'll test with curl.
Yes, i'm using current master and i'm on commit 026f5682ba1cd7af9f9abda43c73bd4511180acb.

**Comment by fossxplorer** [comment]
It was kinda weird behaviour as i saw queries from the updater were being processed by the DB. I guess the error is related to my very little knowledge with OpenLiteSpeed web server and it's LSAPI i was using as PHP handler. Everything is fine when i switched to Apache :)
Thx @Raydiation
