### ISSUE TITLE
Overwrite sorting for a feed

### ISSUE THREAD

**Issue by pank** [owncloud/news#711]
Related to #161.  I hope it's not a duplicate.

I read both "News Feeds" (say BBC News) and "Story Feeds" (say [History of Rome](http://thehistoryofrome.typepad.com/the_history_of_rome/)).  I would like to choose the sort order of my "story feeds" to be old → new and everything else new → old.  *Basically, I want to overwrite the ordering for specific feeds*.

The issue is particularly problematic when you are 50 issues behind and the otherwise sensible "mark-as-read-on-scrolling"-feature enabled as it becomes very hard to get to the next (oldest unread) feed.

**Comment by Raydiation** [comment]
Have you tried to use the reverse ordering setting in the settings area?

**Comment by pank** [comment]
This seems to be a *global* setting (please correct me if I'm wrong).  That makes it incompatible with my news feeds where I want to have newest entry first.

**Comment by Raydiation** [comment]
Implemented in master, can you test if everything works fine?

**Comment by pank** [comment]
That was quick, thanks!

I will try to setup an image on rhcloud and test it.  I don't have "root" for primary owncloud-account.

**Comment by pank** [comment]
Do you know if this will work out of the box with News-Android-App or whether I should open a seperate issue there to support this new feature?

**Comment by Raydiation** [comment]
This feature is only for the web interface and has nothing to do with the android app

**Comment by pank** [comment]
Bernhard Posselt <notifications@github.com> writes:

> This feature is only for the web interface and has nothing to do with
> the android app

But isn't the new preference /stored/ in such a way that the android
program could read it and apply the desired sorting?  Skimming the patch
it seemed that way, but I'm not familiar with the details of Owncloud News
so I could very easily be mistaken.

Thanks,

**Comment by Raydiation** [comment]
Yes you could expose it in the API (which it currently isnt) but it's just adding a line after https://github.com/owncloud/news/blob/master/db/feed.php#L129:

    'ordering'

Currently we only expose data and not configuration/settings because it might be undesirable to have the same settings on different devices: think of compact vs normal mode, compact mode may be desirable to use on the android app whereas normal mode is perfectly fine on a 22" monitor.

**Comment by pank** [comment]
> https://github.com/owncloud/news/blob/master/db/feed.php#L129:

Thanks for pointing this out.

> Currently we only expose data and not configuration/settings because
> it might be undesirable to have the same settings on different
> devices: think of compact vs normal mode, compact mode may be
> desirable to use on the android app whereas normal mode is perfectly
> fine on a 22" monitor.

I see.  If you consider the "correct" sorting as a fundamental and unique
characteristic of the feed in question it would make sense to expose it.
For books or history-podcasts, as I'd got in mind, I think it would make
sense.  But perhaps there are also cases where it does not make sense to
expose local sorting via the API.  I think you're the better judge
wrt. this issue.

Thanks again!

—Rasmus

**Comment by Raydiation** [comment]
Yep, probably makes sense
