### ISSUE TITLE
Why not stay compatible?

### ISSUE THREAD

**Issue by blaskovic** [owncloud/news#712]
I have a huge problem that I am not able to run news on centos6, because it has php-5.3.3. But the news app uses some php55 (or different version) things like:

    a = []

instead of array() and so.

Why not stay compatible? I assume that lot of users still uses centos6.

**Comment by LukasReschke** [comment]
That's 5.4 notation and ownCloud 8 will also require 5.4… Beside that 5.3 is End-of-Life and receives no more security patches anymore.

Please update your PHP version for example using RHSCL

**Comment by Raydiation** [comment]
@blaskovic we require php 5.4 features like traits and libxml changes that are only available in 5.4. Going back to the old array syntax would not change the 5.4 hard requirement

**Comment by Raydiation** [comment]
You wont be able to run news on centos 6 anyways since the libxml library is too old. Upgrade to any distro listed here: https://github.com/owncloud/news#supported-operating-systems

**Comment by Raydiation** [comment]
PS: Support for centos 6 was dropped 2 years ago
