### ISSUE TITLE
wrong characters display on news

### ISSUE THREAD

**Issue by thenamelessthing** [owncloud/news#713]
I many feed I see wrong character encoding problem.

Here an sample:

![](http://sc-cdn.scaleengine.net/i/40d4cc1f9dc7d97d42e283e3f876ed00.png)

The url rss feed is: http://www.vgchartz.com/article/252814/uk-games-retail-sales-up-12-in-2014-to-23-billion-due-to-the-success-of-the-ps4-and-xbox-one/

**Comment by cosenal** [comment]
The feed itself is broken, see http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Ffeeds.feedburner.com%2FVGChartz

**Comment by thenamelessthing** [comment]
Thanks for the info. At least I know it's not a news problem!
