### ISSUE TITLE
socks5/tor proxy support

### ISSUE THREAD

**Issue by jasonsmith0** [owncloud/news#714]
Since owncloud is often used for people that like maximum privacy and being in control of their own data, it would be really appreciated likely by many users to be able to configure the news app to fetch news via socks5/tor proxy.

Currently one can configure this via proxychains+standard proxy but I think that leaks DNS requests.

Moreover, not sure if standard proxy in news app (standalone) is supported, or if one needs to configure the proxy in owncloud(globally).

**Comment by Raydiation** [comment]
You need to configure it globally, meaning that if you set the proxy settings in the config.php it will also be used in the news app. For socks5/tor proxy support: No idea how it is different but if it is, it should be implemented in core. File an issue there please.
