### ISSUE TITLE
'k' instead of 'r' to refresh 

### ISSUE THREAD

**Issue by cosenal** [owncloud/news#715]
I used to like the pull-to-refresh feature, but I understand a full refresh was annoying for most users.
What if we kind of simulate that beahaviour simply by changing the key for refreshing from 'r' to 'k'? Nothing else will change, except the label »Press r to refresh« will become »Press k again to refresh« (and the key-binding in the code, of course).

**Comment by Raydiation** [comment]
Isn't k already the jump to previous article shortcut? Its very bad to break habits so unless for a very good reason I would not change them. Also r is a nice mnemonic for reload

**Comment by Raydiation** [comment]
Ah i see. What we could do is that we slide up the reload area if you are already at the very top and if it's visible and you press the jump to previous shortcut again it would reload the page

**Comment by Raydiation** [comment]
Basically pressing jump to previous article at the very top will reload the area

**Comment by cosenal** [comment]
that's what I meant

**Comment by Raydiation** [comment]
Very, very cool idea btw, I love it :)

**Comment by cosenal** [comment]
Just tested, it works as expected, thanks!

Maybe we should change the label of the Refresh button, o/w this shortcut is hidden from the user.

**Comment by Raydiation** [comment]
Yeah, the question is though what caption we should add. The r hint to reload is correct, we want to keep that. We dont want the button to grow really large

**Comment by cosenal** [comment]
The r hint is already mentioned in the Keyboard Shortcut page. Maybe »Refresh (press 'k' once more)«, or something like that

**Comment by Raydiation** [comment]
what about r?

**Comment by Raydiation** [comment]
There are also more possibilities:
* k
* left
* p
* page up
* r

**Comment by cosenal** [comment]
you mean what if you get to the refresh area by pressing page up? hmmm, good point, i don't know...
