### ISSUE TITLE
add button for share article/link

### ISSUE THREAD

**Issue by jajaX** [owncloud/news#716]
Hi ! (sorry for my bad english)

it's possible to add button/option for share article/link directly in "news"?

I have got this option in android news apps !

thanks

**Comment by Raydiation** [comment]
Dup of https://github.com/owncloud/news/issues/154

There are no plans to implement sharing but you can very easily create a plugin that does exactly what you want, see https://github.com/owncloud/news/wiki/How-to-write-Plugins#clientside-plugin

**Comment by thenamelessthing** [comment]
Sad to here the news!  It's the only missing feature... ...

**Comment by Raydiation** [comment]
@thenamelessthing there will always be a missing feature ;)

The important thing is that it's open for modification and anyone who'd like to implement this feature can do it in a few lines of code. 

As for sharing: There are hundreds of platforms and we will always be missing someone's favorite platform. Furthermore I am unsure if we should promote privacy abusing services in a privacy focused app. All in all the complexity if we go for an ownCloud internal solution and privacy concerns for external platforms kept us from putting this onto our todo list. However feel free to release a plugin ;)

**Comment by thenamelessthing** [comment]
Why not just adding this kind of javascript? http://www.sharethis.com/get-sharing-tools/#

**Comment by cosenal** [comment]
@thenamelessthing it's not a technical issue, neither laziness. It's a design choice, see the discussion in #154. 
Again, you can always implement a plugin which uses whatever js and css you want. See for example https://github.com/cosenal/mailsharenewsplugin for a plugin that allows Share by email
