### ISSUE TITLE
Group article action plugins in menu

### ISSUE THREAD

**Issue by BernhardPosselt** [owncloud/news#718]
We should probably use the same kind of menu like for feed actions, otherwise it will likely grow a lot

basically have the three dots icon and when you click on it it should expand all the plugin buttons. The only question is do we make the bar expand horizontally or vertically?

@cosenal

**Comment by cosenal** [comment]
This means you're looking forward to lots of plugins coming up :)
I think it's a good idea and I would say we do the same of feed actions, a pop-up menu with a horizontal bar.

**Comment by stormsh** [comment]
>a pop-up menu with a horizontal bar
I like this pop-up menu. Maybe it should be used for the options Menu as well. Or a quick options Menu on the top?! See the screenshot. Maybe you like it.
![options_final](https://cloud.githubusercontent.com/assets/4153852/9839206/2212ba6c-5a72-11e5-94f9-191efc16e875.jpg)
