### ISSUE TITLE
String extraction and double translations

### ISSUE THREAD

**Issue by zinks-** [owncloud/news#719]
Hi, I'm with the French translation team

1. The string extraction for Transifex seems to have problems extracting strings such as : https://github.com/owncloud/news/blob/master/js/app/Config.js#L52 Only the first part of the string makes it to Transifex (anything after the + is ignored).

2. Strings are also extracted from the minified versions found in the "build" directory, leading to having duplicates on Transifex, and strings having to be translated twice.

Thanks for looking into it

**Comment by Raydiation** [comment]
I dont actually know how to solve this, @DeepDiver1975 ?

**Comment by wakeup** [comment]
This was exactly what I am planning to report now. Normally the script was able to parse them as one, but not sure why it is like that right now. One dirty solution would be not wrapping the text.

**Comment by Raydiation** [comment]
@wakeup wrapping the line is not a solution and jshint will complain ;D

We should probably fix the perl script instead

**Comment by Raydiation** [comment]
Closing this in favor of https://github.com/owncloud/core/issues/13924
