### ISSUE TITLE
Check and notify for entry updates

### ISSUE THREAD

**Issue by cosenal** [owncloud/news#720]
The app should detect whenever entries of the aggregated feeds have been updated from the last visit. For instance, this happens when a blog author makes a correction to one of his posts.

From a UX point of view, different behaviors could be implemented: 
 1. (probably the easiest option) the entry is marked again as Unread and bumped to the top of the feed;
 2. a new collection of »Updated articles« is created;
 3. (dreamland) a diff of the different versions is highlighted.

The tags `<lastBuildDate>` (RSS) and `<updated>` (Atom) can be used for this. Perhaps picoFeed needs to be patched in order to parse those tags.

Note: some feeds abuse of this and should be blacklisted, e.g., and entry on a Youtube feed is updated every time a comment has been made. 

@Raydiation @jancborchardt

**Comment by jancborchardt** [comment]
As far as I remember other feedreaders do not really do anything on updated feeds. They definitely do not have »Updated articles« nor do they force it unread on you again.

What’s the use-case behind that? Mostly feed corrections are spelling errors or some addendums. I don’t think that necessitates pushing it to people again. It could be a silent update to the existing article, but not anything like mark as unread or introducing a new section.

**Comment by Raydiation** [comment]
Most blogs that i follow ship significant updates. Also sometimes blogposts on gnome.org appear broken because the initial release was not updated. We also have this on owncloud planet. 

The update could be made to only mark non blacklisted articles unread, so all articles would get updates, but we can control unwanted unread updates by using a blacklist

**Comment by jancborchardt** [comment]
How do I even blacklist articles? Pushing updates onto people by default doesn’t seem like a good pattern.

**Comment by cosenal** [comment]
Most of the blogs I follow have significant updates too. 
For an example, see the following post: http://www.scottaaronson.com/blog/?p=2155
You don't need to read the whole thing, of course, just notice the lines with red mark »UPDATE«. You can understand that I can't miss those updates!
Maybe they're using the blog improperly, I don't know, but most certainly I am not going to change their minds.

The fact that other feedreaders don't do this is even more motivating. It's definitely not a standard feature, but if we only stick to standard features, as we did so far, we'll never rule the world. It's time for News to step up and implement cool things that are nowhere else implemented!

**Comment by Raydiation** [comment]
You can blacklist YouTube for instance so that videos won't be updated

**Comment by Raydiation** [comment]
Because YouTube has this annoying feature to mark an article as updated if a new comment appears

**Comment by cosenal** [comment]
just to clear the confusion, we are not talking about user blacklisting, but hardcoded blacklisting

**Comment by jancborchardt** [comment]
Ok so then let’s start small by just marking updated articles as unread. But not pushing them up in the timeline, nor having an entry »Updated articles«. Start small.

**Comment by cosenal** [comment]
The only problem with that way is that the user will not understand what is going on: "wtf, I have already read this article, stupid buggy News app!"

**Comment by jancborchardt** [comment]
Simple: Add the text `(updated)` at the end of the title.

**Comment by markusj** [comment]
Please add, in any case, a per-feed option to ignore updates. There are broken feeds out there, and there are even more feeds with updates which i do not care about at all, mostly because they pop up several times after fixing punctuation or similar minor flaws.

**Comment by Raydiation** [comment]
@markusj if we blacklist feeds it will be done in a json or php config file and per feed basis. You will be able to edit them pretty easily but they'll will be overwritten on an app update so you commit your changes back so everyone can profit

**Comment by markusj** [comment]
@Raydiation i think this will not work well, because it is a decision of personal taste to ignore or follow updates of a particular feed.

**Comment by Raydiation** [comment]
Not really ;) 

If a feed fixes punctuation etc they will also fix links and add more content. You don't want to blacklist those. Broken feeds however can easily be classified as broken and blacklisted. We can also react to extreme cases

**Comment by markusj** [comment]
> If a feed fixes punctuation etc they will also fix links and add more content. You don't want to blacklist those.

Pretty sure i want to blacklist those, if the benefit of their updates is far less compared to the annoyance of reading the same article the third or fourth time. Before owncloud/news i used Brief for Firefox as newsreader, which handled updates but thankfully allowed me to ignore them. During this time, maybe 95% of all updates did not matter at all. If you follow about 50 feeds you need to keep this noise down.

**Comment by Raydiation** [comment]
Hm, go for white listing instead?

**Comment by markusj** [comment]
> Hm, go for white listing instead?

I do not think this would scale well. It might work if it would be possible to include a local whitelist, but this is not really user friendly either.

**Comment by Raydiation** [comment]
OK updating without changing the state should be fine then. We don't need any black or white lists and unread and starred articles will stay up to date

**Comment by cosenal** [comment]
From a UX point of view, I don't see anything wrong with markusj's initial proposal to have a user option to ignore updates on a per-feed basis. The user will not have to intervene if not for rare cases when it's annoyed by the noise. Of course, we should test this with our own list of feeds.

**Comment by Raydiation** [comment]
Yeah but I don't want to add yet another button and don't want users to manually turn on/off feed updates. That's actually not something you should have to deal with. Let's first get this in without status changes and then see if it's really needed

**Comment by cosenal** [comment]
sounds good

**Comment by BernhardPosselt** [comment]
This is probably fixed already by letting users decide per feed if they don't want to receive updates and if updated articles should be marked as unread. Closing hence.
