### ISSUE TITLE
News icon in app manager

### ISSUE THREAD

**Issue by wakeup** [owncloud/news#721]
I don't know whether it is the local or appstore one, but news app icon is shown twice in the app manager. This is only for news app :/

![image](https://cloud.githubusercontent.com/assets/231068/6067623/51fad2a4-ad76-11e4-9d8e-766ad65114f5.png)

**Comment by cosenal** [comment]
I can't reproduce this. What version of core are you running? 
You have two instances of News in that page, why so?

**Comment by wakeup** [comment]
@cosenal It is git-master branch. Two, because I have appstore enabled (in apps2 dir) and also have a clone of news repo (in apps dir).

**Comment by cosenal** [comment]
If you use the same setup, this happens with other apps too, see Music, for example. Can you please move it to core?

![screenshot from 2015-02-06 11 53 47](https://cloud.githubusercontent.com/assets/1048336/6083479/e09bd38e-adf6-11e4-9b59-050b4d90389c.png)
