### ISSUE TITLE
Display issue in Safari 8.0.3

### ISSUE THREAD

**Issue by heubergen** [owncloud/news#722]
I have install ownCloud 8, Safari 8.0.3 and install all Dependencies.

When I display my feeds in the compact view on safari, I see the follow:
![bildschirmfoto 2015-02-09 um 13 24 44](https://cloud.githubusercontent.com/assets/5529410/6116108/0a1fb300-b05f-11e4-9214-0e6e91d01f05.png)
With the same installation everything works on Opera, so I think the problem is only by Safari.

**Comment by bfarkas** [comment]
I have also noticed that, as has someone else in the past. Unfortunately Safari is not supported officially. Maybe some Safari user with a bit more CSS knowledge can help?

**Comment by cosenal** [comment]
Indeed, we don't support Safari, see https://github.com/owncloud/news#bugs
