### ISSUE TITLE
Can't see post contents anymore

### ISSUE THREAD

**Issue by pmk1c** [owncloud/news#724]
I hope its not due to a config option I don't know of or something, but since I updated to OwnCloud 8 and News App 5.2.2 I can't see post contents anymore.
I only see the title (I don't have compact mode activated).

**Comment by cosenal** [comment]
Please read this: https://github.com/owncloud/news#bugs
It's hard to diagnose the issue with so less information.

**Comment by pmk1c** [comment]
I enabled logging, but there are no logs regarding the news app in owncloud.log. But I did find another reason, that might have to do with it. My server has libxml 2.7.6.0 installed while the news app seems to need 2.7.8.

**Comment by cosenal** [comment]
Closing this for now. Let us know if the problem persists with all updated requirements.
