### ISSUE TITLE
picoFeed web scraper and News article enhancers

### ISSUE THREAD

**Issue by cosenal** [owncloud/news#725]
PicoFeed and News both support a way to extract full content from the feed's website.

Now that we switched to picoFeed, our article enhancers mechanism looks redundant. Why don't we get rid of it to make News code slimmer and we "gift" all the xpath rules to picoFeed?

See relevant documentation:
https://github.com/owncloud/news/wiki/Article-Enhancers
https://github.com/fguillot/picoFeed/blob/master/docs/grabber.markdown#web-scraper

@Raydiation @fguillot @icewind1991

**Comment by Raydiation** [comment]
:+1:

**Comment by Raydiation** [comment]
Less code, less bugs, less work

**Comment by Raydiation** [comment]
Current status
* [x] Global enhancers that remove autoplay on youtube have been integraged
* [ ] https://github.com/fguillot/picoFeed/pull/131 merged which adds all of our features to the picofeed lib and allows us to migrate our enhancers
* [ ] Migrated regex article enhancers
* [ ] Migrated xpath article enhancers
* [ ] Removed article enhancer code from the app

**Comment by cosenal** [comment]
and... @Raydiation is awesome!
