### ISSUE TITLE
Sort items by date (Crescent/Descending)

### ISSUE THREAD

**Issue by mauriciogardini** [owncloud/news#727]
From time to time, I have some busy days and I am not able to check my daily RSS feeds. And then, a lot of items to be read accumulate.

I'd like to be able to sort the items by date, more specifically in crescent order, so I could work my way up from the oldest items to the newest.

I don't know if anybody has the need of this feature as well, so I thought that I could at least create an issue here to discuss it.

**Comment by cosenal** [comment]
If you go to Settings (cog-wheel at the bottom left of your screen), you find an option to do that. It's called »Reverse ordering (oldest on top)«.

**Comment by mauriciogardini** [comment]
There is no such option for me. There is a toggle for "Use compact view" and some buttons for subscriptions and starred items export.

Is it a feature that was recently implemented?

**Comment by cosenal** [comment]
Yes, what version of News are you running? 
Try the latest one from git, you can also choose view order of a single feed.

**Comment by mauriciogardini** [comment]
I will try it. I am using an old version of Owncloud, so I'll have to update that first.

Thanks for now.
