### ISSUE TITLE
Push down Explore button

### ISSUE THREAD

**Issue by cosenal** [owncloud/news#728]
After looking at that »Explore« button for a month, I got sick of it, why don't we push it at the bottom of the feed list?
It's definitely not something that deserves to be seen everyday. After all, it's only useful if you don't have your own list of feeds to enjoy :) 

@Raydiation @jancborchardt

**Comment by Raydiation** [comment]
Makes also sense regarding ordering :+1:

Should be easy to do, can you create a pull request?

**Comment by jancborchardt** [comment]
Yep – something you might wanna see when you’re done reading all the feeds. :) Good call.

**Comment by cosenal** [comment]
ok, I'll take this one, PR coming in the weekend.

**Comment by Raydiation** [comment]
Bzw, did you check the keyboard shortcuts

**Comment by cosenal** [comment]
yes, not affected by this
