### ISSUE TITLE
 updating after owncloud 8 upgrade

### ISSUE THREAD

**Issue by buzzra** [owncloud/news#730]
I tried to update news using the "update to 5.2.2" button in the ownCloud web client. It came back done with no errors, but still showed the older version. when I logged out and back in, the app showed 4.3.0 and the "update to 5.2.2" button was present. What is the correct way to update? If the button doesn't work, why is it there? The documentation on github has instructions for upgrading from a git install and upgrading from prior to version 4, but only shows how to install from archive. How do you upgrade an archive install?

Thanks for a great app. Really enhances the usefulness of a personal ownCloud.

**Comment by Raydiation** [comment]
It could be that your directory is not writable, anyways core issue, reopen there ;)

**Comment by buzzra** [comment]
This is a OC CORE issue? Cool, I didn't know the news app was a core app now. Congrats. The directory IS writeable. I have been using the news app on previous versions. The old (4.3.0) version is still working on OC8, but seems to cause more cron.lock files than on OC7.

**Comment by Raydiation** [comment]
Nope, news is not in core, it's just everything that is related to app installation update etc is handled by core. 

PS did you check the app requirements?
