### ISSUE TITLE
Error in owncloud.log after activating news app / Update feeds not working

### ISSUE THREAD

**Issue by TheReal1604** [owncloud/news#731]
Hi Guys,

after upgrade to own cloud 8 my new downloaded news app not working anymore. There are the old feeds and news entrys, but there are no chance to update the feeds. I have this done before with the cron.php and a cronjob.
On my Debian Server i got an apache and php 5.4 installed.

After i activate the news app, i got this in the log:

[{"reqId":"8a170b5e9a54919d8f2dddfd06b567ca","remoteAddr":"172.22.0.244","app":"news","message":"Configuration value \"simplePieCacheDuration\" does not exist. Ignored value.","level":2,"time":"2015-02-13T11:51:30+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/admin"},{"reqId":"a2b1ecf03ffb8bae9e78a6bf6b67d1c6","remoteAddr":"172.22.0.244","app":"index","message":"Exception: {\"Message\":\"Unable to generate a URL for the named route \\\"news.page.index\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(282): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('news.page.index', Array, false)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/urlgenerator.php(42): OC\\\\Route\\\\Router->generate('news.page.index', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/config\\\/appconfig.php(109): OC\\\\URLGenerator->linkToRoute('news.page.index')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/config\\\/appconfig.php(86): OCA\\\\News\\\\Config\\\\AppConfig->registerNavigation()\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/appinfo\\\/app.php(29): OCA\\\\News\\\\Config\\\\AppConfig->registerAll()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(379): require('\\\/var\\\/www\\\/ownclo...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/settings\\\/ajax\\\/navigationdetect.php(9): OC_App::getAppNavigationEntries('news')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n#8 [internal function]: __lambda_func(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('\\\\x00lambda_65141', Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(763): OC\\\\Route\\\\Router->match('\\\/settings\\\/ajax\\\/...')\\n#11 \\\/var\\\/www\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/routing\\\/Symfony\\\/Component\\\/Routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":134}","level":4,"time":"2015-02-13T11:51:00+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/ajax\/navigationdetect.php?app=news"},{"reqId":"75a1bd9bdf7ab24d0c71af8c8e22f840","remoteAddr":"172.22.0.244","app":"news","message":"Configuration value \"simplePieCacheDuration\" does not exist. Ignored value.","level":2,"time":"2015-02-13T11:50:44+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/admin"}]

Did anyone have an idea? Thanks!

Greets
Brian

Edit: After recreating my /data/news folder new i get now this error:
{"reqId":"4fe4f0b41e910937fbc4755ed0481d1f","remoteAddr":"","app":"no app in context","message":"Error while running background job: Could not determine user","level":3,"time":"2015-02-13T12:34:38+00:00","method":"--","url":"--"},

**Comment by Raydiation** [comment]
Read the upgrading from versions prior to 4 section in the readme. As for the other error, you're likely missing a file or it isn't readable (appinfo/routes.php), just reinstall the news app

**Comment by Raydiation** [comment]
BTW you don't need a data news folder, you need to put it into apps.

**Comment by Raydiation** [comment]
The folder is created automatically for you

**Comment by TheReal1604** [comment]
Hi Raydiation,

the first error appearing after reinstallation too... i have checked the file system rights, www-data got owner rights on the necessary folders.

With "recreating" i mean what you describe.. (rm /data/news) and let it recreate automatically. 

The appinfo folder is at my installation at /var/www/owncloud/apps/news/appinfo.. and the owner is www-data. 

any other suggestions?

Thanks for the amazing work. 

Greetz

**Comment by Raydiation** [comment]
Does /var/www/owncloud/apps/news/appinfo/routes.php exist?

If it does, can you reopen it in core? This is a core bug regarding routing if the file is present
