### ISSUE TITLE
Empty iframe in Hackaday articles

### ISSUE THREAD

**Issue by bfarkas** [owncloud/news#734]
I noticed there is an empty iframe in Hackaday articles. Does this happen also with other feeds?
Below is a screenshot of how it looks for me.
![news_hackaday_iframe](https://cloud.githubusercontent.com/assets/8792579/6225092/eb9a7c30-b685-11e4-80fa-470a8f7ec1ea.png)

**Comment by Raydiation** [comment]
We only allow https youtube and vimeo iframes to combat active mixed content. The feed that you've provided uses http youtube videos which could be an attack vector for MITM attacks

**Comment by Raydiation** [comment]
Contact the page author to only include https iframes

**Comment by Raydiation** [comment]
I think that we can simply replace all youtube links that start with http with https, I will try to get a fix into picoFeed so this won't be a problem anymore :)

**Comment by bfarkas** [comment]
cool, sound good!

**Comment by Raydiation** [comment]
Fixed in 5.2.5
