### ISSUE TITLE
"moment.locale is not a function" error

### ISSUE THREAD

**Issue by johnwoltman** [owncloud/news#735]
The news app has stopped working for me with owncloud (from RPM package version owncloud-8.0.0-22.1).  When I go to my news, the blue owncloud navbar is displayed across the top of the page, but the rest of the page is blank (white).

When I load the page with Firefox's web inspector, I see a javascript error in the console: ``TypeError: moment.locale is not a function`` on line 1027 of ``js.js``.

**Comment by Raydiation** [comment]
Can you clear your cache (Ctrl +r)?

**Comment by johnwoltman** [comment]
I cleared my cache with CTRL+R, but I stlll have the same issue.  I also tried clearing all my history/cookies/cache but that did not fix the issue either.  The same thing happens with Chrome.

**Comment by Raydiation** [comment]
Do you run the latest version?

**Comment by johnwoltman** [comment]
8.0.0-22.1

**Comment by johnwoltman** [comment]
I backed up my config.php, removed ownCloud, and reinstalled it.  Then I restored my config.php.  The issue still occurs.

**Comment by Raydiation** [comment]
I mean latest news version. Can not reproduce your problem btw.

**Comment by cosenal** [comment]
It sounds like a packaging problem to me (the core RPM package that OP has installed). 

@johnwoltman Do other apps work fine?

**Comment by Raydiation** [comment]
@cosenal you're right, since the error appears in a js file in core

**Comment by Raydiation** [comment]
We are also bundling moment is btw

**Comment by johnwoltman** [comment]
I'm running owncloud-news 2.002

**Comment by Raydiation** [comment]
That version is not supported anymore, please upgrade ;)

**Comment by johnwoltman** [comment]
Thanks.  Not sure how that old version stuck around :)
