### ISSUE TITLE
Enhancer for sueddeutsche.de is broken (I think)

### ISSUE THREAD

**Issue by kgraefe** [owncloud/news#736]
sueddeutsche.de delivers a short summary of the article via RSS. The enhacer removes this summary completely and replaces it by the full text. That means that I need more reading to get to the point of the article (especially if I am not super-interested and just need that overview).

Plus when the article is a long one it is splitted into multiple pages on the website which confuses the enhancer so that it just displays the first part without any indication that the article is going on... And, of course, the website is way better in formatting its own articles.

**Comment by Raydiation** [comment]
Enhancers are basically maintained by the community (most PRs contain enhancers) so it would be nice if you could send a PR that fixes your problems.

As for the feed in question: I just pushed some changes, namely include stuff besides the p tag. Can you check again? As for the formatting: you can add custom css per feed https://github.com/owncloud/news/wiki/Adding-Custom-CSS

**Comment by Raydiation** [comment]
Reopen if you find other issues or create a PR if you want to tweak it.

**Comment by kgraefe** [comment]
It is better now. Thank you.
