### ISSUE TITLE
Update from 5.2.2 to 5.2.6 stopped running

### ISSUE THREAD

**Issue by yellowcow1100** [owncloud/news#738]
Updated on my Synology Server.
This is the error message from the log: 
Exception: {"Message":"Could not resolve OCA\\News\\Controller\\PageController! Class OCA\\News\\Service\\StatusService does not exist","Code":0,"Trace":"#0 \/volume1\/web\/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(93): OC\\AppFramework\\Utility\\SimpleContainer->resolve('OCA\\\\News\\\\Contro...')\n#1 \/volume1\/web\/owncloud\/lib\/private\/appframework\/app.php(90): OC\\AppFramework\\Utility\\SimpleContainer->query('OCA\\\\News\\\\Contro...')\n#2 \/volume1\/web\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(44): OC\\AppFramework\\App::main('PageController', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#3 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#4 \/volume1\/web\/owncloud\/lib\/private\/route\/router.php(250): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#5 \/volume1\/web\/owncloud\/lib\/base.php(763): OC\\Route\\Router->match('\/apps\/news\/')\n#6 \/volume1\/web\/owncloud\/index.php(36): OC::handleRequest()\n#7 {main}","File":"\/volume1\/web\/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php","Line":79} 

Any clue what this causes?

**Comment by Raydiation** [comment]
How did you update? You are missing a file in service/statusservice.php or it is not readable

**Comment by yellowcow1100** [comment]
Just by updating via integrated update function in Owncloud.

File does not exist (anymore).

**Comment by Raydiation** [comment]
Ok, try to reinstall news by deactivating it, removing the folder in apps/ and reinstalling it, that should fix it ;)
