### ISSUE TITLE
Feeds are not updated

### ISSUE THREAD

**Issue by ratzefux** [owncloud/news#740]
Hello,
I have 8 installed OC fresh on a shared hosting package .
News is available in version 5.2.6 .
When I add new feeds , all news items are picked up. The problem of steady until the feed to be updated.
For this, I use a Webcron service that calls the cron.php every 15 minutes.
This works well so far . If I cron.php manually in the browser views I get the expected success .
Only the feeds are not updated ....
What do I do?
Thanks in advance ....

**Comment by Raydiation** [comment]
Did you go through https://github.com/owncloud/news#all-feeds-are-not-updated-anymore ?

**Comment by ratzefux** [comment]
Hello,
I use a Webcron service .

I can not verify because it is not available to me the system cron.

Unfortunately, I know not the www -user described .

The part about the alternative updater I have read though, but it is understood that he brings me something if I have my own server .

I still have a second instance of the web hosting package. This runs OC7.4 and News 2,002 .
Here everything works. However, I have also installed the app framework here .

regards
Ratzefux

**Comment by Raydiation** [comment]
I think its the cron lock issue which also happens when using webcron. On 8 this issue is much more frequent because an app (search_lucene) has some bugs and crashes the updater iirc.

I've created a fix for the cron issue (https://github.com/owncloud/core/pull/14400) but apparently it wont be backported. So I'd recommend for now to use the python updater. You can install the python updater on the host that also runs your webcron (if you have control over it) and set the url in the config file. More here https://github.com/owncloud/news/tree/master/bin/updater

**Comment by Raydiation** [comment]
Or you could run core master which has the fix included

**Comment by ratzefux** [comment]
Wie kann ich den core master einsetzen?

**Comment by ratzefux** [comment]
Sorry, wrong language...How can I use the core master ?

**Comment by Raydiation** [comment]
https://github.com/owncloud/core/archive/master.zip
https://github.com/owncloud/3rdparty/archive/master.zip

Du musst die ordner richtig zusammestückeln. der inhalt von 3rdparty mit den vielen ordnern gehört in das 3rdparty verzeichnis von core. Hast du zufällig ein Linux system? Da gestaltet sich das viel leichter, einfach https://github.com/owncloud/ocdev#installation installieren und

    ocdev setup base --dir owncloud

Danach kannst du den ordner hochladen

**Comment by Raydiation** [comment]
Ok, anscheinend gibt es daily builds http://download.owncloud.org/community/owncloud-daily-master.tar.bz2

**Comment by ratzefux** [comment]
also schiebe ich einfach nur die Dateien aus dem daily-Zweig auf meinen Webspace?

**Comment by Raydiation** [comment]
Ja aber config und data Ordner behalten

**Comment by ratzefux** [comment]
Ups...das hat nicht funktioniert. Nach dem Austausch der Daten hat OC auf 8.1 pre alpha aktualisiert. Dabei wurden so ziemlich alle wichtigen apps deaktiviert. Bei dem Versuch sie wieder zu aktivieren, habe ich dann irgentwann nur noch leere Seiten zu Gesicht bekommen ;-(
...also Backup wieder eingespielt ;-)

**Comment by Raydiation** [comment]
Kannst du http://download.owncloud.org/community/owncloud-daily-stable8.tar.bz2 probieren? Das löst zwar nicht den bug aber vielleicht ist die search APP schon gefixt. Ansonsten kann ich dir nur empfehlen, den updater auf einem anderen Server laufen zu lassen oder auf einen fix zu warten

**Comment by ratzefux** [comment]
Damit aktualisiert er auf OC 8.0.1 (ohne pre alpha)
Die Apps lassen sich wieder aktivieren. Die Feeds werden aber dennoch nicht aktualisiert.
Logs sagen:
Debug 	lock 	FREE: Released locks on /hp/zy/aa/ap/www/xxxxxx/data/news/config/config.ini 
Debug 	lock 	INFO: Released lock handle Resource id #218 on /hp/zy/aa/ap/www/xxxxx/data/news/config/config.ini

**Comment by Raydiation** [comment]
Entferne die data/cron.lock Datei

**Comment by ratzefux** [comment]
...ist nicht vorhanden

**Comment by ratzefux** [comment]
...also ich habe sie nicht entfernt, sie war vorher schon nicht vorhanden.

**Comment by Raydiation** [comment]
Ok, dann keine Ahnung, warte auf den fix oder verwende den updater.

**Comment by ratzefux** [comment]
OK....hab trotzdem vielen Dank

**Comment by xn--nding-jua** [comment]
Hey,

see this issue for a possible workaround using webcron: https://github.com/owncloud/core/issues/8531

kind regards,
Chris

**Comment by cosenal** [comment]
@ratzefux @Raydiation Please keep the issue tracker in English!
