### ISSUE TITLE
"Milestones" list here at github is not maintained

### ISSUE THREAD

**Issue by rakekniven** [owncloud/news#741]
Please see https://github.com/owncloud/news/milestones
It is outdated. Please spend some minutes.

**Comment by Raydiation** [comment]
Milestones are only used if there is a goal. Currently there is no goal, so there is no milestone ;)

Compared to core there is basically only one active contributor (me) so I dont have to spend time on doing project management what basically means that there is no need to use milestones.

Basically stuff just trickles, gets merged and released.

**Comment by rakekniven** [comment]
Got your point.

Why not closing old milestones and leave list empty?

**Comment by Raydiation** [comment]
Hm, I thought having 100% closes them automatically. So apparently there is also a close button :D
