### ISSUE TITLE
Update to v5.2.7 by WebUI not working

### ISSUE THREAD

**Issue by rakekniven** [owncloud/news#742]
ownCloud version : 8.0.0

Just tried to update from 5.2.6 to 5.2.7 and it failed.

Screenshot from app menu:

![oc8-news-app-update-error-app](https://cloud.githubusercontent.com/assets/2069590/6426788/84c7fa8e-bf6b-11e4-8fde-67637bd0008f.png)
Screenshot of log message:

![oc8-news-app-update-error-log](https://cloud.githubusercontent.com/assets/2069590/6426789/8e70d808-bf6b-11e4-98cb-967323860b0f.png)

Did an update from 5.2.2 to 5.2.6 this morning and it works fine (WebUI)

**Comment by Raydiation** [comment]
Try again :)

**Comment by rakekniven** [comment]
Update worked now. Confirmed.

**Comment by Raydiation** [comment]
This is a really unhelp error message btw. Could you file a bug in core?

**Comment by Raydiation** [comment]
The issue was the the version number in the uploaded release was still 5.2.6

**Comment by rakekniven** [comment]
I cannot any information about the cause of it. Only you know :wink:
