### ISSUE TITLE
Cron <www-data@myhost> php -f /var/www/owncloud/cron.php

### ISSUE THREAD

**Issue by icewater** [owncloud/news#746]
PHP Fatal error:  Call to undefined method ZendXml\Security::scanHtml() in /var/www/owncloud/apps/news/articleenhancer/globalarticleenhancer.php on line 35
Unexpected error!

Any ideas?

**Comment by cosenal** [comment]
Worst title of a bug report I have ever seen. Please read https://github.com/owncloud/news#when-reporting-bugs

**Comment by Raydiation** [comment]
Update to the latest version

**Comment by GabrieleV** [comment]
Using latest debian packages and 5.2.8: the problem persist.
See https://github.com/owncloud/core/issues/14209

**Comment by rpadovani** [comment]
@Raydiation the bug is still present, and it's very annoying

**Comment by Raydiation** [comment]
@rpadovani you've probably got php caching issues, the lib has been removed in newer versions and the code that produces the error is not present any more.
