### ISSUE TITLE
PHP Fatal error: getTimestamp()

### ISSUE THREAD

**Issue by LIyoai** [owncloud/news#747]
Update to owncloud 8.0.1 and news 5.2.7.
Now I get an error when I run `php -f /var/www/owncloud/cron.php`

PHP Fatal error:  Call to a member function getTimestamp() on a non-object in /var/www/owncloud/apps/news/fetcher/feedfetcher.php on line 152
Unexpected error!

**Comment by Raydiation** [comment]
Can you post your feeds/feed that causes this? Can you also check if all files match the ones in the release, especially the vendor directory

**Comment by LIyoai** [comment]
Just removed the news folder and downloaded it again. Now it is working again.
So the update through owncloud was broken.

**Comment by FriedCircuits** [comment]
Just wanted to add a note that I had the same problem. I recently turned on the news app and upgraded to 8.1.1 and noticed cron not running. This solution ended up fixing it. Thanks.

**Comment by Raydiation** [comment]
FYI the next version (6, already in master) will feature a command that let's you verify that all files are in place (./occ news:verify-install)
