### ISSUE TITLE
Sidebar is buggy

### ISSUE THREAD

**Issue by mauriciogardini** [owncloud/news#748]
Some minutes I was reading my feeds in News with no problem. But, all of a sudden...

http://i.imgur.com/pqFwVO1.jpg

(I can't attach images for some reason. I keep getting a " Yowza, that's a big file. Try again with an image file smaller than 10MB.", and my file is 50kb.)

Any insights?

**Comment by cosenal** [comment]
We can't help you if we don't know any detail, see https://github.com/owncloud/news#when-reporting-bugs

**Comment by Raydiation** [comment]
Can you part your js console output after you've turned on debug mode? I suppose it's a rare problem, we're currently using an angular beta.

**Comment by Raydiation** [comment]
Post*

**Comment by mauriciogardini** [comment]
cosenal, I'm sorry. I'll update with some info as soon as I am able.

Raydiation, I just tried to reproduce the same error in my work computer and I wasn't able. So, I suppose it isn't something in Owncloud, but in a specific instance of a browser.

If this information helps for now, as I will not be able to access my computer until the end of the day, what happened is that Firefox warned me about a unresponsive script and, when I asked it to debug it, it prompted me to a line with a ".join". 

When I tried to print the array that it was trying to join, the debugger told me it was an array like this: ["", 9 empty spaces, 14834383 (Or some other big number)].

After a source code search, as far as I can remember the culprit line was this: https://github.com/owncloud/news/blob/1202f8db1046106860dde1f9303acb55174ff975/js/vendor/angular-route/angular-route.js#L661

Hope this helps in any way for now. I'll try to reproduce the same error in the end of the day in my other computer, and I'll update this thread.

Thanks for now.

**Comment by Raydiation** [comment]
I see unfortunately not something we can fix because it's not reproducible

**Comment by mauriciogardini** [comment]
Here are the information that you asked:
data/owncloud.log (Again, I can't attach it here - Hosted in Dropbox 'cause I don't know if you may have any problems with Files as well)
https://www.dropbox.com/s/x68akd0m33pcq49/owncloud.log?dl=0
ownCloud version: 7.0.4.2
News version: apps/news/appinfo/version says it is 2.002; apps/news/CHANGELOG shows that the latest update on this file was regarding version 2.003.
Browser and version: Firefox Nightly - 39.0a1 (2015-03-10)
PHP version: PHP 5.5.9-1
Distribution: Ubuntu 14.04.1 LTS

Hope that helps.

**Comment by Raydiation** [comment]
2.x has been unsupported for ~1 year, please update ;)

**Comment by mauriciogardini** [comment]
What a shame... I'm using a very old version.

I was postponing updating Owncloud from 7.0.4 to 8.0.2, but to be without News is a great reason to do that.

Well, I updatet Owncloud to 8.0.2 so I could update News to its earliest version and everything is working now.

Thanks for your patience.
