### ISSUE TITLE
Feeds not marked as read after scrolling

### ISSUE THREAD

**Issue by mehturt** [owncloud/news#749]
I installed OC 8.0.2 and news 5.2.7 recently.  I've noticed the following 2 issues:
- feeds are not marked as read when scrolled out
- I cannot click on the feed "menu" - the three dots next to number of unread entries in the feed
There are no errors in owncloud.log

**Comment by cosenal** [comment]
What browser are you using? Any error in the browser console?

**Comment by mehturt** [comment]
Firefox nightly (39.0a1).  No errors in browser console.

**Comment by Raydiation** [comment]
Can you try a stable release?

**Comment by mehturt** [comment]
Ah, correct, that works fine (Firefox 36).

**Comment by mehturt** [comment]
@cosenal sorry, there are errors in browser console

**Comment by Raydiation** [comment]
@mehturt can you post them :)?

**Comment by mehturt** [comment]
Yes, I'm just looking on how to save the console in Firefox.

**Comment by mehturt** [comment]
I did not find a way to add attachments here, so I uploaded them to my dropbox.
FF stable https://www.dropbox.com/s/35bsa14nqszyqr7/news-stable.txt?dl=0
FF nightly https://www.dropbox.com/s/m6hkmtlza227hix/news-nightly.txt?dl=0

**Comment by Raydiation** [comment]
Hm, I cant find a real problem in those erorrs. I think its probably a glitch in the nightly

**Comment by mehturt** [comment]
Ok, so I found out the problem is gone when I disabled E10S in FF nightly.  But then, I enabled it back again and it still works.  So not sure what the problem was originally.
