### ISSUE TITLE
RSS feed : website not found

### ISSUE THREAD

**Issue by StraToN** [owncloud/news#753]
Hello,
I am currently trying to insert an RSS feed into my News. Here is the link : https://desyeuxdebitch.wordpress.com/feed

OC 8.2 refuses this feed. It returns "website not found" error. The feed seems to be reachable and correctly formed according to FeedValidator (http://feedvalidator.org/check.cgi?url=https%3A%2F%2Fdesyeuxdebitch.wordpress.com%2Ffeed%2F)

Is this error related to the URL being https instead of http ?

**Comment by Raydiation** [comment]
Feed works fine for me when i enter https://desyeuxdebitch.wordpress.com/feed/ in the feed input.

**Comment by cosenal** [comment]
Working fine here too. Closing this until new details are received.

**Comment by StraToN** [comment]
Still not working :( Trying to give some more information.

Manual installation of Owncloud 8.0.2.0 (according to config.php)
News 5.2.7
Browsers tested : Mozilla Firefox 20.0 (at work) / Opera 12.16 / Mozilla Firefox 36.0.1 (home)
PHP 5.5.9-1ubuntu4.6 (cli) (built: Feb 13 2015 19:17:11)
OS server : Ubuntu Server 14.10 (up to date)
DEBUG variable set to true, and loglevel => 0,

Log : 

{"reqId":"5d08598677ae9ccc5b7e326ee878b201","remoteAddr":"193.48.246.14","app":"lock","message":"INFO: Read lock requested for \/var\/www\/owncloud2\/data\/news\/config\/config.ini","level":0,"time":"2015-03-17T09:36:28+00:00","method":"POST","url":"\/index.php\/apps\/news\/feeds"}
{"reqId":"5d08598677ae9ccc5b7e326ee878b201","remoteAddr":"193.48.246.14","app":"lock","message":"PASS: Acquired read lock for \/var\/www\/owncloud2\/data\/news\/config\/config.ini","level":0,"time":"2015-03-17T09:36:28+00:00","method":"POST","url":"\/index.php\/apps\/news\/feeds"}
{"reqId":"5d08598677ae9ccc5b7e326ee878b201","remoteAddr":"193.48.246.14","app":"lock","message":"INFO: Incrementing lock type 1 count for \/var\/www\/owncloud2\/data\/news\/config\/config.ini","level":0,"time":"2015-03-17T09:36:28+00:00","method":"POST","url":"\/index.php\/apps\/news\/feeds"}
{"reqId":"5d08598677ae9ccc5b7e326ee878b201","remoteAddr":"193.48.246.14","app":"lock","message":"INFO: Releasing locks on \/var\/www\/owncloud2\/data\/news\/config\/config.ini","level":0,"time":"2015-03-17T09:36:28+00:00","method":"POST","url":"\/index.php\/apps\/news\/feeds"}
{"reqId":"5d08598677ae9ccc5b7e326ee878b201","remoteAddr":"193.48.246.14","app":"lock","message":"INFO: Released lock handle Resource id #189 on \/var\/www\/owncloud2\/data\/news\/config\/config.ini","level":0,"time":"2015-03-17T09:36:28+00:00","method":"POST","url":"\/index.php\/apps\/news\/feeds"}
{"reqId":"5d08598677ae9ccc5b7e326ee878b201","remoteAddr":"193.48.246.14","app":"lock","message":"FREE: Released locks on \/var\/www\/owncloud2\/data\/news\/config\/config.ini","level":0,"time":"2015-03-17T09:36:28+00:00","method":"POST","url":"\/index.php\/apps\/news\/feeds"}
{"reqId":"5d08598677ae9ccc5b7e326ee878b201","remoteAddr":"193.48.246.14","app":"news","message":"Configuration value \"simplePieCacheDuration\" does not exist. Ignored value.","level":2,"time":"2015-03-17T09:36:28+00:00","method":"POST","url":"\/index.php\/apps\/news\/feeds"}
{"reqId":"5d08598677ae9ccc5b7e326ee878b201","remoteAddr":"193.48.246.14","app":"news","message":"Site web non trouv\u00e9","level":0,"time":"2015-03-17T09:36:35+00:00","method":"POST","url":"\/index.php\/apps\/news\/feeds"}

Which other data shall I provide ?

**Comment by Raydiation** [comment]
It could be that your server cant connect to that page, can you try to ping the page from your server?

**Comment by StraToN** [comment]
$ ping https://desyeuxdebitch.wordpress.com
ping: unknown host https://desyeuxdebitch.wordpress.com
$ ping https://desyeuxdebitch.wordpress.com/feed
ping: unknown host https://desyeuxdebitch.wordpress.com/feed
$ ping desyeuxdebitch.wordpress.com
PING lb.wordpress.com (192.0.78.12) 56(84) bytes of data.
64 bytes from 192.0.78.12: icmp_seq=1 ttl=54 time=41.6 ms
64 bytes from 192.0.78.12: icmp_seq=2 ttl=54 time=35.6 ms
64 bytes from 192.0.78.12: icmp_seq=3 ttl=54 time=38.0 ms
64 bytes from 192.0.78.12: icmp_seq=4 ttl=54 time=36.8 ms
64 bytes from 192.0.78.12: icmp_seq=5 ttl=54 time=36.7 ms
64 bytes from 192.0.78.12: icmp_seq=6 ttl=54 time=37.0 ms

I apparently can't reach this page, but I can ping the website. Yet as it is https, I think this is related.

**Comment by Raydiation** [comment]
For the page you need to use something that speaks https, like curl http://stackoverflow.com/questions/2924422/how-do-i-determine-if-a-web-page-exists-with-shell-scripting

**Comment by StraToN** [comment]
Ok, thanks for the information. This showed me the correct way to fix the problem.
The error was simply an iptables rule missing to allow outputs on 443 port.

iptables -t filter -A OUTPUT -p tcp --dport 443 -j ACCEPT

curl then returns correct answer and the RSS feed works correctly.
Thanks a lot.
