### ISSUE TITLE
Serve combined news as RSS feed (feature request?)

### ISSUE THREAD

**Issue by timmi-on-rails** [owncloud/news#754]
Is it possible to serve my articles as RSS feed (link) for use in different RSS readers?
This way the owncloud user can store its RSS feeds and browse with the webapp, but still being able to browse the articles on different devices with a different reader. (I know the owncloud newsreader app, but I have different preferences and devices).

**Comment by Raydiation** [comment]
No, this is a feature that should be handled by a separate app. For that you can directly access the tables of the news app or reuse the classes from the news app like described in the wiki.

The reason for that is that this is a very tricky thing to do in terms of permissions. You can ofc also write a software that serves feeds based on the restful api

**Comment by timmi-on-rails** [comment]
Thank you for the quick answer :-)

**Comment by cosenal** [comment]
fyi, there has been an attempt to make such an app ([FeedCentral](https://github.com/LukasReschke/feedcentral/)), but it was never completed and it's no longer maintained.

**Comment by timmi-on-rails** [comment]
On the README it does not say its not maintained, how do you know? 
I was trying to run it and I get an exception in the application.php that "ItemService" is undefined in ..getContainer()['ItemService'] . Any idea?

**Comment by Raydiation** [comment]
I've updated the docs and the app https://github.com/Raydiation/feedcentral 

Should work now and serve as a good base for implementing what you want

**Comment by timmi-on-rails** [comment]
Thank you so much. I will test it later today.
