### ISSUE TITLE
Update from 5.2.7 to 5.2.8 fails

### ISSUE THREAD

**Issue by reimersjan** [owncloud/news#755]
I tried updating News to 5.2.8 from owncloud/index.php/settings/apps and it fails.

The ErrorLog shows the following:

Exception: {"Message":"Unable to generate a URL for the named route \"news.page.index\" as such route does not exist.","Code":0,"Trace":"#0 \/var\/www\/virtual\/bla\/html\/lib\/private\/route\/router.php(282): Symfony\\Component\\Routing\\Generator\\UrlGenerator->generate('news.page.index', Array, false)\n#1 \/var\/www\/virtual\/bla\/html\/lib\/private\/urlgenerator.php(42): OC\\Route\\Router->generate('news.page.index', Array)\n#2 \/var\/www\/virtual\/bla\/html\/apps\/news\/config\/appconfig.php(109): OC\\URLGenerator->linkToRoute('news.page.index')\n#3 \/var\/www\/virtual\/bla\/html\/apps\/news\/config\/appconfig.php(86): OCA\\News\\Config\\AppConfig->registerNavigation()\n#4 \/var\/www\/virtual\/bla\/html\/apps\/news\/appinfo\/app.php(29): OCA\\News\\Config\\AppConfig->registerAll()\n#5 \/var\/www\/virtual\/bla\/html\/lib\/private\/app.php(386): require('\/var\/www\/virtua...')\n#6 \/var\/www\/virtual\/bla\/html\/settings\/ajax\/navigationdetect.php(9): OC_App::getAppNavigationEntries('news')\n#7 \/var\/www\/virtual\/bla\/html\/lib\/private\/route\/route.php(135) : runtime-created function(1): require_once('\/var\/www\/virtua...')\n#8 [internal function]: __lambda_func(Array)\n#9 \/var\/www\/virtual\/bla\/html\/lib\/private\/route\/router.php(250): call_user_func('\\x00lambda_2258', Array)\n#10 \/var\/www\/virtual\/bla\/html\/lib\/base.php(767): OC\\Route\\Router->match('\/settings\/ajax\/...')\n#11 \/var\/www\/virtual\/bla\/html\/index.php(36): OC::handleRequest()\n#12 {main}","File":"\/var\/www\/virtual\/bla\/html\/3rdparty\/symfony\/routing\/Symfony\/Component\/Routing\/Generator\/UrlGenerator.php","Line":134}

**Comment by Raydiation** [comment]
Please check if all files in the archive are present on your server and your appinfo/routes.php is readable
