### ISSUE TITLE
New published Feed (RSS/ATOM) with the own unread feeds

### ISSUE THREAD

**Issue by darkretailer** [owncloud/news#756]
On this way it should be possible to get the unread feeds in owncloud to Outlook as example.

**Comment by Raydiation** [comment]
We are not planning to add an additional api for a proprietary client and republishing atom/RSS feeds is the job of an additional app that accesses the server side api or db tables directly.

**Comment by darkretailer** [comment]
Ok.
Was just an idea.^^

thanks! :-)

**Comment by Raydiation** [comment]
In case you know php you might want to take a look at https://github.com/Raydiation/feedcentral
