### ISSUE TITLE
Feed update can hang for slow server

### ISSUE THREAD

**Issue by paalsteek** [owncloud/news#763]
For a feed that accepts connections within 10 seconds but does not respond at all the update cronjob hangs forever. This is caused by PicoFeed only setting the CURLOPT_CONNECTTIMEOUT but not the CURLOPT_TIMEOUT. Please add an option for the total timeout.

(An example for a problematic feed is http://www.elektrischer-reporter.de/phase3/rss_webm/)

**Comment by Raydiation** [comment]
Please also open this issue on the picofeed bugtracker: https://github.com/fguillot/picoFeed/issues 

I'd need an additional config setting, I think its in fact easy to implement, take a look at the lib  :)
