### ISSUE TITLE
python news update deamon fails with SNI SSL Sites

### ISSUE THREAD

**Issue by torbennehmer** [owncloud/news#764]
My own OC installations requires clients to support Server Name Indication (SNI) as I am forced to use Name-Based VHosting even with SSL.

Unfortunately this seems to interfere with the updaters SSL handling, making it essentially unusable in this scenario. For security reasons, non-SSL traffic is forbidden and gets automatically redirected back to HTTPS. This should be fixed, as SNI gets more and more common due to IP scarcity.

Error message:
root@server:/root# owncloud-news-updater --testrun --config /etc/owncloud/news/updater.ini
2015-04-09 11:59:41,084 - ownCloud News Updater - ERROR - http://owncloud.my.domain/index.php/apps/news/api/v1-2: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600) Trying again in 30 seconds

The sites SSL configuration is fine (as long SNI works), it uses a StartCOM SSL certificate, the cert chain is delivered correctly by apache. The ssllabs.com SSL Server checks reports no problems of importance.

**Comment by Raydiation** [comment]
SNI is actually supported by the library in use (requests) and should not pose a problem, see http://docs.python-requests.org/en/latest/community/faq/

The lib says it supports it and I've never used SNI, setup seems really complex so I wont work on this issue. You can either write your own updater with these API methods (https://github.com/owncloud/news/wiki/Cron-1.2) or send a pull request that fixes the issue

**Comment by LukasReschke** [comment]
@torbennehmer Please send me the link of your instance and the exact OS and Python version that you used. I might then take a look. - If you don't want to post your domain you can send me a mail. My mail address can be found on my GitHub profile.

**Comment by Raydiation** [comment]
In case its just a configuration issue, depending on the outcome we want to add a separate section in the [docs](https://github.com/owncloud/news/blob/master/bin/updater/README.rst) later on

**Comment by Raydiation** [comment]
Closing this because http://bugs.python.org/issue5639 and https://github.com/kennethreitz/requests/issues/749 is fixed
