### ISSUE TITLE
Website not found

### ISSUE THREAD

**Issue by neupet** [owncloud/news#766]
Hey,
thanks for the great app. I looks pretty good on the first glance. Sadly i have some problems adding the feeds: "Website not found" appears when trying to add any feed.

I tried to access the website via command line:
curl --head https://owncloud.org/feed
It returns HTTP Status: 301

I use a Lighttp Server, MySQL and PHP 5.5.9 (PHPDroid).
Owncloud Version: 8.0.2
News Version: 5.2.8
News default settings.

I didnt find any helpful logfile output regarding to the described problem.

Greets Peter

**Comment by cosenal** [comment]
In order to see the logs, check out https://github.com/owncloud/news#when-reporting-bugs

**Comment by neupet** [comment]
ok thanks. I should really read the README before posting.

I realized that i installed the oc version 8.0.2 which is currently the latest stable version. But in the readme it says ownCloud >= 8.1. Could this may be the problem?

Here is also the log:
http://pastebin.com/raw.php?i=nP0S6b9W

The only important log i could found is:

{"reqId":"60211c4dbfef9cb081191c1c076a7edb","remoteAddr":"192.168.1.151","app":"news","message":"Webseite nicht gefunden","level":0,"time":"2015-04-10T09:02:59+00:00","method":"POST","url":"\/owncloud8\/index.php\/apps\/news\/feeds"}

**Comment by Raydiation** [comment]
The readme is for the next release ;) 

Your current release works fine on 8.0.2, so thats not the issue.

I think the issue here is probably your firewall or server settings, can you check if you can reach those websites from your server terminal when running a ping and traceroute on them?

**Comment by neupet** [comment]
Hmmm i guess you are right. The problem seems to be the curl connection. When using curl i get the error "Could not resolve host". I guess this is because of my webserver configuration :(.
But thanks anyway for the support.

**Comment by cosenal** [comment]
@neupet you can browse to closed issues in this repo to find some common fixes, like this one for example: https://github.com/owncloud/news/issues/753#issuecomment-82374725
