### ISSUE TITLE
No news update when server-side encryption is enabled

### ISSUE THREAD

**Issue by efelon** [owncloud/news#767]
Owncloud 8.0.2
News 5.2.8

As long as server-side encryption is enabled, no feeds will be updated. I'm using the webcron setting.

(On owncloud 7 news update worked with encryption.)

This is pretty much the only thing holding me back from updating owncloud to 8. Your news app is just awesome and exceptional useful. I would appreciate a fix for the latest stable owncloud 8.0.2.

Best regards
Martin

**Comment by Raydiation** [comment]
Can you post your logs?

**Comment by Raydiation** [comment]
We are not doing anything special, my guess is that the encryption app has some cron code which produces an error which in turn aborts the cron. All in all logs are needed to see what goes wrong :)

You can also use the shipped custom updater (should work) https://github.com/owncloud/news/tree/master/bin/updater

**Comment by efelon** [comment]
I assume you just mean enable highest log level in admin settings and wait for cron to be called?

**Comment by Raydiation** [comment]
Yes, you can call the cron by hand: 

    sudo -u www-data php -f owncloud/cron.php

replace www-data with your webserver user

**Comment by efelon** [comment]
Only when i have encryption enabled i get:
{"reqId":"116981ce9c21dcd8e43eed629c4fcb94","remoteAddr":"x.x.x.x","app":"no app in context","message":"Error while running background job: Could not determine user","level":3,"time":"2015-04-16T07:01:16+00:00","method":"GET","url":"\/ocnew\/cron.php"}

**Comment by Raydiation** [comment]
Ah I see, OK. It's a bug in the encryption app, please file a bug in core. On a side note you can disable the encryption app without loss of security if you don't have your storage on a different server.

**Comment by efelon** [comment]
Thanks for you help. Can't we just move this issue over to core. ;) 
I'm gonna file an issue there.

**Comment by Raydiation** [comment]
BTW: did a quick check: the cronjob does not request the user at all, so this error is really happening somewhere else.
