### ISSUE TITLE
Chromium not showing unread

### ISSUE THREAD

**Issue by drsbaitso** [owncloud/news#771]
In Chromium 44.0.2376.0 (64-bit) the unread or all articles button is missing.

On the left is Chromium and the right is IE 11.

![capture](https://cloud.githubusercontent.com/assets/3653167/7275282/a17ba23a-e8c8-11e4-90d0-f13ba1f1b946.png)

**Comment by Raydiation** [comment]
The starred entry does not have a menu ;)

**Comment by cosenal** [comment]
@Raydiation The OP was asking for something else.

@drsbaitso I cannot reproduce it with chromium 42.0.2311.90-1. Any error in the console? Any special add-on that may hide page elements?

**Comment by Raydiation** [comment]
Ah i See now

**Comment by Raydiation** [comment]
Please provide more details, check the readme

**Comment by drsbaitso** [comment]
Uhhh... It appears that Adblock was somehow blocking the element.  I disabled that and all is fine now...

So, I should have checked that before, but that's totally weird... sorry for the ticket.  I looked in the console and no errors so that's why I posted the ticket.

Closing.
