### ISSUE TITLE
Adding feed: Request timed out

### ISSUE THREAD

**Issue by martynvs** [owncloud/news#772]
Whenever I try adding a feed, it loads and then generates a red box with the text: Request timed out

data/owncloud.log (important!) ![owncloud log](https://cloud.githubusercontent.com/assets/2098719/7332807/99292ec6-eb53-11e4-8268-cab3db47df0e.png)
ownCloud version : 8.0.2
News version : 5.2.8
Browser and version : Firefox 37.0.2 and Chrome 42.0.2311.90 m
PHP version : 5.6.7
Distribution : FreeNAS 9.3 (owncloud plugin) 

![config ini](https://cloud.githubusercontent.com/assets/2098719/7332816/97de4942-eb54-11e4-9d43-d31653b0dc60.png)

**Comment by Raydiation** [comment]
First off remove your invalid config values. Also does this happen for all feeds?

**Comment by martynvs** [comment]
Dear Raydiation, thank you for the quick reply!
Which config values are invalid? How can I tell? I tried restoring the config.ini from scratch several times using the default values in the wiki. Am I missing something?
Yes, this happens for all feeds

**Comment by Raydiation** [comment]
Check https://github.com/owncloud/news#updating-from-versions-prior-to-4

**Comment by martynvs** [comment]
The "simplePieCacheDuration" settings is not listed in my config.ini, see image below:
![config ini](https://cloud.githubusercontent.com/assets/2098719/7332976/97d09538-eb5c-11e4-9962-57b0761090c5.png)

**Comment by Raydiation** [comment]
The last two lines belong into the owncloud/config/config.php not in the news config.ini

**Comment by martynvs** [comment]
Ah ok. I changed it now. Thanks for all your help so far!
The Invalid config error is gone, but the problem with the request timed out still remains. The log file is now as follows:

![owncloud log](https://cloud.githubusercontent.com/assets/2098719/7333787/6f5bb702-eb7c-11e4-9819-5fbd6a073e20.png)

I don't understand what is wrong. Do you?

**Comment by Raydiation** [comment]
Can you check how long curl takes to fetch the feed on your console? We've had questions with similar problems and it was related to the machine having a very slow connection.

    curl http://your-feed.com

**Comment by martynvs** [comment]
It takes more or less 11 seconds (timed 3 times). My internet connection is not that slow, but the setup running my FreeNAS server is quite slow. Could that be the cause?

**Comment by Raydiation** [comment]
OK, that's really slow. Have you tried to increase the timeout in the config? The default is 10 seconds

**Comment by martynvs** [comment]
What timeout do you mean? A timeout of curl? What I find online is that it by default has no timeout? Could you point me in the direction of where to change this?

Or do you mean a timeout of the news app? I set the Feed fetcher timeout to 240 seconds, but that does not seem to impact the Request time out. This does happen after approximately 10 seconds, so I guess this is the cause of the problem.

**Comment by Raydiation** [comment]
I've recently discovered a timeout bug in the feed lib that we are using. I'm not sure if it's in a release yet, you could try master which requires owncloud 8.1 and check if it works there

**Comment by martynvs** [comment]
I updated my ownCloud 8.0.2 to 8.1 Alpha2 and updated my News app to 5.3.1 and now it works! Thank you very much for your help!

**Comment by Raydiation** [comment]
Awesome :) 

Will add that to the changelog then :)
