### ISSUE TITLE
Hide second setting

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/news#774]
The second setting should only be visible, if the first setting is checked. otherwise it does not make sense since it does not have any effect.

CC @owncloud/designers 

![second](https://cloud.githubusercontent.com/assets/4741199/7358395/5812cdaa-ed35-11e4-96c8-2a5d00da779b.png)

**Comment by Raydiation** [comment]
:+1:  makes it more readable

**Comment by stefan-niedermann** [comment]
Maybe even the text can be shorten. if the second setting only appears if the first is ticket, it should be clear, that it references to the first, shouldn't it? something like "expand on key navigation"? (in german "Artikel bei Tastatur-Navigation erweitern")

**Comment by stefan-niedermann** [comment]
other thought: maybe the user interface jitters if options are removed and added dynamically ( @jancborchardt ?). in this case the second option should at least be disabled (grey and not checkable).
(sorry for spamming ;) )

**Comment by jancborchardt** [comment]
Yeah, I would also rather say it should be disabled instead of being invisible.

**Comment by jancborchardt** [comment]
And yes, shorter text would be good.
