### ISSUE TITLE
Hide "Mark all as Read" if there are no unread articles

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/news#775]
If there are no unread articles left, the three-dots-menu with the "Mark all as Read"-Button should be hidden because it's useless.

CC @owncloud/designers 

![mark all as read](https://cloud.githubusercontent.com/assets/4741199/7358432/84f6fb84-ed35-11e4-8eb0-61fc9f72a9e9.png)

**Comment by Raydiation** [comment]
Good idea

**Comment by jancborchardt** [comment]
Hehe, good catch. That actually looks funnily stupid. ;)
