### ISSUE TITLE
News not updating whole day today

### ISSUE THREAD

**Issue by zkvvoob** [owncloud/news#778]
Hello,

Up until yesterday the News app had been functioning normally. Today no new articles were pulled, even though, according to OwnCloud's Admin page, the Cron service is executed regularly, the last time being 6 minutes ago.

I've checked all accounts and the Android owncloud News app - the results are the same.

I'm not sure whether this is a bug, whether it's related to the app itself, but I'd be very grateful if you could point me where to look for a possible cause.

Thank you!

**Comment by Raydiation** [comment]
https://github.com/owncloud/news#before-reporting-bugs
https://github.com/owncloud/news#feeds-are-not-updated

**Comment by zkvvoob** [comment]
OK, apologies for the scarcity of information. Here are the owncloud.log entries from the last couple of days: http://pastebin.com/zx4PH4UY
- the cronjob hasn't been changed ever since OC was installed months ago; it's managed through ISPConfig (a cPanel-like console), so I assume it's being run with the necessary credentials;
- owncloud/cron.php is owned by the web user;
- I couldn't place **error_log('updating')** because the file task.php does not exist at the specified location (https://github.com/owncloud/news/blob/master/backgroundjob/task.php#L37);
- owncloud's config.php has **"loglevel" => 0**, the results are in the pastebin above.

* ownCloud version 8.0.2
* News 5.2.8
* Browser: Chrome 42.0.2311.90 m (64-bit)
* PHP 5.5.9
* Distribution: Ubuntu 14.04.2

What else would you need to help me?

**Comment by zkvvoob** [comment]
Update: I tried News' custom updater script and it works! Which is great! 

However, I'm not that python-savvy and I don't understand - do I need to run `python3 -m owncloud_news_updater -c /path/to/config.ini` once and that's all, the updater will run at a predefined interval? Or do I need to install it somehow, I didn't quite understand the two methods - init system and systemd. Which of the two would be appropriate for my situation?

Thank you!

**Comment by Raydiation** [comment]
Disable the search lucene app, its throwing errors

**Comment by Raydiation** [comment]
Which is likely stopping the update

**Comment by zkvvoob** [comment]
Done, search lucene is disabled. Now perhaps I should check back **Use ownCloud cron**? In the meantime, should I cancel the updater-script? I left it in terminal...

**Comment by Raydiation** [comment]
yes just to check if it works ;)

**Comment by zkvvoob** [comment]
I don't think it does. Even with Search Lucene off, it's been an hour already and no news have appeared.

So, could you tell me how to install the custom script so that it starts running on its own (even after restarting the server)? 

Thanks!

**Comment by Raydiation** [comment]
Can you clear your log and run sudo -u www-data php -f owncloud/cron.php to check if new errors appear in the log?

For more information on the updater see https://github.com/owncloud/news/tree/master/bin/updater#installation-no-init-system

**Comment by zkvvoob** [comment]
Cleared the log, ran the command you requested but nothing appeared - just another clean command prompt.

Now, I also followed the instructions to install the updater script without init system and it went fine I think, but 15 minutes later the news feeds are still empty.

When I ran the script manually this morning, it pulled quite a lot of news articles.

terminal log: http://pastebin.com/uFvfrh2a

**Comment by Raydiation** [comment]
your log?

**Comment by Raydiation** [comment]
It's supposed to be kept occupied, you can leave it open in a screen session for instance. Or use systemd to run it in the background.

**Comment by zkvvoob** [comment]
Apologies for the oversight, here's owncloud.log > http://pastebin.com/KnnCn2ky

On another matter, it appears that Ubuntu 14.04 does not have SystemD - it uses something called Upstart. Is there a way to run the News updater script this way? 

Thanks for all your help!

**Comment by Raydiation** [comment]
Yes, but you'd need to write your own upstart script, see http://upstart.ubuntu.com/cookbook/ 

The newest ubuntu release has systemd btw. Nothing really unusual from the logs btw.

BTW: one last thing: try to delete data/cron.lock, totally forgot about that issue, fixed in 8.1

**Comment by zkvvoob** [comment]
Thanks for the pointers, but I don't feel proficient enough to write a script on my own, so that's out as an option.

I would rather try to figure out why the regular cron stopped doing its job.

There's no cron.lock file in OC's data folder.

**Comment by Raydiation** [comment]
The script should not be run as cron because you'll get into deadlock issues. Run it like it's documented, use a separate screen session or write an init script to do that.

**Comment by zkvvoob** [comment]
It seems to be working now. I upgraded to OC 8.0.3 and changed the way cron.php was executed, so no need to use the built-in updater.

By the way, I did run it like a cron-job for a couple of days - every hour or so, and it worked fine without getting into deadlock issues.

Anyway, thanks for your help, @Raydiation !
