### ISSUE TITLE
Ajax cron mode detected error

### ISSUE THREAD

**Issue by colmoneill** [owncloud/news#779]
I'm glad ownCloud warns me about this kind of stuff, but does it have to look this way?

![screenshot from 2015-05-01 23 05 51](https://cloud.githubusercontent.com/assets/2122318/7438747/bdb1a834-f069-11e4-8a6f-a2cde2101c30.png)

Could there be a way of making this warning a little more integrated with the rest of the interface?

**Comment by Raydiation** [comment]
? Imho it's integrated, uses the same colors etc. Provide mockups please if you can do it better

**Comment by jancborchardt** [comment]
No, it’s not integrated. It’s a giant yellow ugly technical notification which is slapped into my face the first time (and _every time_) I want to use the news app. It should not be permanent like that, and not take like 25% of viewing space.

Just use the normal notification API to show a small notification up top in the header. But not a giant blocking abomination like this.

**Comment by jancborchardt** [comment]
@Raydiation good on using the default system notification! :)

**Comment by colmoneill** [comment]
Looking good! Thanks for this! :)
