### ISSUE TITLE
Feed ordering setting for each feed?

### ISSUE THREAD

**Issue by colmoneill** [owncloud/news#780]
Is this not more of a general app setting, rather than a toggle for touch menus?

![screenshot from 2015-05-02 01 24 05](https://cloud.githubusercontent.com/assets/2122318/7438801/c7638a2c-f06a-11e4-8bb2-84599b0484ea.png)

Also, do these menu items need labels @jancborchardt not sure what the best strategy would be here.

**Comment by jancborchardt** [comment]
Yeah, I agree. It’s a bit too granular and should probably only be a global setting. @Raydiation @cosenal

**Comment by Raydiation** [comment]
Has it's use case. It's there to override ordering settings which are also available in the global settings menu. For instance you've got comic feeds which you want to order oldest first and news feeds where newest first is the desired setting.

**Comment by Raydiation** [comment]
https://github.com/owncloud/news/issues/711
