### ISSUE TITLE
Ohh please, you did not just locked a discussion that you don't like, Kim Jong-un?

### ISSUE THREAD

**Issue by clementhk** [owncloud/news#782]
https://github.com/owncloud/news/issues/781#issuecomment-98341892

It's a valid on going discussion and when I'm gathering info you just locked it, is that really how grown up you are??
What I was trying to write was the implementation clearly looks wrong from what you described, pull to refresh should not be able to get triggered by scrolling, but by "dragging", as it should not be a part of the webpage, but be triggered by actions, for example like this one http://apeatling.com/demos/web-ptr/ .

**Comment by Raydiation** [comment]
Read the rest of the issue. It's not pull to refresh. Please open a new issue with a proper suggestion

**Comment by jancborchardt** [comment]
@clementhk see my comment at https://github.com/owncloud/news/issues/781#issuecomment-98352862

One problem though with the exampe you linked is that dragging is not discoverable at all. It needs to work via scrolling, but maybe only _after_ you scrolled to the top and scroll again. It’s a tough nut to crack on desktop and I can understand why @Raydiation is annoyed about it.

@clementhk let’s maybe try to find a good implementation and experiment with it in ownCloud Mail. Then we might be wiser.
