### ISSUE TITLE
Receiving a notification to add ownCloud News as a Feed Reader in Firefox

### ISSUE THREAD

**Issue by zirydy** [owncloud/news#783]
### Steps to reproduce
1. Open Firefox
2. Check and turn on the following settings in Preferences: ```Privacy > Clear history when Firefox closes``` and ```Privacy > Clear history when Firefox closes > Settings > Cookies``` (One needs to have ```Use custom settings for history``` turned on)
3. Log into ownCloud and load the News App
4. One is prompted with the notification: ```"Add "ownCloud News @ https://xyz.com/owncloud" as a Feed Reader?"```
5. Click on ```Add Feed Reader```
6. Close Firefox and load the News App again
7. One is then prompted with the notification (which doesn't go away): ```"ownCloud News @ https://xyz.com/owncloud" is already registered as a Feed Reader```

### Expected behaviour
I don't expect to receive any more notifications once I click on "Add Feed Reader" (Step 5)

### Actual behaviour
One receives the message ```"ownCloud News @ https://xyz.com/owncloud" is already registered as a Feed Reader```

### Server configuration
**Database:** MySQL

**PHP version:** 5.4.40

**ownCloud version:** 8.0.3

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:** News

### Original Message ###

Hi, I just wanted to report that I get the following notification every time I open the News App in Firefox: "Add "ownCloud News @ https://abc.com/owncloud..." as a Feed Reader?"

Moreover, when I click on "Add Feed Reader", I then get a different notification every time instead which is this: "ownCloud News is already registered as a Feed Reader".

Is this a normal behavior? Is there a way to get rid of these messages? I find them quite annoying, not to mention they are taking up my screen space.

I'm currently running ownCloud 8.0.3 with News App 5.2.8 on a hosted webserver. My own computer is running Ubuntu 14.10 and Firefox 37.0.2.

**Comment by cosenal** [comment]
Thanks for filing the issue.

The function , so we use localStorage to understand if the reader is already registered or not. It's possible that in your case, the 

Fyi, this is implemented here: https://github.com/owncloud/news/blob/master/js/gui/ExternSubscription.js

I suggest you try the following things:
- open the webconsole, type `window.localStorage' and check if there is a setting `registeredHandler';
- open a new tab on Firefox, type `about:config' in the url, filter for fields with the name `browser.contentHandlers.types.*' and look for the one where ownCloud News is registered and reset them;
- try to reproduce the problem with Firefox Dev edition https://www.mozilla.org/en-US/firefox/developer/

Let us know what you find out.

**Comment by zirydy** [comment]
@cosenal 
Thank you very much for your detailed comment.

I've tried the above steps but didn't get very far, unfortunately. I'm not a developer in any way so I'm not even sure if I've followed them in the right way, but I'll report you the result:

* I couldn't find ```window.localStorage``` nor ```registeredHandler``` in the Firefox Web Console. (I'm guessing it's the thing that appears when one presses ```F12``` by default?) - I've attached some of  the messages below
* When I reset the ```browser.contentHandlers.types.6.type```, I will see the first notification ("Add ... as a Feed Reader?") all over again.
* This issue didn't occur when I tried it with Firefox Developer Edition.

I've tried resetting some values in ```about:config``` but I can't seem to be able to solve this issue. The strange thing is that the exact same thing happens when I use another Firefox profile, which is nearly completely fresh. So while it doesn't occur under Firefox Developer Edition, it does seem to be Firefox related (and is not specific to, say, my Firefox profile or an addon).

Below are the messages I found in the Web Console:

```
Using @ to indicate sourceMappingURL pragmas is deprecated. Use # instead jquery.min.js:1:0
Using @ to indicate sourceMappingURL pragmas is deprecated. Use # instead jquery-migrate.min.js:3:0
window.controllers is deprecated. Do not use it for UA detection. ace.js:1716:0
Content Security Policy: The page's settings blocked the loading of a resource at self (***************) news
mutating the Prototype of an object will cause your code to run very slowly; instead create the object with the correct initial Prototype value using Object.create

<source> element has no "src" attribute. Media resource load failed. news
All candidate resources failed to load. Media load paused. news
<source> element has no "src" attribute. Media resource load failed. news
All candidate resources failed to load. Media load paused.

Loading mixed (insecure) display content "(***************)" on a secure page[Learn More] jquery.min.js:5:0
Loading mixed (insecure) display content "(***************)" on a secure page[Learn More] jquery.min.js:5:0
Loading mixed (insecure) display content "(***************)" on a secure page[Learn More] jquery.min.js:5:0
<source> element has no "src" attribute. Media resource load failed. news
All candidate resources failed to load. Media load paused. news
<source> element has no "src" attribute. Media resource load failed. news
All candidate resources failed to load. Media load paused.
```

**Comment by cosenal** [comment]
Hi again!
Yes, the web-console is the one you open with F12.
At the very bottom you find a prompt where you can enter commands.
With the tab of ownCloud News open, try to type `window.localStorage` and see what you get. Let me know if you see a field that is called `registeredHandler` there.

**Comment by zirydy** [comment]
@cosenal 
Ah, now I see how it works. I got the following message:
```Storage { registeredHandler: "https://domain.com/…", length: 1 }```
Hope that helps! Thanks again.

**Comment by cosenal** [comment]
And that url points to the same location where News is installed, right?
Can you please do `window.localStorage.clear()` in the same console and then refresh?

**Comment by zirydy** [comment]
Yeah, the URL is the location where my ownCloud is installed.

I just run the command and the same output (```Storage { registeredHandler: "https://ssl.webpack.de/phi.web-repu…", length: 1 }```) is displayed when I refresh the page.

(Prior to refreshing, I get the output ```Storage { length: 0 }```)

**Comment by cosenal** [comment]
OK, then localStorage seems to be working fine. Is the issue still there?

**Comment by zirydy** [comment]
Yeah, I'm still having this issue. When I click on "Add Feed Reader" in the notification, close the browser, and come back to the News page, I now get a different message ""ownCloud News @ https://domain.com" is already registered as a Feed Reader". And like the first notification, it appears every time I open the page.

**Comment by cosenal** [comment]
Sorry, I can't reproduce your issue with exactly your same setup+same browser.
I give up, don't know what else you can try. @Raydiation any ideas?

**Comment by zirydy** [comment]
@cosenal 
You're right. I just tried it with a brand new profile and this actually didn't happen.

Somehow this issue is unique to the two profiles I have set up. Trying to find out what may be causing this.

**Comment by zirydy** [comment]
@cosenal 
I found out the cause. It has to do with the cookies. I seem to get the message ```"ownCloud News @ https://domain.com" is already registered as a Feed Reade``` when the setting ```Privacy > Clear history when Firefox closes > Settings > Cookies``` is enabled in Firefox preferences. But the OC News App shouldn't be dependent on having cookies in the browser...?

**Comment by Raydiation** [comment]
It's not related to cookies, it's most likely Firefox also clearing your local storage when it clears cookies. Use a different setting where you white list cookie domains instead of clearing everything every time again

**Comment by cosenal** [comment]
@zirydy I am glad you found the fix. For more about cookie-localstorage relationship in firefox, I found this interesting reference: http://superuser.com/a/771799/418712
