### ISSUE TITLE
News not working: searchIndex is not a valid attribute

### ISSUE THREAD

**Issue by DavidEGx** [owncloud/news#784]
Hi,

This is more a [pebcak](http://www.urbandictionary.com/define.php?term=PEBCAK) than a defect and maybe this is not the right place to ask... but hopefully someone will help me to get my news back :-)

So this is how I fucked it up:
1. Upgrade debian: apt-get update && apt-get dist-upgrade
2. Open firefox and go to my owncloud, everything was ok except news was disabled.
3. So maybe was time to update it, $ cd app/news $ git pull
4. Back to firefox, now telling me that is disabled because requires 8.1... so what could possible go wrong if I edit a file and change 8.1 for 8.0?
(Don't blame me, it works sometimes :D)
5. In firefox again, now I can enable new \o/, but my owncloud is totally broken after that :'(
6. Disable news, undo my naive changes, git checkout 5.2.8, enable.
7. Again in firefox, news is back! I can see my feeds, but when I click any of them I get:

    {"reqId":"95eb5abb8a558474e43ad13e030aacef","remoteAddr":"XX.XX.XX.XX","app":"index","message":"Exception: {\"Message\":\"searchIndex is not a valid attribute\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(134): OCP\\\\AppFramework\\\\Db\\\\Entity->setter('searchIndex', Array)\\n#1 \\\/home\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(67): OCP\\\\AppFramework\\\\Db\\\\Entity->__call('setSearchIndex', Array)\\n#2 \\\/home\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(67): OCA\\\\News\\\\Db\\\\Item->setSearchIndex(NULL)\\n#3 [internal function]: OCP\\\\AppFramework\\\\Db\\\\Entity::fromRow(Array)\\n#4 \\\/home\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(253): call_user_func('\\\\\\\\OCA\\\\\\\\News\\\\\\\\Db\\\\\\\\It...', Array)\\n#5 \\\/home\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(271): OCP\\\\AppFramework\\\\Db\\\\Mapper->mapRowToEntity(Array)\\n#6 \\\/home\\\/www\\\/owncloud\\\/apps\\\/news\\\/db\\\/itemmapper.php(178): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntities('SELECT `items`....', Array, 40)\\n#7 \\\/home\\\/www\\\/owncloud\\\/apps\\\/news\\\/db\\\/itemmapper.php(195): OCA\\\\News\\\\Db\\\\ItemMapper->findEntitiesIgnoringNegativeLimit('SELECT `items`....', Array, 40)\\n#8 \\\/home\\\/www\\\/owncloud\\\/apps\\\/news\\\/service\\\/itemservice.php(93): OCA\\\\News\\\\Db\\\\ItemMapper->findAllFeed(97, 40, 0, 0, false, 'david')\\n#9 \\\/home\\\/www\\\/owncloud\\\/apps\\\/news\\\/controller\\\/itemcontroller.php(101): OCA\\\\News\\\\Service\\\\ItemService->findAll(97, 0, 40, 0, true, false, 'david')\\n#10 [internal function]: OCA\\\\News\\\\Controller\\\\ItemController->index(0, 97, 40, 0, true, false)\\n#11 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(158): call_user_func_array(Array, Array)\\n#12 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(86): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\News\\\\Controller\\\\ItemController), 'index')\\n#13 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(97): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\News\\\\Controller\\\\ItemController), 'index')\\n#14 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(44): OC\\\\AppFramework\\\\App::main('ItemController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#15 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#16 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#17 \\\/home\\\/www\\\/owncloud\\\/lib\\\/base.php(782): OC\\\\Route\\\\Router->match('\\\/apps\\\/news\\\/item...')\\n#18 \\\/home\\\/www\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#19 {main}\",\"File\":\"\\\/home\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php\",\"Line\":107}","level":4,"time":"2015-05-05T15:54:51+00:00"}

**Comment by Raydiation** [comment]
Remove the database column that should fix it

**Comment by Raydiation** [comment]
oc_news_items searchindex

**Comment by Raydiation** [comment]
Kinda interesting why it migrated the tables i even if 8.1 is required. Probably bug in core?

**Comment by Raydiation** [comment]
@DeepDiver1975 @PVince81

**Comment by DavidEGx** [comment]
Thanks! That worked \o/

I guess it upgraded the tables because in 4 I edited appinfo/info.xml and put 8.0 instead of 8.1.

**Comment by Raydiation** [comment]
Ah right :)
