### ISSUE TITLE
News app does not update news feed

### ISSUE THREAD

**Issue by openmatl** [owncloud/news#785]
Since a short time period I have sometimes problems while updating my news feed. I am using the newest ownCloud Version 8.0.3.
The news app is not able to update the newsfeed, because of that I can not download new newsmessages. The last time the problem solves by its own, but now I have the same issue again.

The ownCloud Log shows this fatal error message:

`Fatal 	index 	Exception: {"Message":"Session has been closed - no further changes to the session as allowed","Code":0,"Trace":"#0 \/usr\/share\/webapps\/owncloud\/lib\/private\/session\/internal.php(36): OC\\Session\\Internal->validateSession()\n#1 \/usr\/share\/webapps\/owncloud\/lib\/private\/util.php(982): OC\\Session\\Internal->set('requesttoken', 'WGshrLYBkT6Kcme...')\n#2 \/usr\/share\/webapps\/owncloud\/lib\/public\/util.php(373): OC_Util::callRegister()\n#3 \/usr\/share\/webapps\/owncloud\/lib\/private\/appframework\/middleware\/security\/securitymiddleware.php(116): OCP\\Util::callRegister()\n#4 \/usr\/share\/webapps\/owncloud\/lib\/private\/appframework\/middleware\/middlewaredispatcher.php(90): OC\\AppFramework\\Middleware\\Security\\SecurityMiddleware->beforeController(Object(OCA\\Contacts\\Controller\\PageController), 'index')\n#5 \/usr\/share\/webapps\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(85): OC\\AppFramework\\Middleware\\MiddlewareDispatcher->beforeController(Object(OCA\\Contacts\\Controller\\PageController), 'index')\n#6 \/usr\/share\/webapps\/owncloud\/lib\/private\/appframework\/app.php(97): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Contacts\\Controller\\PageController), 'index')\n#7 \/usr\/share\/webapps\/owncloud\/lib\/public\/appframework\/app.php(125): OC\\AppFramework\\App::main('PageController', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer))\n#8 \/usr\/share\/webapps\/owncloud\/apps\/contacts\/appinfo\/routes.php(20): OCP\\AppFramework\\App->dispatch('PageController', 'index')\n#9 [internal function]: OC\\Route\\Router->OCA\\Contacts\\{closure}(Array)\n#10 \/usr\/share\/webapps\/owncloud\/lib\/private\/route\/router.php(250): call_user_func(Object(Closure), Array)\n#11 \/usr\/share\/webapps\/owncloud\/lib\/base.php(782): OC\\Route\\Router->match('\/apps\/contacts\/')\n#12 \/usr\/share\/webapps\/owncloud\/index.php(36): OC::handleRequest()\n#13 {main}","File":"\/usr\/share\/webapps\/owncloud\/lib\/private\/session\/internal.php","Line":87}`

**Comment by Raydiation** [comment]
Can you disable the contacts app and check if it works

**Comment by Raydiation** [comment]
Also please delete data/cron.lock

**Comment by openmatl** [comment]
Deactivating the contacts app does not help to solve the problem. Where can I finde data/cron.lock? It does not exist in the owncloud directory and also not in the system directory.

**Comment by Raydiation** [comment]
Yes owncloud/data/cron.lock

Can you go through

https://github.com/owncloud/news/blob/master/README.md#feeds-are-not-updatedttps://github.com/owncloud/news/blob/master/README.md#feeds-are-not-updated

**Comment by openmatl** [comment]
Ah the cron.lock was the issue. Now after long long time my system cron is working again :+1: 
Thank you so much.

**Comment by Raydiation** [comment]
Cron lock problem is fixed in 8.1 btw
