### ISSUE TITLE
Navigation shortcuts skip first item

### ISSUE THREAD

**Issue by tgrosinger** [owncloud/news#786]
I have compact view enabled, expand articles when navigating, and disable mark read through scrolling. When I first press `r` to refresh the feed, then press `j` to expand the first item it will instead expand the second item. I then have to push `k` to go back one and continue from there. 

**ownCloud version**: 8.02
**News version**: 168040
**Browser and version**: Firefox 37.0.1
**PHP version**: 

```
$ php --version
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

**Distribution**:

```
$ lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
```

**Comment by Raydiation** [comment]
Where did you get the app version? Or is this a git tag?

**Comment by cosenal** [comment]
@Raydiation I can reproduce it with News 5.2.8 on core 8.0.3

**Comment by tgrosinger** [comment]
@Raydiation this is the version that prefaces the download from http://apps.owncloud.com

**Comment by cosenal** [comment]
@tgrosinger that's a content id, it has nothing to do with the version :)

**Comment by tgrosinger** [comment]
@cosenal Haha good to know. Thank you
