### ISSUE TITLE
Videos are not stopped when going to next article

### ISSUE THREAD

**Issue by tgrosinger** [owncloud/news#787]
When browsing through items, if you start a video (like an embedded YouTube video) then go to the next article the video will continue playing but no longer be on screen.

I had the expectation that article would be collapsed again after pushing `j`. That is not the case, but it might be nice if there was a way to automatically pause popular content such as YouTube and Vimeo videos or SoundCloud audio that is embedded.

**ownCloud version**: 8.02
**News version**: 5.2.8
**Browser and version**: Firefox 37.0.1
**PHP version**: 

```
$ php --version
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

**Distribution**:

```
$ lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
```

**Comment by Raydiation** [comment]
It works for HTML audio and Video, in unsure if we can do the same for iframes

**Comment by Raydiation** [comment]
Ah right not when you collapse stuff in compact mode. Using ngif instead of ngshow should work

**Comment by Raydiation** [comment]
BTW this will only work iframe videos if you collapse the previous article. Which is not done automatically if you are using keyboard shortcuts because it will cause the page to scroll up and possibly mark articles as read.
