### ISSUE TITLE
Navigating from bottom to top with keyboard shortcuts is not possible

### ISSUE THREAD

**Issue by tgrosinger** [owncloud/news#788]
### Reproduction Steps

1. Check "compact view" and "expand articles..."
2. Click "Unread Articles" when you have multiple articles to read
3. Click an article that is not the top-most article
4. Press `k` (or `p` or left) to go to previous article

### Expected Results

Previous article will be shown

### Actual Results

"Refresh (r)" button shows up at top of page. Pressing `k` again will cause the list to refresh. Previous article is never focused.

### Details

**ownCloud version**: 8.02
**News version**: 5.2.8
**Browser and version**: Firefox 37.0.1
**PHP version**: 

```
$ php --version
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

**Distribution**:

```
$ lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
```

**Comment by tgrosinger** [comment]
Interestingly it looks like if you start at an item (even one other than the first one) and go down a couple articles then press `k` you will be able to go back up. Just pressing `j` then `k` does not work however because of #786.

**Comment by Raydiation** [comment]
Intended behavior. First of all the shortcut does not work on focused articles, it checks the scroll position meaning that if you are already on top and you want to go back it won't work because there's nothing to scroll.
