### ISSUE TITLE
Owncloud 8.1 Required

### ISSUE THREAD

**Issue by tgrosinger** [owncloud/news#789]
I apologize for creating an issue for this as I don't think it really deserves one, but I don't have another point of contact for questions.

I have just updated OwnCloud to 8.0.3 (latest on the downloads page) and have checked out `tags/5.3.3` on the ownlcloud/news repo. Unfortunately I am now seeing this:

>News 5.3.3
>by Bernhard Posselt, Alessandro Cosentino, Jan-Christoph Borchardt (AGPL-licensed)
>
>An RSS/Atom feed reader
>
>Documentation: User Documentation Admin Documentation
>
>This app cannot be installed because the following dependencies are not fulfilled:
>
>    ownCloud 8.1 or higher is required.

Am I supposed to install the 8.1.0beta1 release? Unfortunately it doesn't seem like going down to `tags/5.3.2` let's me activate it again either.

Thank you

**Comment by Raydiation** [comment]
5.3.x requires 8.1 

It is supposed to get some testing going on until the stable version is released. You can still find older released on the releases page

**Comment by tgrosinger** [comment]
Ah, I was probably on 5.2.8 previously. Thank you.

**Comment by Raydiation** [comment]
Btw  I'll keep this open in case anyone else has the same question

**Comment by viki53** [comment]
Hi, not sure it's the same question as I installed 8.1 this morning (fresh install) and get the same error message (just downloaded the 5.3.4 release).

Maybe this would be better in a separate issue…(?)

**Comment by Raydiation** [comment]
@viki53 which 8.1? should run fine on the latest beta (thats what I use)

**Comment by viki53** [comment]
That's weird. I checked the `status.php` page (that I just discovered) and it says `"version": "8.0.3.4"` but the *Help* section says `ownCloud 8.1 User Manual`.

**Comment by Raydiation** [comment]
Perhaps not fully done upgrade?

**Comment by viki53** [comment]
I installed ownCloud form scratch this morning (12 hours ago), so I doubt there's been a problem on this end.

Looks like [the `apt-get` repo](http://software.opensuse.org/download/package?project=isv:ownCloud:community&package=owncloud) isn't up-to-date.

**Comment by davodego** [comment]
I installed owncloud 8.0.4 yesterday.
News App 5.3.6 is installed but says 
    ownCloud 8.1 or higher is required.
??? what can I do to install the App?

**Comment by Raydiation** [comment]
Read the readme and check the releases page like already stated in the issue
