### ISSUE TITLE
Mixing keyboard shortcuts and mouse has unexpected results

### ISSUE THREAD

**Issue by tgrosinger** [owncloud/news#791]
This one might be a little more complicated than just what I am going to describe here. This is just the easiest way to repo I think.

1. In the Unread Articles section with more than 2 unread
2. Click on an article other than the first one
3. Click on another article other than the first one
4. Press a hotkey (for example `o` is a good one here)
5. New page opens for an article other than the one you most recently opened.

Hopefully that explanation makes sense. Let me know if I can provide more information.

**ownCloud version**: 8.0.3
**News version**: 5.2.8
**Browser and version**: Firefox 37.0.1
**PHP version**: 

```
$ php --version
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

**Distribution**:

```
$ lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
```

**Comment by cosenal** [comment]
Actually 'o' is supposed to act on the article that is at the top of the screen, no matter what is open.

**Comment by tgrosinger** [comment]
Hmm, that seems unintuitive. If I am going through the articles but there are not enough to fill the screen then that hotkey wouldn't be able to help me. I think having it act on the most recently "touched" article would be more intuitive, just based on the other RSS readers I've used.

**Comment by Raydiation** [comment]
We'd have to mark an article as active with a colored border like we did in the beginning to highlight the currently active article.

There are numerous hard to define behaviors then:
* When scrolling, does the active article change? If so, when does it change
* If I click on an article and scroll, what will happen?
* If the active article is not at the top, where will the "jump to next article" shortcut jump to? Where will the previous article shortcut jump to?
* Is there a way to deselect the currently active article? e.g. I expand the third article which is now active but I want to continue from the first article in the list.

@jancborchardt

**Comment by tgrosinger** [comment]
One idea that would make this simpler is to keeps scrolling unrelated to article selection. This means I could scroll the active article off the page. `j` should move the active article to the one below, and `k` to the one above. This does leave an unanswered question of what happens if you do not have the "disable mark read through scrolling" checked.

Currently it is very confusing when I select an article other than the first one and want to go to the next article. The keyboard shortcuts become completely useless since the one I clicked is often not at the top of the page.

**Comment by Raydiation** [comment]
Another issue that comes to my mind: I often just scroll down using page down and then start from the interesting article with the arrow right shortcut. If we implemented this behavior pure keyboard navigation would be impacted.

**Comment by tgrosinger** [comment]
So through a little trial and error I have determined that I can scroll the page up even if the article list is short, allowing me to put the article I want to start reading at at the top.

I think this is a fine solution to the problem, it's just a little invisible how the keyboard shortcuts are actually working. It doesn't say anywhere that they operate on the article at the top of the page.

**Comment by tgrosinger** [comment]
Another possible solution is making the click to expand an article automatically bring that article to the top of the page.

**Comment by Raydiation** [comment]
Would be bad if mark read on scroll is activated and does not work for the expanded view :)

**Comment by tgrosinger** [comment]
Haha okay. Well this is turning into a surprisingly complicated issue.
I'm just trying to make it so if I click on an article then press `o` it doesn't open a different article. It's surprised me a number of times.

**Comment by Raydiation** [comment]
IMHO it has to work in the following way:
* If a new feed is loaded, the first entry is selected
* Clicking on any entry selects that entry
* Scrolling selects the topmost visible entry

That way you can avoid pretty much every issue. We'd have to visually mark an article as selected though to avoid confusion, maybe an ownCloud blue or orange which works with the ownCloud blue (like we used to do back in the early days)

**Comment by Raydiation** [comment]
What do you think @cosenal @tgrosinger ?

**Comment by Raydiation** [comment]
The article that you jump to would ofc be moved to the very top.

**Comment by tgrosinger** [comment]
What would happen then if you have mark read on scroll enabled? Would the jump mark all those articles between the top and the one you clicked as read, or skip them during the jump?

**Comment by Raydiation** [comment]
You select article 8, press next to jump to 9 and 1 to 8 will be marked read
