### ISSUE TITLE
Libxml version

### ISSUE THREAD

**Issue by wood29** [owncloud/news#792]
I am trying to activate the news app in owncloud 8.0.3 on Qnap, however get the message libxml higher than 2.7.8 is req. - available 2.6.3.  However I have libxml2 2.7.8-1 installed.  Can someone help to fix this issue?  Is the app pointed at a old installed version?  how would I get rid of it?
thanks

**Comment by Raydiation** [comment]
It depends on what libxml version was compiled with PHP, so while you may have the newest libxml version installed, your php could still use the oldest one. Use your favorite search engine to learn how to upgrade libxml on php on your device

**Comment by Raydiation** [comment]
Also please seek support in a PHP forum, stackoverflow etc. since this is a PHP issue and has nothing to do with the News app
