### ISSUE TITLE
Link to 'How to set up the operating system cron' outdated?

### ISSUE THREAD

**Issue by colmoneill** [owncloud/news#793]
This notification suggest info on How to set up the operating system cron, but the link behind it https://doc.owncloud.org/server/8.0/admin_manual/configuration/background_jobs_configuration.html#cron is not responding.

![screenshot from 2015-05-15 13 17 23](https://cloud.githubusercontent.com/assets/2122318/7651795/c46ac516-fb04-11e4-8ae9-e4205a98ca7e.png)

Is this actually a News app problem? I don't know how the doc.owncloud.org is maintained?

**Comment by colmoneill** [comment]
thx!

**Comment by cosenal** [comment]
@colmoneill thank you for catching this
