### ISSUE TITLE
Show a button to fix broken feeds

### ISSUE THREAD

**Issue by oparoz** [owncloud/news#794]
Apparently, it's inevitable to have some broken feeds when importing sites using OPML.

The problem is that besides the error message and the cross to get rid of it, there is nothing one can do to fix the problem.

I think there should be a way to edit the feed and do a refresh, just in case it was simply a problem with the importer or to give the user a chance to update the URL.

**Comment by Raydiation** [comment]
Dup of #71 which covers the same usecase
