### ISSUE TITLE
Catch core exceptions and fail gracefully

### ISSUE THREAD

**Issue by oparoz** [owncloud/news#797]
### Env
8.0, 5.2.8

### Steps to reproduce
1. Open a feed (`index.php/apps/news/#/items/feeds/69`)
2. Wait until the session times out or kill the session manually
3. Refresh the page

### Expected result
The user should be redirected to the login page

### Actual result
The user gets an error 500 with a very long trace

### Logs

```
Code: 10
Message: Could not determine user
File: /apps/files_encryption/lib/helper.php
Line: 306
```

**Comment by Raydiation** [comment]
Can not reproduce

**Comment by Raydiation** [comment]
Also very likely a core issue.

**Comment by Raydiation** [comment]
The log is from the encryption app btw which is not supported due to various bugs in the app itself

**Comment by oparoz** [comment]
Yes, it's from the encryption app, but my point is that the user should never be presented with an error screen meant for admins.

See this answer:
https://github.com/owncloud/core/issues/16372#issuecomment-102862066

Apps are responsible to handle exceptions so that users are not left stranded.

**Comment by Raydiation** [comment]
Apps are not responsible to handle every exception thrown from a random app. This is called swallowing exceptions is bad practice. Also you won't get an error page unless you are running with display errors on which is not recommended for production.

Also redirecting to the login page will create redirect loops for any error which is way more horrible than just failing.

**Comment by oparoz** [comment]
I agree that redirecting might be a problem in case of something severe...
But regarding exception swallowing, I think an app can still log the exception while dealing with it internally in order to not break by displaying an error message per example.

**Comment by Raydiation** [comment]
The exception is logged by core. Dealing with the exception internally is not possible because you don't know what kind of exception it is. 

In this case it is a bug in the encryption app where a simple redirect could help, but what about other cases where we don't know the solution? Just ignoring the exception can cause problems such as data corruption. 

For instance think of the following case: you are trying to read data from a file to update database tables. An unknown exception is thrown by the encryption app (due to a bug), we just ignore the exception. The variable which holds the content is not set and the database tables are updated with null values.

PS: Turn off debug mode so you wont see a trace.

**Comment by Raydiation** [comment]
The obvious solution to this very problem is of course to file a bug in the encryption app bug tracker ;)

**Comment by oparoz** [comment]
It's true that catching exceptions only really works for specific methods, where you can easily discard the answer you get back and notify the user.
In this case, it was the PageController which couldn't do anything because it didn't know which user was making the request. It's more like a general failure and harder to deal with.

**Comment by Raydiation** [comment]
Actually I think it happens outside of the controller when the encryption app is initialized. Just a guess though

**Comment by oparoz** [comment]
```
{
"Message":"Could not determine user",
"Code":10,
"Trace":"#0 appsfiles_encryptionlibhelper.php(283): OCA\Files_Encryption\Helper::getUserFromPath('newsconfigco...')\\n#1 appsfiles_encryptionlibproxy.php(327): OCA\Files_Encryption\Helper::getUser('newsconfigco...')\\n#2 appsfiles_encryptionlibproxy.php(309): OCA\Files_Encryption\Proxy->postFileSize('newsconfigco...', 126, Array)\\n#3 libprivatefileproxy.php(124): OCA\Files_Encryption\Proxy->postGetFileInfo('newsconfigco...', Array)\\n#4 libprivatefilesview.php(1016): OC_FileProxy::runPostProxies('getFileInfo', 'newsconfigco...', Array)\\n#5 libprivatefilesnodenode.php(61): OC\Files\View->getFileInfo('newsconfigco...')\\n#6 libprivatefilesnodenode.php(202): OC\Files\Node\Node->getFileInfo()\\n#7 libprivatefilesnodenode.php(85): OC\Files\Node\Node->getPermissions()\\n#8 libprivatefilesnodefile.php(19): OC\Files\Node\Node->checkPermissions(1)\\n#9 customappsnewsconfigconfig.php(181): OC\Files\Node\File->getContent()\\n#10 customappsnewsappinfoapplication.php(110): OCA\News\Config\Config->read('config.ini', true)\\n#11 3rdpartypimplepimplesrcPimpleContainer.php(112): OCA\News\AppInfo\Application->OCA\News\AppInfo\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))\\n#12 libprivateappframeworkutilitysimplecontainer.php(91): Pimple\Container->offsetGet('OCA\\News\\Config...')\\n#13 libprivateappframeworkutilitysimplecontainer.php(55): OC\AppFramework\Utility\SimpleContainer->query('OCA\\News\\Config...')\\n#14 libprivateappframeworkutilitysimplecontainer.php(73): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))\\n#15 libprivateappframeworkutilitysimplecontainer.php(93): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\News\\Contro...')\\n#16 libprivateappframeworkapp.php(90): OC\AppFramework\Utility\SimpleContainer->query('OCA\\News\\Contro...')\\n#17 libprivateappframeworkroutingrouteactionhandler.php(44): OC\AppFramework\App::main('PageController', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)\\n#18 [internal function]: OC\AppFramework\routing\RouteActionHandler->__invoke(Array)\\n#19 libprivaterouterouter.php(250): call_user_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)\\n#20 libbase.php(782): OC\Route\Router->match('appsnews')\\n#21 index.php(36): OC::handleRequest()\\n#22 {main}",
"File":"appsfiles_encryptionlibhelper.php",
"Line":306
}
```
