### ISSUE TITLE
Can't subscribe to any feeds

### ISSUE THREAD

**Issue by DougDossett** [owncloud/news#799]
I have a fresh install I'm trying to get working.  It runs but I can't subscribe to any feeds.  I just get the error "Website not found".  I'm not seeing any errors anywhere to explain further.  From the server I can use curl or wget to access the urls successfully, just not when subscribing.  Example url: http://rss.slashdot.org/Slashdot/slashdot

ownCloud version:  8.0.3
News version:  5.2.8, from what I can tell this is the latest version where I don't need 8.1 of owncloud, also tried various other older ones but no luck there either
Browser and version:  Firefox 27.01 and Chrome 43.0.2357.65
PHP version:  5.4.39-0
Distribution: Debian 7.5

Owncloud log doesn't seem especially useful despite enabling debug, just lots of this: 

{"reqId":"d03ee8386c02dee45dcc7a91902ad393","remoteAddr":"192.168.1.15","app":"lock","message":"INFO: Incrementing lock type 1 count for \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-23T20:04:52+00:00","method":"GET","url":"\/index.php\/apps\/news\/folders"}
{"reqId":"d03ee8386c02dee45dcc7a91902ad393","remoteAddr":"192.168.1.15","app":"lock","message":"INFO: Releasing locks on \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-23T20:04:52+00:00","method":"GET","url":"\/index.php\/apps\/news\/folders"}
{"reqId":"d03ee8386c02dee45dcc7a91902ad393","remoteAddr":"192.168.1.15","app":"lock","message":"INFO: Released lock handle Resource id #558 on \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-23T20:04:52+00:00","method":"GET","url":"\/index.php\/apps\/news\/folders"}
{"reqId":"d03ee8386c02dee45dcc7a91902ad393","remoteAddr":"192.168.1.15","app":"lock","message":"FREE: Released locks on \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-23T20:04:52+00:00","method":"GET","url":"\/index.php\/apps\/news\/folders"}
{"reqId":"992a4828d762e2ab942bdcef3b890052","remoteAddr":"192.168.1.15","app":"lock","message":"INFO: Read lock requested for \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-23T20:04:52+00:00","method":"GET","url":"\/index.php\/apps\/news\/feeds"}
{"reqId":"992a4828d762e2ab942bdcef3b890052","remoteAddr":"192.168.1.15","app":"lock","message":"PASS: Acquired read lock for \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-23T20:04:52+00:00","method":"GET","url":"\/index.php\/apps\/news\/feeds"}
{"reqId":"992a4828d762e2ab942bdcef3b890052","remoteAddr":"192.168.1.15","app":"lock","message":"INFO: Incrementing lock type 1 count for \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-23T20:04:52+00:00","method":"GET","url":"\/index.php\/apps\/news\/feeds"}
{"reqId":"992a4828d762e2ab942bdcef3b890052","remoteAddr":"192.168.1.15","app":"lock","message":"INFO: Releasing locks on \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-23T20:04:52+00:00","method":"GET","url":"\/index.php\/apps\/news\/feeds"}
{"reqId":"992a4828d762e2ab942bdcef3b890052","remoteAddr":"192.168.1.15","app":"lock","message":"INFO: Released lock handle Resource id #558 on \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-23T20:04:52+00:00","method":"GET","url":"\/index.php\/apps\/news\/feeds"}
{"reqId":"992a4828d762e2ab942bdcef3b890052","remoteAddr":"192.168.1.15","app":"lock","message":"FREE: Released locks on \/var\/www\/owncloud\/data\/news\/config\/config.ini","level":0,"time":"2015-05-23T20:04:52+00:00","method":"GET","url":"\/index.php\/apps\/news\/feeds"}

I'm guessing this is something relatively simple, but I don't know what the issue is.  The base owncloud works fine, I can upload files, etc. and other apps like Notes work.   Any help to get this running would be much appreciated.

**Comment by Raydiation** [comment]
The last time someone opened the same issue his web hosting provider blocked all outgoing requests

**Comment by Raydiation** [comment]
Please search the closed issues in the bug tracker to get more info, currently on the train ;)

**Comment by DougDossett** [comment]
Sorry to have bothered you.  Appears to have been a misunderstanding of a configuration option in the owncloud config.  I have it behind a reverse proxy and had a value in the proxy setting I shouldn't have had.  Took that out and it started working.
