### ISSUE TITLE
RFE: visit feed button

### ISSUE THREAD

**Issue by patricktokeeffe** [owncloud/news#800]
I was thinking about the current process for viewing feed urls (export OPML)... having a button to open the raw feed in a new tab would make that task easier. And it would have more utility than a component which is just for viewing or copying the url.

**Comment by patricktokeeffe** [comment]
I can see how 'open' might be confusing word choice.

**Comment by Raydiation** [comment]
I don't understand what should get easier

**Comment by cosenal** [comment]
[This issue is a continuation of #798.]

@patricktokeeffe As mentioned in other issues, we believe that viewing the raw feed is not a task needed for regular users. It's quite a geeky thing and I don't see why it's necessary to be made a one-click action.

**Comment by patricktokeeffe** [comment]
You're right: it'd be used for troubleshooting more than anything else. I'll find a different angle.
