### ISSUE TITLE
Can't mark feed as read

### ISSUE THREAD

**Issue by UnnamedHero** [owncloud/news#805]
Hello.
OC 8.1Beta2, News 5.3.5, Firefox 38.0.1, Google Chrome 37.0.2062.120

How can I manually mark feed as read without pressing header url? Pressing black eye icon do nothing. 

By the way, pressing middle mouse button (open url in a tab)on header url do not mark feed read in Firefox, but it works in Google Chrome

**Comment by Raydiation** [comment]
Ad 1) You can simply click on the body. The black eye icon is for keeping an article unread, meaning that if you toggle it it will prevent marking the item read. This is useful for keeping articles around and reading them later. 

Ad 2) Good catch, fixed. Caused by different browser behavior btw
