### ISSUE TITLE
Read marked feed gets unread after cron run

### ISSUE THREAD

**Issue by Gomez** [owncloud/news#807]
This feed get unread if the cron runs:

http://onlinelibrary.wiley.com/rss/journal/10.1002/%28ISSN%292169-9291

Reproduce:
1. Add the feed and let it populate
2. Mark the feed as read (in the nav)
3. Come back after a while (cron was executed) 
4. Feed is unread

As reported by a user it worked with a older news/owncloud version

**Comment by Raydiation** [comment]
The feed does not provide a guid element therefore we have to resort to a different way to check that a feed is not added twice. This is done by hashing over the title, url and content.

The feed in question changes the image URLs inside the content every time you access the feed, compare the following URLs for instance.

    <img alt="inline image" src="http://onlinelibrary.wiley.com/store/10.1002/2014JC010415/asset/equation/jgrc21269-math-0001.png?v=1&amp;t=iajaq34l&amp;s=6073f7433e33dc0d240b19f3d95ee884d3f2e176" class="inlineGraphic"/>
    <img alt="inline image" src="http://onlinelibrary.wiley.com/store/10.1002/2014JC010415/asset/equation/jgrc21269-math-0001.png?v=1&amp;t=iajas7sb&amp;s=2ab54f91641f98844a9be1553c5f367278c4acc4" class="inlineGraphic"/>

I suppose this is done for caching purposes. This however does not allow us to reliably determine if the element is the same and therefore causes elements to reappear (even without marking them as read).

**Comment by sambarluc** [comment]
But these feeds were working fine on owncloud 7, so there must be something new in version 8.

**Comment by Gomez** [comment]
@sambarluc The News app got a update to. And the feed parser changed. Can be that wiley.com added some caching..

**Comment by Raydiation** [comment]
2.x which also ran on ownCloud used a different feed library which was unmaintained and broken in many places.

Your best bet is to contact the page maintainer and notify him to update his feed format and provide a guid. The feed uses RSS 1.x which was released in 2000 and replaced by RSS 2 in 2002 btw.

**Comment by sambarluc** [comment]
I contacted wiley.com, let's hope they fix it, they seem to be indeed a bit out of date...
Thanks in any case.
