### ISSUE TITLE
Uninstall with option to delete database tables and appconfig

### ISSUE THREAD

**Issue by aidanamavi** [owncloud/news#809]
For the admins who aren't developers, it would be beneficial to streamline the removal process by providing a check box next to the uninstall button in the Apps section, which removes the appconfig entries and news tables in the database upon deletion.

The read me says to remove the news app folder, however that step is no longer necessary because this process is streamlined, but the database removal is not. Therefore, it would be logical to provide this enhancement to the UX.

**Comment by Raydiation** [comment]
Great idea, however this needs to be implemented on core first, can you reopen the issue there?
