### ISSUE TITLE
News 5.3.6 problem on OC 8.1 beta2

### ISSUE THREAD

**Issue by tflidd** [owncloud/news#810]
System: Debian wheezy with openSuSE testing-branch of owncloud, running OC 8.1 beta2 (apache, mod_php, mysql)

I wanted to update the news app but the update from the OC interface failed (error 23 from curl). So I downloaded the latest release (5.3.6) as zip-file from github, unpacked it to the apps-folder, changed the owner to www-data. I needed to run the upgrade procedure which created a database error. After that I thought it might be related to this database error, so I deactivated the news app, deleted all oc_news_* tables and settings in oc_preferences. Then I activated the news app, but I got this error (no tables were created on the database):

````

Internal Server Error

The server encountered an internal error and was unable to complete your request.

Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.

More details can be found in the server log.

Technical details

    Remote Address: 2001:xxxx::yyyy
    Request ID: cZ5VapQF8zYCWDW0RzdY
    Type: OCP\AppFramework\QueryException
    Code: 0
    Message: Could not resolve OCA\News\Controller\PageController! Class OCA\News\Service\StatusService does not exist
    File: /var/www/owncloud/lib/private/appframework/utility/simplecontainer.php
    Line: 83


Trace

#0 /var/www/owncloud/lib/private/appframework/utility/simplecontainer.php(97): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\News\\Contro...')
#1 /var/www/owncloud/lib/private/appframework/app.php(95): OC\AppFramework\Utility\SimpleContainer->query('OCA\\News\\Contro...')
#2 /var/www/owncloud/lib/private/appframework/routing/routeactionhandler.php(45): OC\AppFramework\App::main('PageController', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#3 [internal function]: OC\AppFramework\routing\RouteActionHandler->__invoke(Array)
#4 /var/www/owncloud/lib/private/route/router.php(272): call_user_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)
#5 /var/www/owncloud/lib/base.php(862): OC\Route\Router->match('/apps/news/')
#6 /var/www/owncloud/index.php(40): OC::handleRequest()
#7 {main}
````

**Comment by Raydiation** [comment]
Did you check if service/status service.php exists in the news folder?

**Comment by tflidd** [comment]
there is a service-folder, even a service.php but all files in the service-folder are empty

**Comment by tflidd** [comment]
The archive was unpacked in midnight commander. I used the unzip command directly. Now, everything was properly unpacked. I still needed to delete the entries in the oc_appconfig-table related to the news app (news tables were deleted). Now it works.

Sorry for this false alert. This error was related to the unzipping routine in the midnight commander (mc).
