### ISSUE TITLE
Certain UTF-8 characters break Mysql

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/news#813]
https://xkcd.com/1538/

It doesn't show up in the entry. It simply shows the header and nothing more:
![bildschirmfoto von 2015-06-17 02-40-56](https://cloud.githubusercontent.com/assets/245432/8197600/58af6ae8-149a-11e5-8a92-d13695bfed35.png)

**Comment by Raydiation** [comment]
Works for me. Can you try to disable your adblocker etc?

**Comment by MorrisJobke** [comment]
Weird ... does work on my dev env (same core and news app version) but not on my production env. Any hints what could be the cause for this?

**Comment by MorrisJobke** [comment]
MySQL tables have the same character set and collation.

**Comment by Raydiation** [comment]
In running sqlite and postgres maybe really a db problem? That post contains a lot of weird characters, maybe that's the issue?

**Comment by MorrisJobke** [comment]
Ah ... yes. My test instance is SQLite. @Raydiation Can you add this as test case? Maybe we should add something like this also as a core test case to verify that input == output after a database store and read operation?

cc @DeepDiver1975 Opinion on this?

**Comment by Raydiation** [comment]
I've had some Unicode issues in the past, suspected our db layer

**Comment by MorrisJobke** [comment]
Refs: 
https://github.com/owncloud/core/issues/3190
https://github.com/owncloud/core/issues/4513
https://github.com/owncloud/core/issues/7030
https://github.com/owncloud/core/issues/11506

I will try to create a unit test that bricks the DB layer. Let me see

**Comment by Raydiation** [comment]
```xml
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0"><channel><title>xkcd.com</title><link>http://xkcd.com/</link><description>xkcd.com: A webcomic of romance and math humor.</description><language>en</language><item><title>Hemingway</title><link>http://xkcd.com/1540/</link><description>&lt;img src="http://imgs.xkcd.com/comics/hemingway.png" title="Instead of bobcat, package contained chair." alt="Instead of bobcat, package contained chair." /&gt;</description><pubDate>Fri, 19 Jun 2015 04:00:00 -0000</pubDate><guid>http://xkcd.com/1540/</guid></item><item><title>Planning</title><link>http://xkcd.com/1539/</link><description>&lt;img src="http://imgs.xkcd.com/comics/planning.png" title="[10 years later] Man, why are people so comfortable handing Google and Facebook control over our nuclear weapons?" alt="[10 years later] Man, why are people so comfortable handing Google and Facebook control over our nuclear weapons?" /&gt;</description><pubDate>Wed, 17 Jun 2015 04:00:00 -0000</pubDate><guid>http://xkcd.com/1539/</guid></item><item><title>Lyrics</title><link>http://xkcd.com/1538/</link><description>&lt;img src="http://imgs.xkcd.com/comics/lyrics.png" title="To me, trying to understand song lyrics feels like when I see text in a dream but it𝔰 hอᵣd t₀ ᵣeₐd aกd 𝒾 canٖt fཱྀcu༧༦࿐༄" alt="To me, trying to understand song lyrics feels like when I see text in a dream but it𝔰 hอᵣd t₀ ᵣeₐd aกd 𝒾 canٖt fཱྀcu༧༦࿐༄" /&gt;</description><pubDate>Mon, 15 Jun 2015 04:00:00 -0000</pubDate><guid>http://xkcd.com/1538/</guid></item><item><title>Types</title><link>http://xkcd.com/1537/</link><description>&lt;img src="http://imgs.xkcd.com/comics/types.png" title="colors.rgb(&amp;quot;blue&amp;quot;) yields &amp;quot;#0000FF&amp;quot;. colors.rgb(&amp;quot;yellowish blue&amp;quot;) yields NaN. colors.sort() yields &amp;quot;rainbow&amp;quot;" alt="colors.rgb(&amp;quot;blue&amp;quot;) yields &amp;quot;#0000FF&amp;quot;. colors.rgb(&amp;quot;yellowish blue&amp;quot;) yields NaN. colors.sort() yields &amp;quot;rainbow&amp;quot;" /&gt;</description><pubDate>Fri, 12 Jun 2015 04:00:00 -0000</pubDate><guid>http://xkcd.com/1537/</guid></item></channel></rss>
```

Added the XML in case it is not available in the feed anymore :)

**Comment by MorrisJobke** [comment]
https://github.com/owncloud/core/pull/17978 <- lets discuss it there.

**Comment by Raydiation** [comment]
Closed as wontfix, see https://github.com/owncloud/core/pull/17978

Tests and recommendations will be moved to postgres :)
