### ISSUE TITLE
Updates are not updated when using server-side encryption - "Could not determine user"

### ISSUE THREAD

**Issue by hevtig** [owncloud/news#815]
Hello,
as stated here (https://github.com/owncloud/core/issues/14209) feeds are not being updated when using server-side encryption. The error message in the log file is "Could not determine user". There was a workaround til OC 8.0.3 which doesn´t work anymore on OC 8.0.4. It would be great if a developer could at least determine if it is an encryption or a news issue.

**Comment by Raydiation** [comment]
Encryption is not supported, see https://github.com/owncloud/news#before-reporting-bugs

**Comment by Raydiation** [comment]
It's an encryption issue btw

**Comment by Raydiation** [comment]
Which basically can be summed up to cron + encryption is broken.

**Comment by hevtig** [comment]
Ah, I see. Thanks for the information.

**Comment by xn--nding-jua** [comment]
Hey,

when using webcron, the cron.php has to be fixed regaring to https://github.com/owncloud/core/issues/8531

Then the current version of news app is working even with encryption enabled for ownCloud >=8.1 without restrictions!

kind regards,
Chris
