### ISSUE TITLE
API requests should not require DELETE or PUT

### ISSUE THREAD

**Issue by proth** [owncloud/news#817]
In a standard apache installation DELETE and PUT are not among the allowed methods.
Those are: OPTIONS, GET, HEAD, POST

This means right now I can write a news client that uses the API to fetch and display folders, feeds and items. It is not possible to mark items or entire feeds as read when using a standard apache setup.

Suggestions:
1) Beside PUT and DELETE also allow GET for API calls that now require PUT or DELETE if they are not among the allowed methods.
2) Warn the administrator/user in the web interface that he won't be able to use some API features when PUT and DELETE are not among the allowed methods

**Comment by Raydiation** [comment]
Apache is not an API client, its a web server.

**Comment by Raydiation** [comment]
See https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Request_methods

**Comment by Raydiation** [comment]
We are following the HTTP 1.1 spec which apache started to support back in 1996.

**Comment by proth** [comment]
Of course I am talking about the news API https://github.com/owncloud/news/wiki/API-1.2

See ownCloud runs on a web server (like Apache). The news API is a RESTful API (this means URLs are being requested to get information, update a status, etc.) that works via this web server.

Apache does support PUT and DELETE. But those methods are disabled by default after installing apache (also by most webhosters).

I know how to enable them. That is not my problem.
The problem is that other users don't know that PUT and DELETE are required for a proper working API.

**Comment by Raydiation** [comment]
See http://serverfault.com/questions/438183/how-to-enable-all-http-methods-in-an-apache-http-server

>  For dynamic content (CGI scripts, mod_php, etc), Apache does not care what the HTTP method is (unless it is explicitly restricted with a <Limit> directive), and passes the request to the appropriate handler as it is. Your script needs to handle the specific method as intended, not Apache. Even non-standard methods are passed to dynamic handlers with no problem.

PHP handles those methods, not apache, so this is not an issue unless your hoster limits those methods artificially. If your hoster does this then contact him or choose a different hosting or vserver. There won't be workarounds for webhosting.

**Comment by proth** [comment]
Right, PHP handles those methods if apache allows them. Since apache is the web server (in my case) it catches all HTTP requests and check whether it can handle them or not. If an http client requests
https://myinstallation/owncloud/index.php/apps/news/api/v1-2/items/123/read
via PUT request PHP won't do any thing because it's never notified that there is something to do since apache does not allow PUT out of the box.
In a standard installation of apache the allowed request methods are OPTIONS, GET, HEAD, POST.

As said I know how to fix this issue for my installation. The problem is that I can't fix this on all the web servers of potential users.

**Comment by Raydiation** [comment]
Since this is a precondition to use owncloud and the news app, it is up to the administrator to make sure that his server is configured correctly. Non issue.

**Comment by proth** [comment]
Which brings us to my second suggestion:
2) Warn the administrator/user in the web interface that he won't be able to use some API features when PUT and DELETE are not among the allowed methods

**Comment by Raydiation** [comment]
That would be a core issue.

**Comment by proth** [comment]
Oops. Sorry I just figured out that this is already an known issue in the news module.
See screenshot attached.

Would you mind to re-open this issue?

![screen shot 2015-06-19 at 14 58 16](https://cloud.githubusercontent.com/assets/806286/8253832/b79dcaae-1693-11e5-8369-c4b9d12891d5.png)

**Comment by Raydiation** [comment]
This is just because POST would for those routes better than PUT based on it's definition. This has nothing to do with your issue

**Comment by Raydiation** [comment]
S/for/fit

**Comment by proth** [comment]
In fact it is somewhat related to my issue since it would fix the problem.
Shall I open a new issue for those PUT to POST conversions?

**Comment by Raydiation** [comment]
It would not fix your problem because there will still be DELETE and PUT requests, the POST changes only apply to a subset. While the FIXME is there, the API is used too widely to just break it because certain HTTP methods would fit better. 

Once we break the API, we could clean it up eventually (if that ever happens though). Since this is not an issue that has a roadmap for fixing, the FIXME in the code is fine, no further open issues needed ;)
