### ISSUE TITLE
Feed item not being hidden when no unread articles are left

### ISSUE THREAD

**Issue by tgrosinger** [owncloud/news#818]
**ownCloud Version:** 8.0.4
**News App Version:** 5.2.8
**Browser:** Chrome 43.0.2357.125 (64-bit)
**PHP Version**:

```bash
$ php --version
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

I have not yet figured out how to reliably reproduce this, but I have had it happen many times.

![selection_021](https://cloud.githubusercontent.com/assets/597386/8381900/a9a5136c-1be3-11e5-96f6-8a79c4ca0a92.png)

Notice that is says no unread articles, however there are still two row items left un-hidden on the left. Pressing `r` does not solve the issue, but refreshing the page does.

Let me know if I can provide more information to help debug this issue.

**Comment by Raydiation** [comment]
Its an angular issue I think. Its hard to debug, maybe someone else can fix it or we'll have to wait until angular 2 comes out

**Comment by Raydiation** [comment]
Feel free to try to fix it ;)

**Comment by BernhardPosselt** [comment]
Haven't had this issue in forever, probably an angular update fixed it. Please reopen if this is still an issue
