### ISSUE TITLE
After deleting feeds, they no longer appear on the list but they are not deleted completely

### ISSUE THREAD

**Issue by martinchodev** [owncloud/news#821]
Hello

This is what happened. I added an OPML exported from another feed reader (Inoreader) and imported it on the ownCloud reader.
I got a lot of timeouts and canceled the whole thing. I tried adding them by hand and some worked and others didn't, so I tried to start over, deleted every feed manually, and I even uninstalled the app and reinstalled it, and now I get this error message for almost all of them:

![captura de pantalla_2015-07-07_15-23-31](https://cloud.githubusercontent.com/assets/7395872/8553785/254be51e-24bc-11e5-9331-dac73b9fa194.png)

Note that the feed list is empty, there are no folders or individual feeds added.

Is there a way to reset the plugin's preferences or something like that?

I'm running Manjaro Linux and ownCloud version 8.0.4-2 and owncloud-app-news 5.2.8-1

Thanks

EDIT: Also, the folders still appear on the dropdown, but they are not actually there.

![captura de pantalla_2015-07-07_15-26-35](https://cloud.githubusercontent.com/assets/7395872/8553877/c5bf05c6-24bc-11e5-9a80-131d311e43f0.png)

**Comment by cosenal** [comment]
Just making sure that you are not missing the obvious: have you tried to change the setting »Show all articles»?

**Comment by martinchodev** [comment]
Oh sh*t, I'm new to ownCloud and totally missed that. My fault!!

Thanks!

XD
