### ISSUE TITLE
Favorites sort by folder or tag

### ISSUE THREAD

**Issue by thfree** [owncloud/news#823]
Will there be implemented tagging of interesting news on the tags, and not in the pile?

**Comment by Raydiation** [comment]
Tagging is more of a chore work, you need to do it by yourself. Much better is to go with things that are already available, like the feed address and article content. Filtering by those tags is already possible by using the built in search feature in the newest version. This should cover pretty much all usescases.

Additionally there's #776 which will allow you to make those searches persistent and easily accessible, so you can basically create folders that contain all feeds from somedomain.com or that contain "whiskey"
