### ISSUE TITLE
Wordpress feed error

### ISSUE THREAD

**Issue by dervomsee** [owncloud/news#825]
Hi,
with the following feed i get the error "Could not find a feed".
http://www.weltreise1.de/feed/

Is it a problem of my OC installation or a OCNews problem?

Regards and thank you!

**Comment by cosenal** [comment]
This is odd, I can reproduce it on ownCloud, but the feed works fine with picofeed-cli and with miniflux+picofeed (everything master here).
Maybe some strange curl setting in ownCloud?

**Comment by Raydiation** [comment]
Not a bug, check the picofeed thread ;)

**Comment by dervomsee** [comment]
Thank you for the solution. I fixed it temporally by changing the user agent.

**Comment by Raydiation** [comment]
Please also contact the site admin and ask him to fix his server setup
