### ISSUE TITLE
cookie problem with google chrome ?

### ISSUE THREAD

**Issue by jajaX** [owncloud/news#827]
Hi (sorry for my bad english) !

I've got a issue with google chrome under kubuntu 14.04 (64 bits) and Owncloud 8.1 / News 5.3.8.

since last update of Owncloud and News, I've got, after a small time, this message :

Requête non autorisée. Êtes-vous bien connecté avec vos identifiants ?"

in english => "Not authorised request. Are you connected fine with your logins ?"

after refresh the News page (with F5), I must login to Owncloud again and News work.

after a small time, this message come back....

I've this probleme with google chrome only.

no problem with Mozilla Firefox.

thanks ;)

**Comment by Raydiation** [comment]
This is a configuration or core issue and the News app is probably the only app that notifies you when your session runs out. 

First check your session configuration in the php.ini (http://stackoverflow.com/questions/3476538/php-sessions-timing-out-too-quickly) and if that does not work, file a bug in core
