### ISSUE TITLE
Align Settings

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/news#829]
It will look smoother if the text starts not at the checkbox but at the line above if it wraps.

**current**
![current](https://cloud.githubusercontent.com/assets/4741199/8847325/00605b58-312e-11e5-8f3d-aa0a5449cda9.png)

**expected**
![expected](https://cloud.githubusercontent.com/assets/4741199/8847327/05602d54-312e-11e5-8298-9d635d31e135.png)

**Comment by Raydiation** [comment]
Looks good, can you prepare a pull request? Don't forget to compile the CSS with grunt ;)

**Comment by stefan-niedermann** [comment]
sry for closing err: nope, this was just a mockup ;)

**Comment by Raydiation** [comment]
CSS file to make changes: https://github.com/owncloud/news/blob/master/css/settings.css

Changes will need to be uglified with grunt. To do that change into the **js/** folder and run

    sudo npm -g install grunt-cli
    npm install

To build the CSS run

    grunt

or to build when you change the file:

    grunt watch

**Comment by BernhardPosselt** [comment]
Thanks to @IBBoard who fixed the issue :)
