### ISSUE TITLE
Feature request: Hide feed item content

### ISSUE THREAD

**Issue by mcladyz** [owncloud/news#831]
Add a config option to hide feed item content by default and show titles only. Add a button beside each title to expand the content.

This is useful for quickly checking news of interest by titles alone. Also helps the performance on slower devices.

[ttRSS](https://www.tt-rss.org/gitlab/fox/tt-rss/wikis/home) can be used as a reference for this feature.

**Comment by Raydiation** [comment]
Already implemented, called compact view
