### ISSUE TITLE
libxml is now an hard dependency for the news app

### ISSUE THREAD

**Issue by averi** [owncloud/news#834]
Since a few releases the news app is not compatible with systems running RHEL 6 anymore as it requires an higher version of the libxml package, specifically 2.7.8 (while RHEL 6 has 2.7.6).

Is libxml 2.7.8 really required in order for the news app to work properly or can it be made a soft dependency?

**Comment by Raydiation** [comment]
There are no soft dependencies ;) 

2.7.8 is required and rhel 6 is not supported, see the readme

**Comment by averi** [comment]
As expected I should upgrade the GNOME Owncloud instance to RHEL 7. Thanks for confirming that was the case!

**Comment by jancborchardt** [comment]
@averi btw @Raydiation is using GNOME (he was at GUADEC with me back in Brno) and will be happy to hear that you run the News app on the ownCloud instance at cloud.gnome.org :)

**Comment by averi** [comment]
That's great! the news app was so great for me that I did even buy the Android app for that until RHEL 6 wasn't supported anymore and we lost the news app all together.

I'll see when I can have a RHEL 7 VM up and running for the migration to happen. :-)

**Comment by jancborchardt** [comment]
The Android app is awesome too, thanks to @David-Development ;)
