### ISSUE TITLE
Unable to generate a URL for the named route "calendar_index" as such route does not exist.

### ISSUE THREAD

**Issue by lukas-schulze** [owncloud/news#837]
I'm using ownCloud 8.1.1 on a Debian 7 server with nginx and php-fpm.
If I try to update apps like calendar or contacts, I get the following error message:

__Unable to generate a URL for the named route "calendar_index" as such route does not exist.__

I thought It might be related to the use of nginx. However, I cannot find any related information to fix this problem.
Does anyone know, how to solve this?

![image](https://cloud.githubusercontent.com/assets/820580/9262402/f9d9c786-4214-11e5-9509-b7dba5259295.png)

**Comment by Raydiation** [comment]
Not a news issue

**Comment by lukas-schulze** [comment]
Can you give me some more information? If it is not a new issue, which is the original one?

**Comment by Raydiation** [comment]
You are writing in the wrong repo ;) this is the news app not the calendar app
