### ISSUE TITLE
News 6.0.0 breaks owncloud

### ISSUE THREAD

**Issue by v1r0x** [owncloud/news#838]
I recently updated to News 6.0.0 and now the whole owncloud (8.1.1) doesn't work anymore.

server log shows this line:
```
 PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /www/owncloud/apps/news/appinfo/application.php on line 51" while reading response header from upstream
```

**Comment by Xefir** [comment]
What's your PHP version ? PHP 5.5 or more is required from News 6.0

**Comment by Raydiation** [comment]
It should actually not be possible to activate the app without php 5.5 (required in the info.xml). Please open a bug report in core if you did not change that value
