### ISSUE TITLE
Please, get back using php 5.4 and get CentOS support back

### ISSUE THREAD

**Issue by UnnamedHero** [owncloud/news#839]
I think ,amy users using owncloud with RedHat/Oracke/CentOS server solutions. Good  support and long support licecycle. But now you are using php 5.5 which not supported withing those distros. OwnCloud itself support php 5.4. I thing it is a good idea to support same minimakl php version as owncloud. May be you can support two branches - with php 5.5 and php 5.4?

**Comment by Raydiation** [comment]
CentOS 7 was supported before they reverted from php 5.6 back to 5.4.

5.4 security support ends in a few days. Either upgrade your php using a repo (scl, remix) or stay with the 5.x release

**Comment by Raydiation** [comment]
See https://www.softwarecollections.org/en/scls/rhscl/php55/

**Comment by UnnamedHero** [comment]
Thank you. Already updated.
