### ISSUE TITLE
Cannot subscribe to Communities Dominate Brands feed 

### ISSUE THREAD

**Issue by blizzz** [owncloud/news#840]
I attempt to subscribe to this blog http://communities-dominate.blogs.com/ by giving domain, but also trying with the Feed URL http://communities-dominate.blogs.com/brands/rss.xml

The feed URL can be opened properly in Firefox and also the [Validator](https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fcommunities-dominate.blogs.com%2Fbrands%2Frss.xml) confirms its validity.

No JS errors. 

Network tab reveals this error:

```
POST XHR https://mine.com/owncloud/index.php/apps/news/feeds [HTTP/1.1 422 Unprocessable Entity 150ms]
```

with Response Body

```
{"message":"Could not find a feed"}
```

> data/owncloud.log (important!)

```
{"reqId":"ovTgexLmps7Ml\/TTMujt","remoteAddr":"2a01:4f8:190:14e5::2","app":"no app in context","message":"Current user is not logged in","level":0,"time":"2015-08-17T09:17:45+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds"}
{"reqId":"K4qK1XkrgpnlslTrbhC5","remoteAddr":"194.29.236.66","app":"news","message":"Could not find a feed","level":0,"time":"2015-08-17T09:17:45+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/news\/feeds"}
```

> ownCloud version

8.1.1

> News version

6.0.1

> Browser and version

Firefox 40

> PHP version

5.5.9

> Distribution

Ubuntu 14.04

**Comment by Raydiation** [comment]
Both URLs work for me, can not reproduce.

Can you run the news:verify-install command (see the readme) if all files match the ones that should be shipped?

**Comment by Raydiation** [comment]
@cosenal

**Comment by Raydiation** [comment]
Also check PHP caching

**Comment by blizzz** [comment]
```
# sudo -u www-data ./occ news:verify-install
 558/558 [============================] 100%

Installation verified, everything OK!
```

> Also check PHP caching

APCu (4.0.6) is enabled. Same after restarting Apache.

It's the only feed i have issues with. Others are fine.

**Comment by Raydiation** [comment]
No idea :/

**Comment by jajaX** [comment]
Hi (sorry for my bad english)

Both URLs work for me too !

**Comment by Raydiation** [comment]
Thanks for confirming :)

**Comment by Raydiation** [comment]
A while ago we encountered a feed that broke because of our user agent name, paranoid settings probably. Can you try if you can curl the feed on your console? Maybe firewall or another weird issue

**Comment by cosenal** [comment]
It works here with **exactly** the same setup! I agree with Raydiation, your IP might be in some black list, or some crap like that.

**Comment by blizzz** [comment]
Indeed. Using just wget from my server ends up in 403, from my laptop its fine. :unamused:
