### ISSUE TITLE
SQL error: the total number of locks exceeds the lock table size

### ISSUE THREAD

**Issue by pravussum** [owncloud/news#841]
I had a quite old installation of news reader which I recently updated to Owncloud 8.1.1. Therefore I've got thousands of news items and the GUI becomes really sluggish (inititial page load is slow).
Some operations fail with the following error (e. g. marking a group of feeds with 75000+ unread items as read):
From owncloud.log:
```JSON
{"reqId":"UrNeNhj\/o2N7CoH3F6RQ","remoteAddr":"194.25.158.132","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE `oc_news_items` SET `status` = `status` & ? , `last_modified` = ? WHERE `feed_id` = ? AND `id` <= ? AND EXISTS (SELECT * FROM `oc_news_feeds` WHERE `user_id` = ? AND `id` = ? ) ' with params [-3, 1439808182, 172, 236539, \\\"pravussum\\\", 172]:\\n\\nSQLSTATE[HY000]: General error: 1206 The total number of locks exceeds the lock table size\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/vhosts\\\/mortalsilence.net\\\/wolke\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/vhosts\\\/mortalsilence.net\\\/wolke\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(172): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE `oc_news...', Array)\\n#2 \\\/var\\\/www\\\/vhosts\\\/mortalsilence.net\\\/wolke\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(250): Doctrine\\\\DBAL\\\\Statement->execute()\\n#3 \\\/var\\\/www\\\/vhosts\\\/mortalsilence.net\\\/wolke\\\/apps\\\/news\\\/db\\\/itemmapper.php(142): OCP\\\\AppFramework\\\\Db\\\\Mapper->execute('UPDATE `*PREFIX...', Array)\\n#4 \\\/var\\\/www\\\/vhosts\\\/mortalsilence.net\\\/wolke\\\/apps\\\/news\\\/service\\\/itemservice.php(198): OCA\\\\News\\\\Db\\\\ItemMapper->readFeed(172, 236539, 1439808182, 'pravussum')\\n#5 \\\/var\\\/www\\\/vhosts\\\/mortalsilence.net\\\/wolke\\\/apps\\\/news\\\/controller\\\/feedcontroller.php(267): OCA\\\\News\\\\Service\\\\ItemService->readFeed(172, 236539, 'pravussum')\\n#6 [internal function]: OCA\\\\News\\\\Controller\\\\FeedController->read(172, 236539)\\n#7 \\\/var\\\/www\\\/vhosts\\\/mortalsilence.net\\\/wolke\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#8 \\\/var\\\/www\\\/vhosts\\\/mortalsilence.net\\\/wolke\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\News\\\\Controller\\\\FeedController), 'read')\\n#9 \\\/var\\\/www\\\/vhosts\\\/mortalsilence.net\\\/wolke\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\News\\\\Controller\\\\FeedController), 'read')\\n#10 \\\/var\\\/www\\\/vhosts\\\/mortalsilence.net\\\/wolke\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('FeedController', 'read', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/var\\\/www\\\/vhosts\\\/mortalsilence.net\\\/wolke\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#13 \\\/var\\\/www\\\/vhosts\\\/mortalsilence.net\\\/wolke\\\/lib\\\/base.php(873): OC\\\\Route\\\\Router->match('\\\/apps\\\/news\\\/feed...')\\n#14 \\\/var\\\/www\\\/vhosts\\\/mortalsilence.net\\\/wolke\\\/index.php(40): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/vhosts\\\/mortalsilence.net\\\/wolke\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":115}","level":4,"time":"2015-08-17T10:43:37+00:00"}
```
   
I read I can increase the buffer pool size to avoid the error, but actually it's a bad user experience and some users might not even have access to the db settings (hosted environments etc.).

So it might be a good idea to do such manipulations in batches of 10.000 or similar. A bonus would be a progress bar for long running operations (even though a DB update of a read flag should take mere milliseconds for 70.000 records if there's a corresponding index).

**Comment by Raydiation** [comment]
First of all this can't be fixed in News, if you think this is uber important, open an issue in core. Second it is not ownCloud's job to configure your database server. If you run your install with that many users or with that many feeds, you need to configure your environment to match those needs.

**Comment by Raydiation** [comment]
This is a server maintainenance issue and has nothing to do with the code ;)

**Comment by Raydiation** [comment]
To clear possible confusion: marking articles as read is a query that is already run in a single SQL command, so really is nothing left to be sped up.

**Comment by pravussum** [comment]
Understood. Still I think I've got a minimal setup - one active user for the news app and using it with some 50 feeds you easily get these figures after some month... 
And its not working with a default MySQL installation... I'm just saying this will lead to bad user experience (it just did ;-)).
For the technical side:
Even one query for groups of groups? Why are there so many locks anyway? Can you point me to the right code location? I'm a developer (not PHP but Java, but quite some SQL experience).

**Comment by Raydiation** [comment]
It really depends on your usage, I'd personally never hit those numbers. Read and unstarred articles are deleted automatically when running the update, nothing more. The basic mantra is: Never delete unread articles because they may be important (logs, etc). Therefore ignoring a large feed library for a long amount of time will of course pile up ;)

As far as I've understood it, the issue here is basically shitty MySql defaults (use Postgres if you want something saner), see https://major.io/2010/02/16/mysql-the-total-number-of-locks-exceeds-the-lock-table-size-2/  By default it stores a maximum amount of 8MB of references to locks. The update query first locks all rows in question before updating to prevent other queries modifying the rows in question. In your case the number of locks exceeds it and IMHO updating 75k rows should not be anything unusual.

Here's the code btw: https://github.com/owncloud/news/blob/master/db/itemmapper.php#L99 This is run when you mark a feed read. Marking a folder as read will run a query for every feed in it since it seemed to be a too unusual usecase to create a separate query for it ;)

**Comment by Raydiation** [comment]
BTW: workaround for this problem would probably be to write Stored Procedures which is out of scope. Not enough compensation for the pain ;)

**Comment by pravussum** [comment]
All right, thanks for the info. Just to let you know: the UI really becomes unusable with that many unread items (I had that many because I never got the News app running after OC 6 again btw). 
I worked around the timeouts and locking issues by marking every single feed read one after the other. Now I can at least use the UI again. 
So if you get bored some day you might want to run some tests with high unread counts... maybe some query sticks out as really inefficient. 
I'd do it myself, but right now I don't have any idea how to start profiling this PHP stuff. 
Thanks again for your patience :-)

**Comment by Raydiation** [comment]
That would be great :)

If you are interested, a performance testing suite would probably be nice.

The basic steps would be really simple:
* Add a phpunit.benchmark.xml which adds a different directory than this one here https://github.com/owncloud/app-tutorial/blob/master/phpunit.integration.xml#L4
* Create a tests/benchmark/ directory with tests in it
* Populate the database with default entries, for an example see this: https://github.com/owncloud/news/blob/master/tests/integration/bootstrap.php#L66

Then just run queries against the classes that you want to test, in your case the ItemMapper: https://github.com/owncloud/news/blob/master/tests/integration/bootstrap.php#L44

As for profiling, check this thread (XDebug is the solution afaik) http://stackoverflow.com/questions/8291366/how-to-benchmark-efficiency-of-php-script XDebug generates output that can be parsed, if you are using PHPStorm, this is basically built in and easy to use.

**Comment by Raydiation** [comment]
Easier than that would ofc to just dive into it using PHPStorm and submit an issue with your findings. Feel free to do whatever you like best ;)
