### ISSUE TITLE
[6.0.x] Display of heise.de feeds changed

### ISSUE THREAD

**Issue by nRaecheR** [owncloud/news#842]
**ownCloud Version:** 8.1.1
**News App Version:** 6.0.1
**PHP Version:** 5.6.4
**Android App Version:** 0.9.5.2

Maybe a coincidence but after updating the news app to 6.0.x the feeds from heise.de (newsticker, opensource) only showing the headline and no longer the whole text from the article. Someone need to open the web page to display the content of the page. On mobile device this means a lot more traffic to read these news items. 
The Security feed from heise.de has never been displayed in full but now the OpenSource and Newsticker feeds have changed too. 

Links to the feeds : http://www.heise.de/news-extern/news.html

Is there any way to get back the old pre-6.0.x behaviour ?

**Comment by Raydiation** [comment]
Yes, this is actually a feature in 6.0.0 where we replaced our own webscraper with the one from picofeed. The picoFeed enhancer is more generic and works with a lot of standard pages, however you have to enable it per feed. Click on the feed menu and choose the **Enable full text feed** option.

**Comment by Raydiation** [comment]
On a side note this also gives you the power to display the feed exactly as you want it

**Comment by nRaecheR** [comment]
Yes, it works! I've enabled the full text feed in the Web-UI and the feed items are fully fetched. Thank you for the quick help!
