### ISSUE TITLE
failed to import all feeds from opml file

### ISSUE THREAD

**Issue by nexus-uw** [owncloud/news#843]
Hello,

I have an opml file with about 400 feeds in 11 categories exported from feedly.Yesterday I tried importing it through the web ap. It managed to import all the categories, but only the feeds from the last 4 categories. I did not see any error messages in the app or in the owncloud log.

Is there some upper limit on the number of feeds I can import at once?

Thanks,
SR

**Comment by Raydiation** [comment]
Shouln't be, can you post the opml?

**Comment by Raydiation** [comment]
JavaScript console errors would be nice too, you need to enable debug mode first though, see the contributing.md

**Comment by Raydiation** [comment]
https://github.com/owncloud/news/blob/master/CONTRIBUTING.md#when-reporting-bugs

**Comment by nexus-uw** [comment]
owncloud.log: https://gist.github.com/nexus-uw/3b94c6f3d3bd82319622
php --version ->
PHP 5.5.9-1ubuntu4.11 (cli) (built: Jul  2 2015 15:23:08)
owncloud version 8.1.1
news version 6.0.1
browser: Chrome 43 64bit OSX
server dist: Ubuntu 14.04.2 LTS

didn't see any significant console errors (just some 403 about favicons)


would browser plugins interfere with adding feeds?

**Comment by nexus-uw** [comment]
@Raydiation, when I broke my opml file into separate file opml by category (10 categories, with at most 60 feeds per categories), I was able to successfully import all fees.

**Comment by Raydiation** [comment]
Big files should still work, they are actually just shoved into a queue :)

In case you're familiar with JS, you might take a look:

* https://github.com/owncloud/news/blob/master/js/service/OPMLImporter.js#L13
* https://github.com/owncloud/news/blob/master/js/service/OPMLParser.js

**Comment by nexus-uw** [comment]
Ok, so I took some time and looked over the files you mentioned above. There appears to be a couple of places that async errors are suppressed.


angular's $q.all will be rejected on the first promise that is rejected ("If any of the promises is resolved with a rejection, this resulting promise will be rejected with the same rejection value." - bottom of https://docs.angularjs.org/api/ng/service/$q) . so for https://github.com/owncloud/news/blob/master/js/service/OPMLImporter.js#L101
```js
this.importFeedQueue = function (feedQueue, jobSize) {
        // queue feeds to prevent server slowdown
        var deferred = $q.defer();

        var jobPromises = [];
        for (var i=0; i<jobSize; i+=1) {
            jobPromises.push(startFeedJob(feedQueue));
        }

        $q.all(jobPromises).then(function () {
            deferred.resolve();
        });

        return deferred.promise;
    };
```

could be refactored into 
```js 
this.importFeedQueue = function (feedQueue, jobSize) {
        var jobPromises = [];
        for (var i=0; i<jobSize; i+=1) {
            jobPromises.push(startFeedJob(feedQueue));
        }

        return $q.all(jobPromises).then(function () {
           return undefined; //to match existing method signature
        });
    };
```
so that if any of the jobPromises are rejected, the importFeedQueue promise will also be rejected (instead of never resolving).

also in https://github.com/owncloud/news/blob/7dcbea39cce13007375b770108a14fed76d8755f/js/controller/SettingsController.js#L36
in any error in the importing promise chain is being suppressed and will not be caught by the catch block. It could use something like this to deal with any errors in the promise chain
```js
  OPMLImporter.importFolders(parsedContent)
            .then(function (feedQueue) {
                return OPMLImporter.importFeedQueue(feedQueue, jobSize);
            })
           .then(function(){
}, function(e){
  console.error(error);
  self.opmlImportError = true;
})
.finally(function(){
  self.isOPMLImporting = false;
})
```

**Comment by Raydiation** [comment]
Right, the promises stuff should be refactored, however we don't want to abort import if something failed. If a feed failed to import, it should show up as a red box on the left side (that's how it should work right now).

Can you create a PR?

Try to create a small PR first with the refactored $q.all stuff to get running ;)
