### ISSUE TITLE
Missing favorite/mark as read icon

### ISSUE THREAD

**Issue by thenamelessthing** [owncloud/news#846]
Since the last update of the news app I don't see anymore the icon to mark as favorite and read/unread article...

**Comment by Raydiation** [comment]
Clear your browser cache and disable all your browser addons

**Comment by thenamelessthing** [comment]
I forgot to indicate it's for thye android app...

**Comment by Raydiation** [comment]
Wrong repo then ;D https://github.com/owncloud/News-Android-App

PS: swipe left/right

**Comment by thenamelessthing** [comment]
HA!  Swipe left/right did it!  Thanks you!  it's new since wich version?

**Comment by Raydiation** [comment]
2 weeks maybe, don't know since when exactly. I don't write any code for the Android app and I've got some issues myself with the news design, see https://github.com/owncloud/News-Android-App/issues/376 :)
