### ISSUE TITLE
J and K shortcuts don't work all the time.

### ISSUE THREAD

**Issue by tapir** [owncloud/news#847]
I always use keyboard to scroll through my feed. I've recently switched from Inoreader to ownCloud and I noticed something very annoying. Sometimes (1 out of 3 maybe?) when you press J or K to scroll down or up it doesn't really scroll but only moves couple pixels. You have to press a second time to actually make it scroll to the next article.

**Comment by tapir** [comment]
Unfortunately the fix only fixed J (scroll down), scroll up still has the same problem.

**Comment by BernhardPosselt** [comment]
Can you test again (using master)?

**Comment by tapir** [comment]
Sorry it took some time to test. It's not fixed yet. Still got that 1-2 pixel movement while scrolling up.

**Comment by BernhardPosselt** [comment]
Have you cleared the cache? It's working fine for me

**Comment by BernhardPosselt** [comment]
master that is

**Comment by tapir** [comment]
You mean php cache? is restarting php5-fpm enough?

I'm on master.

**Comment by BernhardPosselt** [comment]
browser cache :)

**Comment by tapir** [comment]
Cleared everything on Firefox (cache, offline data, history, cookies etc..). It's still not working.
Then I downloaded and tried Chrome. It's working OK there.

**Comment by BernhardPosselt** [comment]
Maybe 10px is not working good enough yet

https://github.com/owncloud/news/blob/master/js/gui/KeyboardShortcuts.js#L330

Can you change the + 10 to + 20 (or 15), recompile the JavaScript, clear cache and test again?

You need NodeJS and npm, then follow this instruction https://github.com/owncloud/news/tree/master/js#javascript--css-development
