### ISSUE TITLE
Allow to pin feeds to the top of a folder

### ISSUE THREAD

**Issue by BernhardPosselt** [owncloud/news#848]
See #368

@rakekniven

**Comment by rakekniven** [comment]
Summary of discussion  at #368 :
Pinned feeds would be on top and also ordered alphabetically (order by pinned, feed_name).

**Comment by rakekniven** [comment]
You are really, really fast. v6.0.3 works for me very well.
Thx.

**Comment by cosenal** [comment]
I like the idea, already using it! Thanks @rakekniven and @BernhardPosselt
