### ISSUE TITLE
Open article in background tab

### ISSUE THREAD

**Issue by stormsh** [owncloud/news#849]
Hello there, since a function to open articles in tabs is already there, I would like to suggest a shortcut to open an article in a background tab. I don't know which key would be the best for such a shortcut, but the "B" is still available. Also I don't know if it's hard to implement for different browsers.
Just let me know what you think.

st.

**Comment by cosenal** [comment]
I am ok with this. @BernhardPosselt Since it's an easy task, why don't we leave it open and encourage potential new contributors to take it?

**Comment by BernhardPosselt** [comment]
Background Tab?

**Comment by cosenal** [comment]
@BernhardPosselt AFAIU the OP is asking for a keyboard shortcut that opens the web page of the article in a new tab without moving the focus on that tab.

**Comment by BernhardPosselt** [comment]
I see, great idea if its easy to do :)

**Comment by BernhardPosselt** [comment]
The file that needs to be edited is this one, simple jQuery basically: https://github.com/owncloud/news/blob/master/js/gui/KeyboardShortcuts.js

Don't forget to compile the JS and CSS afterwards like described here https://github.com/owncloud/news/tree/master/js#javascript--css-development

**Comment by stormsh** [comment]
Thanks, I should use the speelcheka moore offden ;)

**Comment by tgrosinger** [comment]
Hmm, I gave this a shot. Even got the new keyboard shortcut working.

Sadly from what I have been reading it doesn't look like you can reliably (at all?) open new tabs in the background. It's a per-browser setting and if the user has new tabs set to open in the foreground then I don't think you can do anything about it from Javascript.

**Comment by BernhardPosselt** [comment]
@tgrosinger let's close the issue then?

**Comment by tgrosinger** [comment]
Yes, unfortunately.

**Comment by stormsh** [comment]
@tgrosinger Ok, what a pitty. But to open all in tabs would work? So that the last tab opened by the news app would be in focus?

**Comment by tgrosinger** [comment]
Yes, I think that is how it would work. What's interesting though is on mobile (at least Chrome on Android) when you open a link in a new tab it automatically opens it in the background.

**Comment by stormsh** [comment]
@tgrosinger On desktop you can use addons like tab mix plus to define tab behavior. That addon for instance is not available for the mobile browser. It could be that the tab behavior options in the mobile browser are limited to simplify user experience.
Could you have a look at #850? I would appreciate it :)
