### ISSUE TITLE
Open all unread/starred articles at once

### ISSUE THREAD

**Issue by stormsh** [owncloud/news#850]
Hello again, the second issue (suggestion) I would like to make is open all articles of a specific folder at once. This could be done by using shortcuts:
shift-o for opening all and switching to first open tab
shift-b for opening all in backround tab (if the open in bakround tab feature is available https://github.com/owncloud/news/issues/849 )
Or a simple button in the little three dot menu of each folder.
Thanks for reading.

st.

**Comment by BernhardPosselt** [comment]
You can do that already by using the jump to previous/next folder shortcuts right?

**Comment by stormsh** [comment]
I can navigate through the folders, but the unread articles are not opened in tabs. Like the "o" shortcut, just for a whole folder.

**Comment by BernhardPosselt** [comment]
I see, so this is more about tab management. I doubt that this is a good idea. Because PHP does not support websockets because of its request model, your stuff gets out of sync pretty fast. We don't poll for changes that often to reduce the load, so I would not recommend this approach at all. You can however still use the URL and open it in a second tab.

Closing hence :)

**Comment by stormsh** [comment]
Ok, I don't know much about programming and php, so I thought it would be easy since there is already a function similar to what I suggested. No problem. Keep up the good work :+1:

**Comment by cosenal** [comment]
@BernhardPosselt I don't see how this is related to syncing/php requests. Maybe there was a misunderstanding.

@stormsh Let me clarify if I understood the suggestion. Again you would like a keyboard shortcut that opens the web pages of all the *unread* articles inside a feed or a folder in different tabs. Is this right?

**Comment by stormsh** [comment]
@cosenal Yes this is correct. A keyboardshortcut or an entry in the little pop up menu which every feed and folder provides. Either is fine, both would be awesome.
Unread articles and if possible starred as well. And if the "Open tab in Background" feature is implemented, the user can choose to open the unread or starred articles in background tabs or with the first unread article in a focused tab (since only one tab can have the focus of course).
@BernhardPosselt sry for the insufficient description...

**Comment by BernhardPosselt** [comment]
Ah, I see, yep, totally misunderstood it. I thought you wanted to open folders/feeds in new browser tabs.

The implementation for that one is a bit tricky however:
* We probably want a popup if there are more than 10 unread articles, otherwise opening 50+ tabs might crash the browser/system because of RAM issues
* Because we load articles lazily, we need to fetch all the remaining articles. To keep it simple we should probably create a new request to the server to fetch all unread articles and open those ones, then mark them read at once and also update the articles that are available locally.

**Comment by BernhardPosselt** [comment]
I'm fine with the proposed shortcuts btw.

**Comment by cosenal** [comment]
Btw, I commented to clarify the issue, it doesn't mean I support the suggestion :)

If you are opening all the articles (ok, *unread* articles, but still) of a feed, you may as well open the website corresponding to the full feed. I would freak out if I saw tens of tabs popping up in my browser after clicking a key. Maybe »Shift+o« should open the website corresponding to the feed you're looking at (a bit like »Original« mode in Newsblur).

**Comment by stormsh** [comment]
@BernhardPosselt Sounds great. The warning for the tabs is a good idea. I work with a lot of tabs every day and firefox starts having problems at 150+ tabs. Chrome is a bit better because it uses one process for each tab. But more than 250+ tabs is critical as well because, as you mentioned, the system ram should be considered. Maybe an option to deactivate the warning would surve both sides, with opt out, so the warning pops up by default.
:+1:

**Comment by BernhardPosselt** [comment]
I've tried this one out and opening more than 5 new tabs takes a massive toll on the browser speed and actually tricks you into hitting the shortcut again. Therefore this is capped at 5. Shortcut is shift + o and will open the next 5 unread articles in new tabs.

**Comment by BernhardPosselt** [comment]
@stormsh can you check the latest master? I've tried to use this feature a bit and it feels a bit useless

**Comment by BernhardPosselt** [comment]
After using it a bit I'd actually favor to remove it again xD

**Comment by BernhardPosselt** [comment]
Yep, reverted this feature. It is now in the open-five branch https://github.com/owncloud/news/tree/open-five if you want to test it out.

**Comment by stormsh** [comment]
Well, it's your app. If you feel like to remove it again, then preceed.

Anyone useing a feature that is able to open 50+ tabs at the same time should expect that it takes a minute or two to open and load them all.
But even just 5 is still 80% less klicking, so I would at least like to try it.

**Comment by BernhardPosselt** [comment]
Yep, try the branch and see how it works for you. If you think this is an awesome addition that you can't live without and/or want to gear up the count, I'd actually prefer this to be in a plugin. The JS code for this should basically amount to this (there could be errors in this, not tested):

```js
$(document).ready(function () {
    var openAllUnread = function () {
        var unreadItems = $('#app-content').find('.item:not(.read)');
        // only open a maximum of 10 new tabs
        var tabsToOpenNumber = 5;
        unreadItems.slice(0, tabsToOpenNumber).each(function (index, element) {
            var url = $(element)
                    .find('.external:visible')
                    .attr('href');
            $(element).trigger('click');  // mark read
            window.open(url, '_blank');
        });
    };

    var noInputFocused = function (element) {
        return !(
                element.is('input') ||
                element.is('select') ||
                element.is('textarea') ||
                element.is('checkbox')
        );
    };

    $(document).keyup(function (event) {
        // shift + o
        if (noInputFocused($(':focus')) &&
                event.shiftKey &&
                [81].indexOf(event.keyCode)) {
            openAllUnread();
        }
    });
});
```

Here's how to write plugins https://github.com/owncloud/news/wiki/How-to-write-Plugins#clientside-plugin

PS: 50+ tabs can not be opened at the same time since the app autopages by 20 with 40 initial ones ;D You'd have to work around the current web interface.

**Comment by stormsh** [comment]
This is a nice examble of user expectation, developer knowledge and user experience. Don't get me wrong, I'm neither mad at you nor disappointed. It's just that I expect this to work totally different than you know it would in reality (eg the thing that it's up to 20 max because of the autopage cap at 20).
Unfortunately I am not capable of writing a plugin. I have no idea what to do, even after I read the how to at least 5 times.
I downloaded the open-five branch and uploaded everything and overwrote the files of the existing news app, but I don't see the option to open 5 tabs at once.
I was just so used to this feature from the FF plugin Newsfox, that I thought this would be used by more users. But since I seem to be the only one who wants this feature, it's not worth the work for you.
But thank you anyway that you tried :) :+1:

**Comment by BernhardPosselt** [comment]
I've added it to the plugins section in the wiki which is where I keep most of the request plugin ideas and guidelines in: https://github.com/owncloud/news/wiki#plugins

I've detailed how to create the basic stuff, basically you just need to create 3 text files: https://github.com/owncloud/news/wiki/open-all-unread-articles-shortcut

**Comment by stormsh** [comment]
Thank you very much. The manual is exactly what I needed and I got it to work. 
And I know now, why you didn't like it. It feels a bit odd. But hey, less clicking is less klicking non the less ;).
