### ISSUE TITLE
stuck to version 5.2.8

### ISSUE THREAD

**Issue by awikatchikaen** [owncloud/news#851]
Hi,

Owncloud  8.1.1 doesn't propose to update the news app. I'm still on 5.2.8 

Thank you

**Comment by BernhardPosselt** [comment]
Are you on PHP 5.5+?

Also please reopen in core if you are

**Comment by awikatchikaen** [comment]
I'm on php 5.6.
I have open an issue on core : https://github.com/owncloud/core/issues/18884
