### ISSUE TITLE
compact view unusable on iOS

### ISSUE THREAD

**Issue by tflidd** [owncloud/news#852]
Safari on iOS 8.4
News: 6.0.3
Owncloud: 8.1.1

screenshot: 
![preview](https://cloud.githubusercontent.com/assets/8111200/9719072/80cea174-5581-11e5-91cd-1d02fb3c6593.png)

**Comment by BernhardPosselt** [comment]
Yep, Safari is unsupported, see the README/CONTRIBUTING.md ;D

Use the iOS app instead https://itunes.apple.com/de/app/cloudnews-owncloud-news-reader/id683859706?mt=8

**Comment by tflidd** [comment]
@BernhardPosselt Sorry, I didn't read that. But then opera-mini or chrome should work but they don't:
Opera mini:
![preview](https://cloud.githubusercontent.com/assets/8111200/9719353/c78a33c4-5583-11e5-95fc-dfaaf65c3ef0.png)
Chrome (loads very very slowly):
![preview2](https://cloud.githubusercontent.com/assets/8111200/9719354/ca54ef54-5583-11e5-8787-516e47af2fe5.png)

**Comment by BernhardPosselt** [comment]
Yes, that's because apple does not allow another browser engine on iOS, so every other browser uses a slower version of the safari engine ;)

**Comment by tflidd** [comment]
Ok. I see the problem. I don't want to install so many apps (and pay without testing them before) for things that should run properly on a browser. So I'll look for a possibility to debug this css-stuff on a desktop computer.

**Comment by BernhardPosselt** [comment]
The issue here is that safari does not support flexbox properly yet
