### ISSUE TITLE
Add daily or weekly summary by mail

### ISSUE THREAD

**Issue by fulljackz** [owncloud/news#853]
Hi,
For those (like me) which does not check their news apps all the day, it would be cool to add a mail summary functionnality, daily or weekly.

I will give it a try if I find some time.

Cheers,

**Comment by BernhardPosselt** [comment]
Hi, 

thanks for the suggestion. I personally think there are various problems with the idea and solution in ownCloud itself:
* Which articles should be suggested? Random ones? Isn't it better to just take a quick peak into the webinterface then? I doubt there is any value in just random news articles. Online platforms like Feedly can analyze what most people read and give you suggestions based on those. This approach however won't work well in ownCloud.
* You usually don't want communication and news bundled together. This would be some kind of newsletter and people don't usually read those
* I'm unsure if a feature that covers people that don't use the app is an often used one. This probably applies to very niche of readers only.
* Lastly, this is more of a backend standalone plugin feature. If you think the feature is important and you want to work on it, I'd suggest to create a plugin like this one https://github.com/BernhardPosselt/feedcentral which basically lets you edit some settings and reuses the News database/tables.

**Comment by BernhardPosselt** [comment]
PS: if you need help with the plugin, let me know ;)
