### ISSUE TITLE
Always »Token expired« on Chrome on iOS 

### ISSUE THREAD

**Issue by cosenal** [owncloud/news#854]
I was trying to reproduce #852 on Chrome on iOS and whenever I open the app, I get the »Token expired or app not enabled!« message. Reloading the page doesn't help. This is on core master + news master.

**Comment by BernhardPosselt** [comment]
Please reopen in core :)

Let's search for possible solutions there

**Comment by BernhardPosselt** [comment]
BTW: Chrome on iOS also uses Safari, everything on iOS uses Safari (which we don't support)

This is a different issue though I think.
