### ISSUE TITLE
Application breakes Owncloud

### ISSUE THREAD

**Issue by pganuza** [owncloud/news#855]
Hello.

Since latest updates whenever I activate News I can't access my Owncloud instance anymore, i just get a blank page until I delete /var/www/owncloud/apps/news/

Here is the log at /var/www/owncloud/data/owncloud.log:
{"reqId":"+5mjCXrIRbsZaXMTVNvM","remoteAddr":"195.76.142.134","app":"PHP","message":"syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' at \/var\/www\/owncloud\/apps\/news\/appinfo\/application.php#56","level":3,"time":"2015-09-09T11:32:50+00:00"}

**Comment by BernhardPosselt** [comment]
dup of #838
