### ISSUE TITLE
Allow embedded YouTube videos to be shown in fullscreen

### ISSUE THREAD

**Issue by jonas-koeritz** [owncloud/news#857]
Currently the "allowfullscreen" attribute is filtered from the iframe tag. This prevents the YouTube HTML5 player from going fullscreen (the fullscreen button is disabled).

There should be a configuration option to pass or enforce (if the feed did not provide it) this attribute.
Maybe this should even be enabled by default.
![youtube no fullscreen](https://cloud.githubusercontent.com/assets/6485387/9817075/2077cddc-58a1-11e5-9303-e5cf238c875d.png)

**Comment by qezzo** [comment]
+1

**Comment by BernhardPosselt** [comment]
PicoFeed Attribute filter needs to be updated https://github.com/fguillot/picoFeed/blob/master/lib/PicoFeed/Filter/Attribute.php and the attribute should be whitelisted for iframes in HtmlPurifier https://github.com/owncloud/news/blob/master/appinfo/application.php#L114 

We need to make sure that no additional holes get ripped open in terms of HtmlPurifier

As for PicoFeed, we need another issue there, can you open one @jonas-koeritz ?

**Comment by jonas-koeritz** [comment]
I will add an issue there and refer to this one.

Bernhard Posselt <notifications@github.com> schrieb am Fr., 11. Sep. 2015
20:27:

**Comment by jonas-koeritz** [comment]
picoFeed issue is opened.
Reference: fguillot/picoFeed#192

**Comment by BernhardPosselt** [comment]
PicoFeed issue is resolved, all that's left is the correct HTMLPurifier setting where I'm currently stuck at https://github.com/owncloud/news/blob/master/appinfo/application.php#L114

If you find the time, please take a look ;)

**Comment by jonas-koeritz** [comment]
This might be a push in the right direction. I tried this the first time
but had the picoFeed changes wrong so nothing happened.

http://stackoverflow.com/questions/4464004/htmlpurifier-custom-attributes

**Comment by BernhardPosselt** [comment]
Yep, tried that already, stuck here: http://htmlpurifier.org/phorum/read.php?3,7462,7812#msg-7812

**Comment by BernhardPosselt** [comment]
The issue being basically that adding anything to allowed iframe attributes completely whipes all other attributes on it
