### ISSUE TITLE
Last version suporting PHP 5.4 does not work on ownCloud 8.1.1

### ISSUE THREAD

**Issue by M4rtinK** [owncloud/news#858]
Since the 6.x series dropped PHP 5.4 support (and thus suport for running on enterprise distros and their derivatives such as RHEL 7 and CentOS 7) I have been trying to get an older PHP 5.4 supporting version of news installed to my ownCloud 8.1.1 deployment running on CentOS 7.

But news version 5.3.9, which is as far as I can tell the last version of notes with PHP 5.4 support, does not work on ownCloud 8.1 (running on CentOS 7):

- the app fails to load
- data/owncloud.log is full of error messages like this one:

`
{"reqId":"VfbCmuOtAS6q4Z2FJ0EJfQAAAAA","remoteAddr":"192.168.1.150","app":"index","message":"Exception: {\"Exception\":\"BadFunctionCallException\",\"Message\":\"fullTextEnabled is not a valid attribute\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(145): OCP\\\\AppFramework\\\\Db\\\\Entity->setter('fullTextEnabled', Array)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(69): OCP\\\\AppFramework\\\\Db\\\\Entity->__call('setFullTextEnab...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(69): OCA\\\\News\\\\Db\\\\Feed->setFullTextEnabled('0')\\n#3 [internal function]: OCP\\\\AppFramework\\\\Db\\\\Entity::fromRow(Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(305): call_user_func('\\\\OCA\\\\News\\\\Db\\\\Fe...', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(324): OCP\\\\AppFramework\\\\Db\\\\Mapper->mapRowToEntity(Array)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/news\\\/db\\\/feedmapper.php(77): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntities('SELECT `feeds`....', Array)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/news\\\/service\\\/feedservice.php(76): OCA\\\\News\\\\Db\\\\FeedMapper->findAllFromUser('admin')\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/news\\\/controller\\\/feedcontroller.php(64): OCA\\\\News\\\\Service\\\\FeedService->findAll('admin')\\n#9 [internal function]: OCA\\\\News\\\\Controller\\\\FeedController->index()\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\News\\\\Controller\\\\FeedController), 'index')\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\News\\\\Controller\\\\FeedController), 'index')\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('FeedController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#16 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(873): OC\\\\Route\\\\Router->match('\\\/apps\\\/news\\\/feed...')\\n#17 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php\",\"Line\":114}","level":4,"time":"2015-09-14T12:50:35+00:00"}
`
I've also tried various older versions up to 5.2.x and all died with the same error message.

Please let me know if there is anything else I should try or additional log output, etc. I can provide. :)

**Comment by BernhardPosselt** [comment]
You also need to delete the migrated db tables, remove the full_text_enabled column from oc_news_feeds
