### ISSUE TITLE
MathJax support

### ISSUE THREAD

**Issue by cosenal** [owncloud/news#859]
Some math blogs use [MathJax](https://www.mathjax.org/) to display mathematical formulas. It would be cool if this behavior was mirrored by our reader.

The options are:
 1. Enable mathjax for all feeds
 2. Introduce an option to toggle mathjax support
 3. (dunno if possible) Automatically detect feeds corresponding to website that support mathjax. 

Example of blog with mathjax formulas: http://www.scottaaronson.com/blog/?p=2464

**Comment by BernhardPosselt** [comment]
Unfortunately this requires us to whitelist script tags which is not possible due to XSS ;)

There's no workaround for this

**Comment by cosenal** [comment]
Why so? The way it works is you load Mathjax in the beginning and then mathjax snippet are detectable from the format $$ ... $$ (same notation as LaTeX).

**Comment by BernhardPosselt** [comment]
Well that depends on your configuration :)

**Comment by cosenal** [comment]
hmm, damn, I didn't know you could configure the format...

**Comment by cosenal** [comment]
(from discussion on IRC) solution is to use some mathml polyfill libs to render only feeds that support mathml
