### ISSUE TITLE
PHP syntax error

### ISSUE THREAD

**Issue by MarekK82** [owncloud/news#860]
Recently I deployed _ownCloud 8.1.1 (stable)_ through my web provider (all-inkl.com).

```bash
$ uname -a
Linux dd34300 3.2.0-90-generic #128-Ubuntu SMP Fri Aug 14 21:43:58 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ php -v
PHP 5.4.42-nmm1 (cli) (built: Jun 17 2015 09:00:02) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
    with the ionCube PHP Loader v4.7.5, Copyright (c) 2002-2014, by ionCube Ltd.
```

It worked well until I enabled the official app _News (6.0.3)_. After that OC didn't work anymore due to a PHP syntax error:

```php
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /path/to/owncloud/apps/news/appinfo/application.php on line 56
```

The error was pointing on the following line:

```php
        $this->registerFactory(ItemMapper::class, MapperFactory::class);
```

Unfortunately I was unable to disable the app. Also the `occ` script ended with that same error. So I searched the web and found a SQL based solution to disable the app via its:

```sql
UPDATE `oc_appconfig` SET `configvalue` = 'no' WHERE `appid` LIKE 'news' AND `configkey` LIKE 'enabled'
```

Lucky me, it worked! However, I was wondering if no one else ran into this issue before?

**Comment by BernhardPosselt** [comment]
At least 5 previous reports like this one, please search the issue tracker next time ;D

**Comment by MarekK82** [comment]
Snap -.-
