### ISSUE TITLE
Add sorting/pinning info to client API

### ISSUE THREAD

**Issue by rakekniven** [owncloud/news#861]
Apps like iOS news reader cannot display feeds in same order as news app does due to missing API functions.
Latest pinning function #848 is pretty nice and now order of feeds look different in web UI and iOS UI.

Referring to comment at https://github.com/owncloud/news-iOS-App/issues/62

**Comment by BernhardPosselt** [comment]
Already implemented in 6.0.3, see https://github.com/owncloud/news/wiki/Feeds-1.2
