### ISSUE TITLE
Search issue with Firefox

### ISSUE THREAD

**Issue by mcmurphyrp** [owncloud/news#863]
Hi,

when I try to use the search box in the upper right corner with Firefox by either hitting enter or trying to click the magnifying glass, there is no action. Using Chrome browser the search works.

OC 8.1.3
News 6.04
Firefox 41
PHP 5.6.13-0+deb8u1
Raspbian GNU/Linux 7 (wheezy) 7.8

log:

#53","level":3,"time":"2015-09-30T14:45:42+00:00","method":"GET","url":"\/index.php\/apps\/news\/"}
{"reqId":"a+edV9gHs+Ynq98scXrh","remoteAddr":"1xx.xx.xxx.xxx","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2015-09-30T14:46:39+00:00","method":"POST","url":"\/index.php\/apps\/news\/items\/48657\/read"}

I also already set 'always_populate_raw_post_data' to '-1' in the php.ini

Thanks.

**Comment by BernhardPosselt** [comment]
Please read the Contributing.md and provide additional details.

**Comment by mcmurphyrp** [comment]
added to post

**Comment by BernhardPosselt** [comment]
Can reproduce on Firefox
