### ISSUE TITLE
API returns 500 server error if login fails

### ISSUE THREAD

**Issue by David-Development** [owncloud/news#864]
Maybe it's a misconfiguration of my server but I'm getting this exception when my credentials are wrong:
{"reqId":"3gxweZC\/Z7+5pkKdLXvY","remoteAddr":"24.138.62.194","app":"index","message":"Exception: {\"Exception\":\"OC\\\\AppFramework\\\\Middleware\\\\Security\\\\SecurityException\",\"Message\":\"CORS requires basic auth\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/middleware\\\/middlewaredispatcher.php(92): OC\\\\AppFramework\\\\Middleware\\\\Security\\\\CORSMiddleware->beforeController(Object(OCA\\\\News\\\\Controller\\\\UtilityApiController), 'version')\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(88): OC\\\\AppFramework\\\\Middleware\\\\MiddlewareDispatcher->beforeController(Object(OCA\\\\News\\\\Controller\\\\UtilityApiController), 'version')\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\News\\\\Controller\\\\UtilityApiController), 'version')\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('UtilityApiContr...', 'version', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#4 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(874): OC\\\\Route\\\\Router->match('\\\/apps\\\/news\\\/api\\\/...')\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/middleware\\\/security\\\/corsmiddleware.php\",\"Line\":86}","level":4,"time":"2015-09-30T22:56:24+00:00"}

And in the Android App I'm getting a 500 http status code. This makes it impossible for me to show the users a proper error message if the login fails.
I'm using version 6.0.4

**Comment by BernhardPosselt** [comment]
You are sending auth cookies which were disallowed because of csrf

**Comment by BernhardPosselt** [comment]
Recent change fyi

**Comment by BernhardPosselt** [comment]
The exception should be a 403 though, please open an issue in core

**Comment by David-Development** [comment]
Okay. We switched to another network lib since the last version. As far as I can see we don't send cookies (might be default). Anyways.. the response should be 403 though. Thanks!
