### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Forum-Fraggle** [owncloud/news#865]
Hi,

I guess it is better to write my problem here:

I am running Version 5.28 as my owncloud is 8.0.
After I updated my database of my synology system I can´t open news, or more correctly: It shows no news. The error message says to take a look into the log file.
Here is the anonymized content (only 2 lines, sorry for that long text):
{"reqId":"here was an ID","remoteAddr":"Here as an IP","app":"index","message":"Exception: {\"Message\":\"An exception occurred while executing 'SELECT `feeds`.*, COUNT(`items`.`id`) AS `unread_count` FROM `oc_news_feeds` `feeds` LEFT OUTER JOIN `oc_news_folders` `folders` ON `feeds`.`folder_id` = `folders`.`id` LEFT JOIN `oc_news_items` `items` ON `feeds`.`id` = `items`.`feed_id` AND (`items`.`status` & 2) = 2 WHERE `feeds`.`user_id` = ? AND (`feeds`.`folder_id` = 0 OR `folders`.`deleted_at` = 0)AND `feeds`.`deleted_at` = 0 GROUP BY `feeds`.`id`, `feeds`.`user_id`, `feeds`.`url_hash`,`feeds`.`url`, `feeds`.`title`, `feeds`.`link`,`feeds`.`favicon_link`, `feeds`.`added`, `feeds`.`articles_per_update`, `feeds`.`folder_id`, `feeds`.`prevent_update`, `feeds`.`deleted_at`' with params [\\\"genemorph\\\"]:\\n\\nSQLSTATE[HY001]: Memory allocation error: 1038 Out of sort memory, consider increasing server sort buffer size\",\"Code\":0,\"Trace\":\"#0 \\\/volume1\\\/web\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/volume1\\\/web\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(172): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `feeds`....', Array)\\n#2 \\\/volume1\\\/web\\\/owncloud\\\/lib\\\/private\\\/db\\\/statementwrapper.php(65): Doctrine\\\\DBAL\\\\Statement->execute()\\n#3 \\\/volume1\\\/web\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(213): OC_DB_StatementWrapper->execute()\\n#4 \\\/volume1\\\/web\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(266): OCP\\\\AppFramework\\\\Db\\\\Mapper->execute('SELECT `feeds`....', Array, NULL, NULL)\\n#5 \\\/volume1\\\/web\\\/owncloud\\\/apps\\\/news\\\/db\\\/feedmapper.php(77): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntities('SELECT `feeds`....', Array)\\n#6 \\\/volume1\\\/web\\\/owncloud\\\/apps\\\/news\\\/service\\\/feedservice.php(76): OCA\\\\News\\\\Db\\\\FeedMapper->findAllFromUser('genemorph')\\n#7 \\\/volume1\\\/web\\\/owncloud\\\/apps\\\/news\\\/controller\\\/feedcontroller.php(64): OCA\\\\News\\\\Service\\\\FeedService->findAll('genemorph')\\n#8 [internal function]: OCA\\\\News\\\\Controller\\\\FeedController->index()\\n#9 \\\/volume1\\\/web\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(158): call_user_func_array(Array, Array)\\n#10 \\\/volume1\\\/web\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(86): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\News\\\\Controller\\\\FeedController), 'index')\\n#11 \\\/volume1\\\/web\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(97): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\News\\\\Controller\\\\FeedController), 'index')\\n#12 \\\/volume1\\\/web\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(44): OC\\\\AppFramework\\\\App::main('FeedController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#13 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#14 \\\/volume1\\\/web\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#15 \\\/volume1\\\/web\\\/owncloud\\\/lib\\\/base.php(767): OC\\\\Route\\\\Router->match('\\\/apps\\\/news\\\/feed...')\\n#16 \\\/volume1\\\/web\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#17 {main}\",\"File\":\"\\\/volume1\\\/web\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":115}","level":4,"time":"2015-09-30T10:03:44+00:00"}
{"reqId":"here was an ID","remoteAddr":"Here as an IP","app":"index","message":"Exception: {\"Message\":\"An exception occurred while executing 'SELECT `feeds`.*, COUNT(`items`.`id`) AS `unread_count` FROM `oc_news_feeds` `feeds` LEFT OUTER JOIN `oc_news_folders` `folders` ON `feeds`.`folder_id` = `folders`.`id` LEFT JOIN `oc_news_items` `items` ON `feeds`.`id` = `items`.`feed_id` AND (`items`.`status` & 2) = 2 WHERE `feeds`.`user_id` = ? AND (`feeds`.`folder_id` = 0 OR `folders`.`deleted_at` = 0)AND `feeds`.`deleted_at` = 0 GROUP BY `feeds`.`id`, `feeds`.`user_id`, `feeds`.`url_hash`,`feeds`.`url`, `feeds`.`title`, `feeds`.`link`,`feeds`.`favicon_link`, `feeds`.`added`, `feeds`.`articles_per_update`, `feeds`.`folder_id`, `feeds`.`prevent_update`, `feeds`.`deleted_at`' with params [\\\"genemorph\\\"]:\\n\\nSQLSTATE[HY001]: Memory allocation error: 1038 Out of sort memory, consider increasing server sort buffer size\",\"Code\":0,\"Trace\":\"#0 \\\/volume1\\\/web\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/volume1\\\/web\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(172): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `feeds`....', Array)\\n#2 \\\/volume1\\\/web\\\/owncloud\\\/lib\\\/private\\\/db\\\/statementwrapper.php(65): Doctrine\\\\DBAL\\\\Statement->execute()\\n#3 \\\/volume1\\\/web\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(213): OC_DB_StatementWrapper->execute()\\n#4 \\\/volume1\\\/web\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(266): OCP\\\\AppFramework\\\\Db\\\\Mapper->execute('SELECT `feeds`....', Array, NULL, NULL)\\n#5 \\\/volume1\\\/web\\\/owncloud\\\/apps\\\/news\\\/db\\\/feedmapper.php(77): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntities('SELECT `feeds`....', Array)\\n#6 \\\/volume1\\\/web\\\/owncloud\\\/apps\\\/news\\\/service\\\/feedservice.php(76): OCA\\\\News\\\\Db\\\\FeedMapper->findAllFromUser('genemorph')\\n#7 \\\/volume1\\\/web\\\/owncloud\\\/apps\\\/news\\\/controller\\\/itemcontroller.php(93): OCA\\\\News\\\\Service\\\\FeedService->findAll('genemorph')\\n#8 [internal function]: OCA\\\\News\\\\Controller\\\\ItemController->index(3, NULL, 40, 0, false, false)\\n#9 \\\/volume1\\\/web\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(158): call_user_func_array(Array, Array)\\n#10 \\\/volume1\\\/web\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(86): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\News\\\\Controller\\\\ItemController), 'index')\\n#11 \\\/volume1\\\/web\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(97): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\News\\\\Controller\\\\ItemController), 'index')\\n#12 \\\/volume1\\\/web\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(44): OC\\\\AppFramework\\\\App::main('ItemController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#13 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#14 \\\/volume1\\\/web\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#15 \\\/volume1\\\/web\\\/owncloud\\\/lib\\\/base.php(767): OC\\\\Route\\\\Router->match('\\\/apps\\\/news\\\/item...')\\n#16 \\\/volume1\\\/web\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#17 {main}\",\"File\":\"\\\/volume1\\\/web\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":115}","level":4,"time":"2015-09-30T10:03:47+00:00"}

What can I do to get a running version again? Thanks for your help.

**Comment by BernhardPosselt** [comment]
Google this:

    Memory allocation error: 1038 Out of sort memory

Turns up this ;) http://stackoverflow.com/questions/29575835/error-1038-out-of-sort-memory-consider-increasing-sort-buffer-size

**Comment by BernhardPosselt** [comment]
And here https://dev.mysql.com/doc/refman/5.5/en/server-system-variables.html#sysvar_sort_buffer_size

**Comment by Forum-Fraggle** [comment]
Thanks for help, I will try this todays evening. At the moment I don´t have any database access.

**Comment by Forum-Fraggle** [comment]
Perfect, it works. Thanks for your fast help.
