### ISSUE TITLE
Articles not being marked read when importing articles.json

### ISSUE THREAD

**Issue by Bugsbane** [owncloud/news#867]
I just read all articles in news, exported subscriptions.opml and articles.json via the news app settings panel, and then deactivated the app, wiped the database settings, imported subuscriptions.opml and then imported articles.json (admittedly while feeds were still loading).

When I did, my subscriptions and starred articles were successfully imported, but all feeds articles were left marked as unread.

I tried reimporting articles.json through the news settings pane button a couple more times once the feeds had finished refreshing, but it didn't change the read status of any of them. There are no relevant looking errors in the owncloud log.

ownCloud 8.1.3
News 6.0.4

**Comment by BernhardPosselt** [comment]
Relevant code is here https://github.com/owncloud/news/blob/master/service/feedservice.php#L299

**Comment by BernhardPosselt** [comment]
Closing this because of a misunderstanding (after another read through): Only unread and starred articles will be exported, otherwise the exported file would become massive.

**Comment by BernhardPosselt** [comment]
PS: all other solutions would cause data loss or would be incomplete ;)
