### ISSUE TITLE
Feeds not updating

### ISSUE THREAD

**Issue by yellowcow1100** [owncloud/news#868]
Running Owncloud 8.1.3 and News App 6.0.5 on a Synology Server.
![2015-10-11_20-22-14](https://cloud.githubusercontent.com/assets/11228637/10418251/247cb4fc-7056-11e5-9b3b-9e64d480a01f.png)

Even it states in the admin section of Owncloud that the Cron had run, I don't trust the setting I've done on the Synology.

You state the following: Check if the cronjob is ever executed by placing an error_log('updating') in the background job file. If the cronjob runs, there should be an updating log statement in your httpd log.

Can you tell me how/where to place error_log('updating') in the file? I simply don't know and I really want to find out where the problem is.

**Comment by BernhardPosselt** [comment]
Go to the News admin settings and check if **Use ownCloud cron for updates** is checked
![screen shot 2015-10-14 at 15 46 36 2](https://cloud.githubusercontent.com/assets/195053/10485514/e98270b2-728a-11e5-8750-458811bd498c.png)

**Comment by yellowcow1100** [comment]
It is and always was.
![2015-10-16_19-06-12](https://cloud.githubusercontent.com/assets/11228637/10548147/13f3ca80-7439-11e5-8558-b65094854eb2.png)

**Comment by BernhardPosselt** [comment]
Logs? Are you running php 5.5?

**Comment by yellowcow1100** [comment]
Yes.
![2015-10-16_19-17-45](https://cloud.githubusercontent.com/assets/11228637/10548480/5f423740-743b-11e5-85c7-b3e00cb0469c.png)

{"reqId":"nlA4RsRaRoNP6N2yboCt","remoteAddr":"192.168.1.1","app":"index","message":"Exception: {\"Exception\":\"OC\\\\AppFramework\\\\Middleware\\\\Security\\\\SecurityException\",\"Message\":\"CORS requires basic auth\",\"Code\":0,\"Trace\":\"#0 \\\/volume1\\\/web\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/middleware\\\/middlewaredispatcher.php(92): OC\\\\AppFramework\\\\Middleware\\\\Security\\\\CORSMiddleware->beforeController(Object(OCA\\\\News\\\\Controller\\\\FeedApiController), 'index')\\n#1 \\\/volume1\\\/web\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(88): OC\\\\AppFramework\\\\Middleware\\\\MiddlewareDispatcher->beforeController(Object(OCA\\\\News\\\\Controller\\\\FeedApiController), 'index')\\n#2 \\\/volume1\\\/web\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\News\\\\Controller\\\\FeedApiController), 'index')\\n#3 \\\/volume1\\\/web\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('FeedApiControll...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#4 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#5 \\\/volume1\\\/web\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#6 \\\/volume1\\\/web\\\/owncloud\\\/lib\\\/base.php(874): OC\\\\Route\\\\Router->match('\\\/apps\\\/news\\\/api\\\/...')\\n#7 \\\/volume1\\\/web\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#8 {main}\",\"File\":\"\\\/volume1\\\/web\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/middleware\\\/security\\\/corsmiddleware.php\",\"Line\":86}","level":4,"time":"2015-09-22T03:08:32+00:00"}
{"reqId":"1\/Ad7vr6la4uubURLfDJ","remoteAddr":"144.85.227.226","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/volume1\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/volume1\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/volume1\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/volume1\\\/web\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/volume1\\\/web\\\/owncloud\\\/remote.php(132): require_once('\\\/volume1\\\/web\\\/ow...')\\n#6 {main}\",\"File\":\"\\\/volume1\\\/web\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/maintenanceplugin.php\",\"Line\":83}","level":4,"time":"2015-09-22T11:56:07+00:00"}
{"reqId":"BRgNzCYKYCnZMC1LPmdP","remoteAddr":"192.168.1.1","app":"remote","message":"Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory","level":4,"time":"2015-10-01T20:47:48+00:00"}
{"reqId":"EDWehWSRH70ZfdnjUNjL","remoteAddr":"62.157.215.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/volume1\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/volume1\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/volume1\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/volume1\\\/web\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/volume1\\\/web\\\/owncloud\\\/remote.php(132): require_once('\\\/volume1\\\/web\\\/ow...')\\n#6 {main}\",\"File\":\"\\\/volume1\\\/web\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/maintenanceplugin.php\",\"Line\":83}","level":4,"time":"2015-10-05T06:27:35+00:00"}
{"reqId":"d5gXU1+uiO7IdE+wLFsq","remoteAddr":"144.85.134.203","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/volume1\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/volume1\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/volume1\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/volume1\\\/web\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/volume1\\\/web\\\/owncloud\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/volume1\\\/web\\\/owncloud\\\/remote.php\",\"Line\":55}","level":4,"time":"2015-10-05T06:27:55+00:00"}
{"reqId":"e\/9YO7LSKddBj2xkZ51p","remoteAddr":"192.168.1.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/volume1\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/volume1\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/volume1\\\/web\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/volume1\\\/web\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/volume1\\\/web\\\/owncloud\\\/remote.php(132): require_once('\\\/volume1\\\/web\\\/ow...')\\n#6 {main}\",\"File\":\"\\\/volume1\\\/web\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/maintenanceplugin.php\",\"Line\":83}","level":4,"time":"2015-10-11T17:43:55+00:00"}

**Comment by BernhardPosselt** [comment]
Can the web server change into all news directories? (+x)

**Comment by yellowcow1100** [comment]
I think so. I did "chown -R http:http /volume1/web/owncloud".

**Comment by yellowcow1100** [comment]
![2015-10-17_14-01-19](https://cloud.githubusercontent.com/assets/11228637/10558677/0da4f186-74d9-11e5-8a66-ed6478fc656b.png)

**Comment by BernhardPosselt** [comment]
As for the error_log: place it inside this block: https://github.com/owncloud/news/blob/master/cron/updater.php#L31

Can you try to run the cron manually to check if things are updated? To do that run:

    sudo -u http php -f /path/to/owncloud/cron.php

**Comment by yellowcow1100** [comment]
Sorry, but I need more help with placing the error_log('updating').
Can tell me exactly where I need to place it or creat a scrennshot? "Inside this block" is not helping me enough. I'm stuck at this spot from the beginning...

But I also found out that I was following a ghost with the working cron updates. I turned off the cron jobs on the Synology server and Owncloud still showed cron updates. Then I found out that "old" webcrons were still running and still updating OC even the option was not choosen. Now they're dead and OC is not showing updates anymore.

So I'm getting closer to isolate the problem to its core.
My assumption is that the internal cron job of the Synology server is not running as it should. But I would need the help from you about how to place the error_log('updating'). Once this is done, I think I can handle the problem by myself.

**Comment by yellowcow1100** [comment]
I could not rest and now I solved it. It was the synology cron, as I assumed. 

Here is the correct cron setting for the synology server (DSM 5.2-5592 Update 4):
*/5     *       *       *       *       root    /bin/su -s /bin/sh -c "/usr/bin/php -f /volume1/web/owncloud/cron.php" http

The main issue is that it has to be run as root user, but executed as the http user. If anybody wants to know what's happening with this script, read here --> https://forum.owncloud.org/viewtopic.php?f=31&t=28823

It is important not to use the "Cronjob editor". The cronjob can not be added there, since the editor can not cope with the "complicated" syntax. 
You need to open etc/crontab with the vi editor and to enter the lines above. Then restart the cronjob with "/usr/syno/sbin/synoservicectl --restart crond".

Thanks again for your support and the great app you created. The news app is for me the reason why I'm using Owncloud. Next to host the data on my own server of course ;-)
