### ISSUE TITLE
Add ability to use "add to oC News" bookmarklet

### ISSUE THREAD

**Issue by sndrsk** [owncloud/news#871]
Enhancement request: add the capability to add a bookmarklet to browser bookmark bars to add a feed to oC News directly from an open webpage. Example: while at https://owncloud.org/news/, clicking the JavaScript bookmarklet will open up the oC News instance (requiring login if necessary) with the subscribe field pre-filled with the feed address (detected in the page's head, `<link rel="alternate" type="application/rss+xml" title="ownCloud.org Feed" href="https://owncloud.org/feed/">`) and allowing the user to specify a folder to put it into, and then subscribe. This would bring oC News feature parity with other feed readers such as Tiny Tiny RSS.

**Comment by BernhardPosselt** [comment]
This is already implemented, just append ?subscribe_to=https://the feed.com

We already register the app as feed reader in your browser so a generic browser add-on should work fine e.g. https://chrome.google.com/webstore/detail/rss-subscription-extensio/nlbjncdgjeocebhnmkbbbdekmmmcbfjd?hl=de

**Comment by cosenal** [comment]
@sndrsk For your curiosity, see previous discussion on the bookmarklet: https://github.com/owncloud/news/issues/48
