### ISSUE TITLE
Cron Execution fails

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/news#872]
Hi,

i'm using OC 8.1.3 with News 6.0.5. If i set my System-Cron-Job i get every time it executes the following error:
```syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' at /var/www/xxxxx/owncloud/apps/news/appinfo/application.php#56```
The execution cancels and so i'm unable to read my news ;) any ideas?

**Comment by BernhardPosselt** [comment]
Search the bug tracker ;)

PHP 5.5 is required

**Comment by stefan-niedermann** [comment]
phpinfo() says "5.6.14".
![screenshot](https://cloud.githubusercontent.com/assets/4741199/10741955/d6b2bd08-7c2a-11e5-9c4d-c9eb478ca25f.png)

Happens with 5.5 too

**Comment by LukasReschke** [comment]
You're probably running another PHP version on CLI.

**Comment by stefan-niedermann** [comment]
thank you for the hint, i will contact the administrator of my sharedhoster.
