### ISSUE TITLE
Notification of new news

### ISSUE THREAD

**Issue by vonTrips** [owncloud/news#873]
After feeds updating, can menu icon show number of new item? Like as facebook with messages or notices.

I use DIRECT MENU plugin.

**Comment by BernhardPosselt** [comment]
You see the number of unread items to the right of the feed name

**Comment by BernhardPosselt** [comment]
Ah I see, there is no API for this, so we can't implement this. We use the tab title for displaying unread articles.

You can use this chrome extension BTW: https://chrome.google.com/webstore/detail/owncloud-news-checker/hnmagnmdnfdhabdlicankfbfhcdgbfhe

**Comment by vonTrips** [comment]
Thanks.

**Comment by ele0s** [comment]
Hi,

Maybe you can use the notifications system include in some OS/Browser like Chrome ?
Or implement this through the Owncloud notification system ?

**Comment by BernhardPosselt** [comment]
There is a chrome extension that shows the unread count
