### ISSUE TITLE
Scrolling video not working

### ISSUE THREAD

**Issue by szewczyk-it** [owncloud/news#875]
Video scrolling not working on Windows on browsers: Chrome, Firefox, Opera. Just works on MS Edge (OMG!). I tested it on Windows 8 and Windows 10 and nevest ownCloud (8.1.3-13.1) with default "Video Viewer" and "VideoJS Sublime" app.

**Comment by BernhardPosselt** [comment]
What is video scrolling?

**Comment by szewczyk-it** [comment]
Here is what I have in mind:
https://youtu.be/3w8J9Q-Tp-s

**Comment by BernhardPosselt** [comment]
Hm, can't reproduce on Mac OS X and Linux. I can click on any position inside an HTML5 video and it just works.

Can you explain what default "Video Viewer" and "VideoJS Sublime" app is exactly?

**Comment by szewczyk-it** [comment]
VideoJS Sublime: https://apps.owncloud.com/content/show.php/VideoJS+Sublime?content=173993

and "Video Viewer" like on the attachment
<img width="198" alt="vv" src="https://cloud.githubusercontent.com/assets/10866688/10574958/91e8002e-7659-11e5-8101-5460d7530786.PNG">

**Comment by szewczyk-it** [comment]
When I turned off above applications, after click on position with mp4 video, browser asks me to save clicked file.

**Comment by BernhardPosselt** [comment]
Yes, your browser does not support mp4 then, this is a browser codec issue. The video app is also new to me and we definitely don't support it in any combination, closing hence.

**Comment by szewczyk-it** [comment]
OK :)
