### ISSUE TITLE
Allow rating articles

### ISSUE THREAD

**Issue by djibux** [owncloud/news#876]
Hello,

I currently have around 100 feeds and would like to delete a few.  A rating system for articles would help me a lot.

Use case:
* when reading articles I have an optional mechanism to rate articles
* when hovering a feed, I get a summary of the feed letting me know how much I have enjoyed the articles
* I can delete feeds using those statistics

I see a potential non-intrusive implementations using thumbs-up and thumbs-down:
* Each article can be given an optional thumbs-up or thumbs-down:
* The feed summary would display something like: 134 articles, 27 :+1: (20%), 3 :-1: (2%)

What do you think?

**Comment by BernhardPosselt** [comment]
From my POV this is a very edge case scenario that is hard to get right. 

The main issue I see here is that statistics only work, if you keep all articles in the database. This however adds up to enourmous amounts of "useless" articles and can cause performance and storage issues (especially if you have more than one user).

So basically this feature can only work properly by scraping cleanup which is not an option. 

The second issue here is that it imposes a lot of work onto you. You need to manually upvote/downvote all articles in order to get the statistics right. This seems to be more work than actually reading and simply deleting the feed ;)

**Comment by BernhardPosselt** [comment]
I think one of the basic issues that you've got is dealing with a huge amount of feeds which have a lot of "background noise" aka articles that don't interest you. A solution for this is feed filters, take a look at http://readwrite.com/2008/03/04/6_ways_to_filter_your_rss_feeds

**Comment by cosenal** [comment]
I agree that from the usability point of view is not a great feature.
Implementation-wise, I don't agree that you need to keep all articles in the database, you could just keep a counter of Liked/Total in the feed table. 

Maybe one simpler solution would be to somehow "highlight" feeds that have a lot of starred articles.

**Comment by djibux** [comment]
Personally I use starred articles for articles I want to read in the future, not for articles I liked or I want to keep.

@BernhardPosselt I'm not saying the user needs to vote on all articles, just like on social media you probably don't “like” every single post.  Keeping the articles that have been thumbed-up makes sense to me.

Thanks for the link about filters.

**Comment by BernhardPosselt** [comment]
If articles are read and not starred they will be deleted, so you need to star articles that you want to keep. And I guess you want to read starred articles in the future, so basically it's the same thing.

**Comment by djibux** [comment]
Well, not quite to me :)  In tools like TTRSS you can star and you can archive.  I like having the two features.  I star articles to read them later, then archive them if I liked them.  I don't know how to reproduce that feature in Owncloud News.

**Comment by BernhardPosselt** [comment]
Thats because it's the same in ownCloud News ;) 

* Star 1 article to read it later
* Unstar it if you don't like it

**Comment by djibux** [comment]
I guess that would work but I would need to keep articles I want to read later as “unread” (to differentiate from articles I have already read and kept as favourites).  That means disabling auto-read when scrolling and doesn't feel very robust to me…  But maybe I am missing something.

**Comment by BernhardPosselt** [comment]
My usual workflow is like this: 
* I scroll through the articles and star the interesting ones (if I dont have enough time mostly)
* Later on, I go to the starred section and unstar the ones that I've read and did not want to keep

There's also another feature that you can use for keeping stuff unread: If you hit the mark unread button (the eye, or its shortcut **u**), it won't be marked read when you scroll down. If you load a new feed, articles will be marked read again through scrolling.

**Comment by djibux** [comment]
I see…  How do you differentiate between starred articles you haven't read and starred articles you have?  It looks like you might have to scroll through a bunch of starred articles before finding one you need to read.

**Comment by BernhardPosselt** [comment]
The ones that I've already are at the bottom. Once I hit an article that I already know I just stop.

**Comment by djibux** [comment]
I'll try that but I am quite sceptic.
I will need to read starred articles from the bottom up.  Otherwise, if I have 20 starred articles (the first 10 being articles I have yet to read) and I read only the first two, I will end up with: 2 read, 8 unread, and then again 10 read…  It will be a nightmare…

Would you be willing to accept a PR with thumbs-up if I find the time to dig into that, or will you reject the feature?

**Comment by BernhardPosselt** [comment]
First try if my propsed workflow works good enough. If you've got big problems with it I'd say lets talk about the exact issue in another thread (starred/archived/read later distinction).

Please don't write any code beforehand, if needed let's get the basics done first.

**Comment by djibux** [comment]
OK that sounds goods.  Thanks for your help.
