### ISSUE TITLE
https / http mixed results woes

### ISSUE THREAD

**Issue by aquaherd** [owncloud/news#885]
It is foreseeable that owncloud installations will be most likely behind https. In the near future, web browsers might treat mixed https / http pages as compromised. Therefore, the 3rd party stuff in news reader previews like favicons, images and videos need to be either blockable or cacheable behind https URLs.

**Comment by BernhardPosselt** [comment]
Active mixed content is blocked completely

The only thing left is passive mixed content which has to be fixed by the feed providers. Worst case scenario here is that someone MITMs you a different picture/video/audio. 

Putting this behind a "cacheable https" proxy or downloading them adds zero security benefit. The attacker can just MITM the proxy.

**Comment by BernhardPosselt** [comment]
Even worse downloading them and serving them from the same domain opens you up to xss attacks ;)

**Comment by aquaherd** [comment]
How about adding an option to block all passive mixed content, then?

**Comment by BernhardPosselt** [comment]
Why? That's basically turning your feeds into text only feeds and the attack scenario is only about swapping out images/audio/video.

**Comment by BernhardPosselt** [comment]
And its MITM which is hard to do unless someone targets you

**Comment by aquaherd** [comment]
I can't really say why not. Consider this was an e-mail plug-in. If blocking external images in the preview window was missing, would you actually use it?

**Comment by BernhardPosselt** [comment]
The e-mail thing is an entirely different story: external media is not loaded because of mixed content but in order to prevent spammers from verifying your address by simply opening a mail ;)

**Comment by CannyFoxx** [comment]
I'm not a PHP-developer, but I think that using php possible to proxy requests, beginning with "http". Yes, this is a high load on a network channel. This setting can make optional

**Comment by BernhardPosselt** [comment]
Like mentioned above this only silences the error and does not get rid of the security "issue"
