### ISSUE TITLE
OC 8.1.4 + News 5.3.9 = error

### ISSUE THREAD

**Issue by t0mcat1337** [owncloud/news#890]
Hi everybody,

just installed OC 8.1.4 and wanted to install News Vers. 5.3.9 (the server is an Univention Corporate Server which just includes PHP 5.4, therefore it's not possible to use News 6.1.1). 
News is obviously correctly installed but there is no news icon in the Menu. In owncloud.log this can be read:

require(): Cannot redeclare class oca\news\appinfo\application at /var/www/owncloud/lib/private/app.php#389

Any hint?

**Comment by BernhardPosselt** [comment]
You've got a duplicate news folder lying around

**Comment by t0mcat1337** [comment]
Nope, doing a "find...." in the compete owncloud directory just gives the fresh "news" folder in OCs app directory...

**Comment by BernhardPosselt** [comment]
Try:

    find owncloudDirectory -name "*news/appinfo/application.php"

**Comment by BernhardPosselt** [comment]
And maybe clear your php cache

**Comment by t0mcat1337** [comment]
Silly me.... right, I shorty activated APC in OC... clearing the cache helps, thx a lot for pushing me to the right direction :S
