### ISSUE TITLE
How to get rid of this error message?

### ISSUE THREAD

**Issue by under-score** [owncloud/news#893]
My setup works (mostly) while I can't get rid of this error message...

![sc](https://cloud.githubusercontent.com/assets/2796454/11393949/dfc738f2-9362-11e5-90f2-97ca490b4f72.jpg)

**Comment by BernhardPosselt** [comment]
Do exactly what the error message says: either activate the system cron in the admin interface or turn off cron updates for the news app by using a custom updater

**Comment by under-score** [comment]
thanks for responding so fast.

I have no access to the system cron. Unfortunately also with webcron the error message stays on top of the news page.

![sc](https://cloud.githubusercontent.com/assets/2796454/11394492/a081e6b2-9365-11e5-9706-fc8c3d18c3d8.jpg)

**Comment by BernhardPosselt** [comment]
In that case you need to set up the custom updater bundled with the app (click the link in the error message) and turn off cron updates for the news app. You can run the custom updater from any machine

**Comment by under-score** [comment]
As this is a hosted system, I have also no access to the bundled updater. Setting owncloud/data/news/config/config.ini
useCronUpdates = false
helped. Thanks!

**Comment by BernhardPosselt** [comment]
Yep, unfortunately you need a system with access to either the system cron or a vserver that is able to run the updates via the custom updater. All other methods don't work properly. My recommendation here is to get a better hosting or even better: get a vserver ;)

Closing this as solved.

**Comment by BernhardPosselt** [comment]
Just a hint: setting useCronUpdates to false is only the first step, you need to set up a custom updater on another machine

**Comment by MrksKwsnck** [comment]
I would appreciate a solution to turn off this message and keep using my flawlessly working WebCron very much.

**Comment by BernhardPosselt** [comment]
@MrksKwsnck Ajax cron can also work good enought (tm) for your installation but with severe downsides, same as with webcron. Both may lead to obscure bug reports which I want to prevent since my time is very limited. The warning is persistent on purpose, do not use webcron or ajax cron!

Should you really require a web based updating mechanism, please use the already mentioned python updater.

**Comment by MrksKwsnck** [comment]
I fully understand you. Unfortunately I also don't own a vserver but I am using a web hosting provider with very limited access/features. Therefore I am unable to run Python scripts.

For me two possible solution would be:
1.  Reimplementing the Python script in PHP or
2.  introducing a config flag to turn that message off.

**Comment by BernhardPosselt** [comment]
PHP won't work since it's killed by the webserver unfortunately that's why the updater is written in Python

**Comment by under-score** [comment]
I used css display none.Vom Mobiltelefon gesendet-------- Originalnachricht --------Betreff: Re: [news] How to get rid of this error message? (#893)Von: Bernhard Posselt An: owncloud/news Cc: under-score PHP won't work since it's killed by the webserver unfortunately that's why the updater is written in Python
