### ISSUE TITLE
Favorites and Unread news categories are kind of stacked on each other visually

### ISSUE THREAD

**Issue by benediktg** [owncloud/news#894]
If you look at this picture the count of favorites is shown in a strange way like there are two numbers stacked on each other. In addition to that the category "Unread news" is missing although I have some unread messages.

![news](https://cloud.githubusercontent.com/assets/14795615/11445086/9cf13294-9529-11e5-9a2f-6fd8d97075df.png)

I'm using Owncloud 8.2.1 (stable) and the News app version 6.1.1. If you need more info, just tell me.

**Comment by BernhardPosselt** [comment]
Browser and version and data/owncloud.log would be interesting.

**Comment by benediktg** [comment]
The browser is Firefox 42.0 as delivered by openSUSE Leap 42.1 and here is an extract of the owncloud log (there were no log entries since 20th of November, just some "login failed" ones caused by myself).
https://gist.github.com/benediktg/46db019eb44367fb851e
I formatted the log like a json file for better readablility.

**Comment by cosenal** [comment]
Thanks for reporting the issue.
Can you please check if there is any error in the browser console log? (hit F12 on the keyboard and check the tab Console).

**Comment by BernhardPosselt** [comment]
We both can't reproduce the issue, can you follow https://github.com/owncloud/news/blob/master/CONTRIBUTING.md#before-reporting-bugs ?

**Comment by BernhardPosselt** [comment]
And https://github.com/owncloud/news/blob/master/CONTRIBUTING.md#when-reporting-bugs

**Comment by benediktg** [comment]
Ok, I found the problem: it was the "Fanboy Annoyance List" in uBlock origin. After I have deactivated it works correctly now. ;)
Hence there's no problem with the Owncloud News app. Sorry for bothering you but thanks for the quick answers.
