### ISSUE TITLE
Internal server error! Please check your data/owncloud.log file for additional information!

### ISSUE THREAD

**Issue by crocki89** [owncloud/news#899]
Hello. I have:
Owncloud 8.2.1.4
News 6.1.1
PHP 5.6.14
Nginx 1.9.7
Browsers Firefox/Opera/Chrome/Maxton.

Apps for Owncloud: Documents, tasks, calendar(they are working) ,news(don't work).

After installation I opened the news and add rss. News crashed and wrote "Internal server error! Please check your data/owncloud.log file for additional information!".
When I opened the news next time I saw  "Internal server error! Please check your data/owncloud.log file for additional information!" and white page.

cat /data/owncloud.log
{"reqId":"ye+0NdtEteUEhVnEzqfg","remoteAddr":"192.168.107.108","app":"index","message":"Exception: {\"Exception\":\"BadFunctionCallException\",\"Message\":\"updateErrorCount is not a valid attribute\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(145): OCP\\\\AppFramework\\\\Db\\\\Entity->setter('updateErrorCoun...', Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(69): OCP\\\\AppFramework\\\\Db\\\\Entity->__call('setUpdateErrorC...', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(69): OCA\\\\News\\\\Db\\\\Feed->setUpdateErrorCount('0')\\n#3 [internal function]: OCP\\\\AppFramework\\\\Db\\\\Entity::fromRow(Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(305): call_user_func('OCA\\\\\\\\News\\\\\\\\Db\\\\\\\\Fee...', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(324): OCP\\\\AppFramework\\\\Db\\\\Mapper->mapRowToEntity(Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/db\\\/feedmapper.php(69): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntities('SELECT `feeds`....', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/service\\\/feedservice.php(72): OCA\\\\News\\\\Db\\\\FeedMapper->findAllFromUser('lavr')\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/controller\\\/feedcontroller.php(64): OCA\\\\News\\\\Service\\\\FeedService->findAll('lavr')\\n#9 [internal function]: OCA\\\\News\\\\Controller\\\\FeedController->index()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\News\\\\Controller\\\\FeedController), 'index')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\News\\\\Controller\\\\FeedController), 'index')\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('FeedController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(851): OC\\\\Route\\\\Router->match('\\\/apps\\\/news\\\/feed...')\\n#17 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php\",\"Line\":114}","level":3,"time":"2015-12-14T14:06:19+03:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds"}
{"reqId":"i\/3DdIb0cyGiRJl1Khkt","remoteAddr":"192.168.107.108","app":"index","message":"Exception: {\"Exception\":\"BadFunctionCallException\",\"Message\":\"updateErrorCount is not a valid attribute\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(145): OCP\\\\AppFramework\\\\Db\\\\Entity->setter('updateErrorCoun...', Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(69): OCP\\\\AppFramework\\\\Db\\\\Entity->__call('setUpdateErrorC...', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php(69): OCA\\\\News\\\\Db\\\\Feed->setUpdateErrorCount('0')\\n#3 [internal function]: OCP\\\\AppFramework\\\\Db\\\\Entity::fromRow(Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(305): call_user_func('OCA\\\\\\\\News\\\\\\\\Db\\\\\\\\Fee...', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(324): OCP\\\\AppFramework\\\\Db\\\\Mapper->mapRowToEntity(Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/db\\\/feedmapper.php(69): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntities('SELECT `feeds`....', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/service\\\/feedservice.php(72): OCA\\\\News\\\\Db\\\\FeedMapper->findAllFromUser('lavr')\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/controller\\\/itemcontroller.php(103): OCA\\\\News\\\\Service\\\\FeedService->findAll('lavr')\\n#9 [internal function]: OCA\\\\News\\\\Controller\\\\ItemController->index(2, 0, 40, 0, false, false, '')\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\News\\\\Controller\\\\ItemController), 'index')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\News\\\\Controller\\\\ItemController), 'index')\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('ItemController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(851): OC\\\\Route\\\\Router->match('\\\/apps\\\/news\\\/item...')\\n#17 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/entity.php\",\"Line\":114}","level":3,"time":"2015-12-14T14:06:19+03:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/items?limit=40&oldestFirst=false&search=&showAll=false&type=2"}

Journal
Error	index	Exception: {"Exception":"BadFunctionCallException","Message":"updateErrorCount is not a valid attribute","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/public\/appframework\/db\/entity.php(145): OCP\\AppFramework\\Db\\Entity->setter('updateErrorCoun...', Array)\n#1 \/var\/www\/owncloud\/lib\/public\/appframework\/db\/entity.php(69): OCP\\AppFramework\\Db\\Entity->__call('setUpdateErrorC...', Array)\n#2 \/var\/www\/owncloud\/lib\/public\/appframework\/db\/entity.php(69): OCA\\News\\Db\\Feed->setUpdateErrorCount('0')\n#3 [internal function]: OCP\\AppFramework\\Db\\Entity::fromRow(Array)\n#4 \/var\/www\/owncloud\/lib\/public\/appframework\/db\/mapper.php(305): call_user_func('OCA\\\\News\\\\Db\\\\Fee...', Array)\n#5 \/var\/www\/owncloud\/lib\/public\/appframework\/db\/mapper.php(324): OCP\\AppFramework\\Db\\Mapper->mapRowToEntity(Array)\n#6 \/var\/www\/owncloud\/apps\/news\/db\/feedmapper.php(69): OCP\\AppFramework\\Db\\Mapper->findEntities('SELECT `feeds`....', Array)\n#7 \/var\/www\/owncloud\/apps\/news\/service\/feedservice.php(72): OCA\\News\\Db\\FeedMapper->findAllFromUser('lavr')\n#8 \/var\/www\/owncloud\/apps\/news\/controller\/itemcontroller.php(103): OCA\\News\\Service\\FeedService->findAll('lavr')\n#9 [internal function]: OCA\\News\\Controller\\ItemController->index(2, 0, 40, 0, false, false, '')\n#10 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#11 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\News\\Controller\\ItemController), 'index')\n#12 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\News\\Controller\\ItemController), 'index')\n#13 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('ItemController', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#14 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#15 \/var\/www\/owncloud\/lib\/private\/route\/router.php(282): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#16 \/var\/www\/owncloud\/lib\/base.php(851): OC\\Route\\Router->match('\/apps\/news\/item...')\n#17 \/var\/www\/owncloud\/index.php(39): OC::handleRequest()\n#18 {main}","File":"\/var\/www\/owncloud\/lib\/public\/appframework\/db\/entity.php","Line":114}	2015-12-14T14:06:19+03:00
Error	index	Exception: {"Exception":"BadFunctionCallException","Message":"updateErrorCount is not a valid attribute","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/public\/appframework\/db\/entity.php(145): OCP\\AppFramework\\Db\\Entity->setter('updateErrorCoun...', Array)\n#1 \/var\/www\/owncloud\/lib\/public\/appframework\/db\/entity.php(69): OCP\\AppFramework\\Db\\Entity->__call('setUpdateErrorC...', Array)\n#2 \/var\/www\/owncloud\/lib\/public\/appframework\/db\/entity.php(69): OCA\\News\\Db\\Feed->setUpdateErrorCount('0')\n#3 [internal function]: OCP\\AppFramework\\Db\\Entity::fromRow(Array)\n#4 \/var\/www\/owncloud\/lib\/public\/appframework\/db\/mapper.php(305): call_user_func('OCA\\\\News\\\\Db\\\\Fee...', Array)\n#5 \/var\/www\/owncloud\/lib\/public\/appframework\/db\/mapper.php(324): OCP\\AppFramework\\Db\\Mapper->mapRowToEntity(Array)\n#6 \/var\/www\/owncloud\/apps\/news\/db\/feedmapper.php(69): OCP\\AppFramework\\Db\\Mapper->findEntities('SELECT `feeds`....', Array)\n#7 \/var\/www\/owncloud\/apps\/news\/service\/feedservice.php(72): OCA\\News\\Db\\FeedMapper->findAllFromUser('lavr')\n#8 \/var\/www\/owncloud\/apps\/news\/controller\/feedcontroller.php(64): OCA\\News\\Service\\FeedService->findAll('lavr')\n#9 [internal function]: OCA\\News\\Controller\\FeedController->index()\n#10 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#11 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\News\\Controller\\FeedController), 'index')\n#12 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\News\\Controller\\FeedController), 'index')\n#13 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('FeedController', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#14 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#15 \/var\/www\/owncloud\/lib\/private\/route\/router.php(282): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#16 \/var\/www\/owncloud\/lib\/base.php(851): OC\\Route\\Router->match('\/apps\/news\/feed...')\n#17 \/var\/www\/owncloud\/index.php(39): OC::handleRequest()\n#18 {main}","File":"\/var\/www\/owncloud\/lib\/public\/appframework\/db\/entity.php","Line":114}	2015-12-14T14:06:19+03:00

P.S. sorry for my english.

**Comment by BernhardPosselt** [comment]
You've downgraded from master which means that your database is newer than the code that you are using. Either remove the offending column in the items table or stay with master

**Comment by crocki89** [comment]
Sorry I don't understand you. In owncloud -> news_items I have columns:
id
guid_hash
fingerprint
rtl
search_index
guid
url
title
author
pub_date
body
enclosure_mime
enclosure_link
feed_id
status
last_modified

What i must remove?

**Comment by BernhardPosselt** [comment]
There should be an **update_error_count** column. Maybe it's also a PHP cache problem

**Comment by crocki89** [comment]
I found update_error_count in **news_feeds**. I drop column. It doesn't help. 
cat /var/www/owncloud/config/config.php
<div>
<?php
$CONFIG = array (
'debug' => true,
'instanceid' => '******',
'passwordsalt' => '********',
'secret' => '***************',
'trusted_domains' =>
array (
0 => '****.***.**',
),
'datadirectory' => '/data',
'overwrite.cli.url' => 'https://****.***.**/owncloud',
'dbtype' => 'mysql',
'version' => '8.2.1.4',
'dbname' => 'owncloud',
'dbhost' => 'localhost',
'dbtableprefix' => 'oc_',
'dbuser' => 'lavr',
'dbpassword' => '******',
'logtimezone' => 'MSK',
'appstoreenabled' => true,
'appstoreurl' => 'https://api.owncloud.com/v1',
'appstore.experimental.enabled' => true,
'apps_paths' =>
array (
0 =>
array (
'path' => '/var/www/owncloud/apps',
'url' => '/apps',
'writable' => true,
),
),
'enable_previews' => true,
'preview_libreoffice_path' => '/usr/bin/libreoffice',
'enabledPreviewProviders' => array(
'OC\Preview\PNG',
'OC\Preview\JPEG',
'OC\Preview\GIF',
'OC\Preview\BMP',
'OC\Preview\XBitmap',
'OC\Preview\MP3',
'OC\Preview\TXT',
'OC\Preview\MarkDown',
'OC\Preview\Illustrator',
'OC\Preview\Movie',
'OC\Preview\MSOffice2003',
'OC\Preview\MSOffice2007',
'OC\Preview\MSOfficeDoc',
'OC\Preview\OpenDocument',
'OC\Preview\PDF',
'OC\Preview\Photoshop',
'OC\Preview\Postscript',
'OC\Preview\StarOffice',
'OC\Preview\SVG',
'OC\Preview\TIFF',
'OC\Preview\Font',
),
'installed' => true,
'theme' => '',
'filesystem_check_changes' => 1,
'memcache.local' => '\\OC\\Memcache\\APCu',
'filelocking.enabled' => 'true',
'memcache.locking' => '\\OC\\Memcache\\Redis',
'memcached_servers' =>
array (
0 =>
array (
0 => 'localhost',
1 => 11211,
),
),
'redis' =>
array (
'host' => '127.0.0.1',
'port' => 6379,
'timeout' => 0,
'password' => '',
),
'loglevel' => 0,
);
</div>

**Comment by BernhardPosselt** [comment]
theres probably an additional column to drop. Your config does not help btw, need data/owncloud.log

**Comment by crocki89** [comment]
Thank you! It work.

rm -rf /var/www/owncloud/apps/news/
rm -rf /data/news/

mysql -u **** -p
use owncloud
delete from oc_appconfig where appid = 'news';
drop table news_feeds;
drop table news_folders;
drop table news_items;

service mysql restart
service nginx restart

cd /var/www/owncloud/apps/
tar xvzf 168040-news.tar.gz
chown -R nobody:nogroup news/

service nginx restart
