### ISSUE TITLE
News unable to subscrbe to Joomla.org news feed

### ISSUE THREAD

**Issue by Bugsbane** [owncloud/news#900]
When I try to subscribe to the feed for Joomla.org, in either rss 2.0 or atom, news gives me the "Feed not found error", however dong curl with the feed url from my server happily goes out and grabs what looks like a correct feed.

The 2 feed urls (rss 2.0 / atom) are:
https://www.joomla.org/announcements.feed?type=rss
https://www.joomla.org/announcements.feed?type=atom

There are the following warnings in the javascript console, but they appear before clicking subscribe. No warnings/errors show up after, other than news' own 'feed not found" error.

Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create es6-shim.min.js:10:20588
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.

Owncloud 8.2
News 6.1.1
Firefox 42

**Comment by BernhardPosselt** [comment]
Can reproduce, please reopen this in picoFeed ;) https://github.com/fguillot/picoFeed

**Comment by Bugsbane** [comment]
Sure. Can you tell me what versionof picofeed News 6.1.1 uses, so I can pass that on to the picofeed team?

**Comment by BernhardPosselt** [comment]
Master

**Comment by BernhardPosselt** [comment]
Resolved in the picoFeed thread, not a bug but Joomla thinking our user agent is Sql injection.

**Comment by BernhardPosselt** [comment]
I've added this to the faq https://github.com/owncloud/news#im-getting-a-feed-not-found-error-when-adding-a-feed-but-it-works-in-picofeedminiflux
