### ISSUE TITLE
Renaming title of news causes "Request forbidden"

### ISSUE THREAD

**Issue by rakekniven** [owncloud/news#903]
Just added feed.
Want to rename it.
After clicking edit, change title and hit the tick it tells me:
"Request forbidden. Are you an admin?"
![bildschirmfoto 2016-01-03 um 20 36 03](https://cloud.githubusercontent.com/assets/2069590/12080446/8ba5072e-b25a-11e5-93ce-2f5cff77e89f.png)

ownCloud version: 8.2.2
news version: 6.1.1

Side note:
Changing title using iOS news app with same user account works pretty well.

**Comment by cosenal** [comment]
I can reproduce it. @BernhardPosselt any idea?

**Comment by BernhardPosselt** [comment]
Can not reproduce this on master

**Comment by rakekniven** [comment]
Can I test master on ownCloud 8.2.2?

**Comment by BernhardPosselt** [comment]
yes

**Comment by cosenal** [comment]
@BernhardPosselt I know it's obvious, but I'll state it anyway: in order to reproduce it, you need to be logged as a non-admin user.

**Comment by BernhardPosselt** [comment]
@cosenal m( will check

**Comment by BernhardPosselt** [comment]
Can reproduce it, will check :)

**Comment by BernhardPosselt** [comment]
@cosenal first suspision is a stupid typo here: https://github.com/owncloud/news/blob/master/controller/feedcontroller.php#L262 but does not look like it

Can you check if its the PATCH method that causes issues? As in change the method in the routes to PUT and modify the JS here? https://github.com/owncloud/news/blob/master/js/service/FeedResource.js#L337

**Comment by rakekniven** [comment]
Just checked against master. UI shows version 6.1.4
Now I can change title of feed, but the yellow message shown at screenshot of my first posting is still shown. And yes I am not an admin.

**Comment by BernhardPosselt** [comment]
Issue was that the patch method docblock started with /* instead of /** at this line fyi: https://github.com/owncloud/news/blob/master/controller/feedcontroller.php#L261
