### ISSUE TITLE
RSS feed isbox.net won't be updated after initial fetch

### ISSUE THREAD

**Issue by nRaecheR** [owncloud/news#904]
### Steps to reproduce
1. Start Owncloud 8.2.2 on server with News app installed
2. Add feed URL http://www.isbox.net/rss.xml
3. Wait for initial sync of feed and mark all items as read
3. Manually check for updated feed XML w.g. with wget http://www.isbox.net/rss.xml
4. Check if News app fetches the updated feed

### Expected behaviour
* New items of RSS feed will be fetched and displayed after initial update of feed. 

### Actual behaviour
* No updates for this feed with be shown after fetching the initial content of the file. All further updates won't be displayed. Fetching the feed with wget works all the time and the fetched XML file contains the updated items. 

### Server configuration
**Operating system**: 
Ubuntu Wily amd64
**Web server:**
Apache 2.4.12
**Database:**
MariaDB 10.0
**PHP version:**
 5.6.11
**ownCloud version:** 
8.2.2
**News version:**
6.1.1

**The content of updater.ini:**

```
{# all values are optional and can be left out to require the argument being
# passed in from the command line

[updater]
user = <user>
password = <password>
threads = 10
interval = 600
testrun = false
url = <URL>
```

#### ownCloud log (data/owncloud.log)
Unfortunately empty, even after adding 'debug' => to OC config.php

**Comment by BernhardPosselt** [comment]
Probably the feed does not properly handle HTTP caching parameters, just a guess though

**Comment by BernhardPosselt** [comment]
@cosenal can you check?

**Comment by cosenal** [comment]
Works fine here, I am using system cron with cron.php.

**Comment by nRaecheR** [comment]
Strange...I tried it once again and still all but the initial fetch did not show any new/additional news items. @cosenal  Are you sure you marked all items as read and waited for the feed update ? I'm using the updater daemon from the News app with the configuration mentioned in the first post.

**Comment by nRaecheR** [comment]
I can see in the outgoing proxy log that the feed will be fetched every 10 minutes, like it is stated in the updater.ini file. 
@BernhardPosselt Is there anything I can do to track down the problem ? Is there any additional switch to get more debug data?

**Comment by BernhardPosselt** [comment]
If you upgrade to master, it will show you a warning in the UI with the last error message after 100 failed update attempts. If you are using an older version, the reason why the update failed should be written to the owncloud.log if you turn on debug mode: https://github.com/owncloud/news/blob/6.1.0/service/feedservice.php#L270

**Comment by nRaecheR** [comment]
I'm using News app 6.1.1, latest release AFAIK, and I have already enabled 'debug' => true in the OC config file. This should produce output to owncloud.log when the feed causes any kind of headaches, right ? Unfortunately there isn't a single line of output from the news app in the logfile. Even with debug enabled the owncloud.log seems to be updated on a very low rate. The last entry seems to be from the update to 8.2.2 and apps disabled.

What can I do to help track down the problem? Have you tried it on your installation, Bernhard ?

**Comment by BernhardPosselt** [comment]
Not yet, need more time (work ;))

Will check this weekend probably

**Comment by BernhardPosselt** [comment]
Can you check if 

    php -f owncloud/cron.php

updates the feed (don't forget to ebabke the checkbox in admin: **Use owncloud cron for updates** before)

**Comment by BernhardPosselt** [comment]
Ok can't reproduce, neither with the ownCloud cron nor with the custom updater. Everything is updated fine

**Comment by nRaecheR** [comment]
Thank you for testing.

I've updated News to 7.0.0 and tried the manual call of the cron.php but without any change to the problem. The feed won't be updated after the initial fetch. I'm totally puzzled why it won't work with my installation. The only slightly unusual thing is that all outgoing traffic will be routed through a proxy chain. But I've tested it with a manual curl test if the proxy is a problem and I always get the current and updated XML file.

The feed is the only one that shows this problem, all other feeds (20+) are updated without any problem.

**Comment by BernhardPosselt** [comment]
Maybe try to change the last_modified and etag columns in oc_news_feeds to an empty string and see if this works?

**Comment by nRaecheR** [comment]
Ha, looking at the database there is now a new "last error output" (without cleaning the etag and last_modified fields: 

```Feed nicht gefunden: entweder die Webseite unterstützt keine Feeds oder blockiert den Zugriff. Um das Blockieren auszuschließen, versuche den Feed mittels Serverkonsole runterzuladen: curl http://the-feed.tld```

But the update_error_count is only 1. 

Will try to clear the fields later.

**Comment by nRaecheR** [comment]
Mh, both fields are already empty, see here : 

```
+----+----------+----------------------------------+------------------------------+--------------------------------+---------+-----------------------+-------------------------------------------------------+---------------+------+------------+---------------------+------------+-----------+----------------+----------+-------------------+--------+-------------+--------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id | user_id  | url_hash                         | url                          | location                       | title   | link                  | favicon_link                                          | last_modified | etag | added      | articles_per_update | deleted_at | folder_id | prevent_update | ordering | full_text_enabled | pinned | update_mode | update_error_count | last_update_error                                                                                                                                                                                                  |
+----+----------+----------------------------------+------------------------------+--------------------------------+---------+-----------------------+-------------------------------------------------------+---------------+------+------------+---------------------+------------+-----------+----------------+----------+-------------------+--------+-------------+--------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 81 | <username> | 353cdb3354f3d944d77248321218c554 | http://www.isbox.net/rss.xml | http://www.israbox.org/rss.xml | IsraBox | http://www.isbox.net/ | http://www.isbox.net/templates/eng/images/favicon.ico |               |      | 1451846731 |                  20 |          0 |        17 |              0 |        0 |                 0 |      0 |           0 |                 17 | Feed nicht gefunden: entweder die Webseite unterstützt keine Feeds oder blockiert den Zugriff. Um das Blockieren auszuschließen, versuche den Feed mittels Serverkonsole runterzuladen: curl http://the-feed.tld   |
+----+----------+----------------------------------+------------------------------+--------------------------------+---------+-----------------------+-------------------------------------------------------+---------------+------+------------+---------------------+------------+-----------+----------------+----------+-------------------+--------+-------------+--------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

```

**Comment by nRaecheR** [comment]
Okay, now the "update_error_count" is back to normal but the feed wasn't updated either. Still no output to owncloud.log.

**Comment by BernhardPosselt** [comment]
The update error count gets reset if there was no error so nothing unusual here. 

Did you add proxy configuration to your curl call when testing?

**Comment by BernhardPosselt** [comment]
Also can you debug the same setup without proxies?

**Comment by nRaecheR** [comment]
Yes, the curl test used the proxy using the '-x' command line parameter. I've double checked that in the proxy logs too. All manual accesses and the OC news fetches are shown in the proxy log file. 

I've disabled the proxy in the OC config.php and configured the firewall to allow OC to directly access the internet without any change to the issue. I restarted the webserver, checked the proxy log files and that the feeds are get updated. All feeds have been updated except the one that causes the problem before.

So, no change without proxy.

**Comment by BernhardPosselt** [comment]
No idea then :(

Delete and readd the feed?

**Comment by nRaecheR** [comment]
Tried this at least 5 times, each time I started a new test actually. 

It seems we're out out of options. Is there any way to trace the actual fetch of the feed from php ? Some kind of debugging and writing to owncloud.log. Because I'm sure the News app fetches the XML file correctly (Proxy log, Intial Update etc.), it seems the processing of the following XML encounter some kind of problem. It would be nice to have some kind of tracing capability for that. But I can't understand why the problem only occurs on my installation and why the initial fetch always works.

**Comment by BernhardPosselt** [comment]
You could try to use the picoFeed logger https://github.com/fguillot/picoFeed/blob/master/docs/debugging.markdown

This is the entire method that uses picoFeed: https://github.com/owncloud/news/blob/master/fetcher/feedfetcher.php#L80

It should not be hard to hook into this with the logger :) 

Remember that error_log writes into your httpd error log and not data/owncloud.log!

**Comment by nRaecheR** [comment]
Okay, I will try add some debugging output in the next days. Thank you very much !

**Comment by nRaecheR** [comment]
Out of the sudden, starting today morning, the RSS feed continued to be working again, without any change in (client-side) configuration or updates to the OC server. It seems that the feed admins have changed some kind of configuration of the feed and now it will be updated regularly by the OC News app.

I'll close this issue. Thank you for your help !
