### ISSUE TITLE
Sub-Folders

### ISSUE THREAD

**Issue by cwmke** [owncloud/news#905]
It would be great to be able to add sub folders.  This way if you just want to have a general look at a category, you can do so from the top level.  If you want something more specific, you can select one of the sub-folders.  For example,

- Tech
   - Tech Blogs
   - Tech News

- News
   - Asia
   - Europe
   - US

#776 could provide most of the functionality, but regular expressions are rather complex for ordinary users I imagine although very useful for people (such as myself) who would like advanced tagging in the long run.  :-)

**Comment by BernhardPosselt** [comment]
It was an explicit decision to only have one folder level and also, check the issue tracker ;)

Apart from that there's too little space in the app navigation for this to work out and we'd have to override tons of core styles. In addition it will break our api.


Sorry, written on my phone so it might read harsher than it was meant ;)

And yep, #776 like you've mentioned is the way to go, closing this hence :)

**Comment by cwmke** [comment]
No problem at all.  :)  I took a look through the issue tracker and didn't find anything.  I guess I didn't look hard enough.  Thanks for the response.
