### ISSUE TITLE
[API 2.0] - Unexpected response in "Create folder"

### ISSUE THREAD

**Issue by David-Development** [owncloud/news#906]
I'm currently working on an import tool for opml files.

For simplicity reasons I'm just creating every folder (even if it exists). The doc (https://github.com/owncloud/news/wiki/Folders-1.2#create-a-folder) states that the result contains the folder id and name. But the result only contains "{"message":"Can not add folder: Exists already"}".

I think the result should be the id and the folder name (as described in the doc). Because the status code indicates that it already exists.

**Comment by BernhardPosselt** [comment]
I see, the misunderstanding here is due to the fact that for error cases, only the HTTP status codes should be considered. 

So to rephrase your request: Basically you want the POST method to return the same response as in a GET request if it exists?

**Comment by David-Development** [comment]
Exactly :+1: 

I mean it's not a "real" error that the folder already exists. So returning the id and name seems appropriate.

**Comment by BernhardPosselt** [comment]
Makes sense (also according to #rubyonrails) but would cause an API break. We should schedule this for API 2.0 ;)

For now I'd recommend to just fetch all folders via GET /folders and only create non existent folders ;)

**Comment by David-Development** [comment]
Btw. I think it's the same issue in the "Create a feed" method.

**Comment by BernhardPosselt** [comment]
Yep, and also in all updates (which should become PATCH instead of PUT) and deletions

**Comment by BernhardPosselt** [comment]
I've added this issue to the initial proposal in #862, let's keep the API stuff together ;)
