### ISSUE TITLE
Limit number of unread news per user

### ISSUE THREAD

**Issue by tflidd** [owncloud/news#908]
### Problem:
User tries the news app, adds some news feeds and then forgets about this feature. Owncloud will continue to fetch news. I ended up with a user with over 300 000 unread news and a `news_items`-table of over 700 MB in size.
I had a Maximum feed page size of `104857600` probably applies per feed?

### Solutions?
As a admin, I'd like to define some limits (like quotas):
* A total number of unread messages per user
* or a total storage size for the news-feature per user

**Comment by BernhardPosselt** [comment]
Not a solution IMHO but I understand the issue. I've discussed it with @fossxplorer who has a similar issue and the proposed idea was to record inactive users, send them a warning and delete their feeds if they did not log into the news app after a specified time.

This can be done by creating a very simple app, any progress there @fossxplorer?

**Comment by BernhardPosselt** [comment]
Ok, I've written up a good bunch of instructions on how this should be done here: https://github.com/owncloud/news/wiki/delete-feeds-of-inactive-users and linked it on the plugins page https://github.com/owncloud/news/wiki#requested-and-needs-contributors

Closing this as this should be done in a separate app like mentioned in #708
