### ISSUE TITLE
Starring 1.2 API appears broken

### ISSUE THREAD

**Issue by phedlund** [owncloud/news#911]
Trying to star a single item returns 500 internal server error. Staring multiple items path with only one item returns 200 OK, but the item is not starred in the web interface.

See https://github.com/owncloud/news-iOS-App/issues/68 for reference.

**Comment by BernhardPosselt** [comment]
Works for me.

**Comment by BernhardPosselt** [comment]
Example curl request:

```
curl -H "Content-Type: application/json" -X PUT -u admin:admin http://localhost:8080/index.php/apps/news/api/v1-2/items/277/f37760b99265ed52b6221f502a6ce325/star
```

**Comment by BernhardPosselt** [comment]
feedid and items guid need to be adjusted obviously :)

**Comment by BernhardPosselt** [comment]
Starring multiple also works fine for me and shows up in the web interface:
```
curl -H "Content-Type: application/json" -X PUT -u admin:admin http://localhost:8080/index.php/apps/news/api/v1-2/items/star/multiple -d '{"items":[{"feedId":277,"guidHash":"f37760b99265ed52b6221f502a6ce325"}]}'
```

There's nothing more I can tell you without more info

**Comment by BernhardPosselt** [comment]
Opcode cache probably? Did you follow https://github.com/owncloud/news/blob/master/CONTRIBUTING.md#before-reporting-bugs ?

**Comment by BernhardPosselt** [comment]
Two things: do you send the application/Jason content type and did you disable the encryption app?

**Comment by phedlund** [comment]
For unstarring a single item I send a URL with a path like this:
`NSString *path = [NSString stringWithFormat:@"items/%@/%@/unstar", [item.feedId stringValue], item.guidHash];`
This code has not changed in ages.

I have never used encryption:
![screen shot 2016-01-28 at 8 20 32 am](https://cloud.githubusercontent.com/assets/884639/12650670/8241e566-c598-11e5-8313-34e62df43a95.png)
![screen shot 2016-01-28 at 8 19 39 am](https://cloud.githubusercontent.com/assets/884639/12650673/828d48bc-c598-11e5-83e7-87ca3f9d05aa.png)

**Comment by BernhardPosselt** [comment]
Does the curl command work for you?

**Comment by phedlund** [comment]
The curl commands do work, but this Firefox REST client also fails. I am at a loss here.
![screen shot 2016-01-30 at 11 11 21 am](https://cloud.githubusercontent.com/assets/884639/12697877/70411c28-c742-11e5-923c-24dc88f2d621.png)

**Comment by phedlund** [comment]
OK, I think I solved. It had to do with the request headers I sent after all. However, something must have changed either in the server code or in the library I use for networking since my code used to work fine.

I wonder if this comment (http://stackoverflow.com/a/16955666/2036378) can be of relevance?

Feel free to close this.

**Comment by BernhardPosselt** [comment]
Another thing that I just discovered: apparently something is accessing the PUT parameters twice and errors because of https://github.com/owncloud/core/blob/master/lib/private/appframework/http/request.php#L376 which is stupid because that restriction is gone in php 5.6 

If at all this is an issue in core (they should remove this check for newer php versions)
