### ISSUE TITLE
On mobile broswers, cannot tap on dots in sidebar

### ISSUE THREAD

**Issue by valmar** [owncloud/news#912]
On mobile broswers (Firefox or Chrome on Android, browser in Ubuntu Touch), if I click on a feed in the sidebar, and then on the dots to open the popup menu, the popup menu does not come up and instead the sidebar closes. This makes impossible to remove feeds or to mark all as read, etc.

Thank you very much for looking into this. Let me know if you need more information...

**Comment by BernhardPosselt** [comment]
Please reopen in core, since the code for this lives there ;)

**Comment by valmar** [comment]
Just did: https://github.com/owncloud/core/issues/21777

Thank you!

Valmar
