### ISSUE TITLE
App totally broken when italian language is chosen

### ISSUE THREAD

**Issue by macgherl57** [owncloud/news#913]
Hi all.
I post this issue in the hope that it is not quite dependent on some particular configuration of my server, which I doubt since all other apps are working quite well, and owncloud log doesn't output any error.
I installed the app with italian as language (my box is in an italian domain) and I got this screen:
![news_italian](https://cloud.githubusercontent.com/assets/14032126/12401862/99837936-be29-11e5-9553-326d053832fe.png)
Like I said, owncloud log doesn't report any problems, and particularly upsetting is the video player bar appearing. The app is just stuck and nothing happens.
All other non English languages I tried worked without any problems.
Since all my users have italian as their default language, the app is quite unusable in this state.
Any help appreciated.
Michael57

**Comment by BernhardPosselt** [comment]
Problem is twofold:
* Most likely some quoting issues (problem is single quote here: L'aggiornamento non è riuscito più di 50 volte:): will move the whole translation strings to JS I think. 
* Translators don't use the app (at least the German ones) and are on a different platform (Transifex) which results in aweful translations, no communication and inconsistencies all over the place.
