### ISSUE TITLE
failed to subscribe to http://alaxon.co.il

### ISSUE THREAD

**Issue by mat-mo** [owncloud/news#915]
Hi, I tried to subscribe to this feed, but it fails. To verify it is the news app and not a general rss issue i used miniflux to verify i am able to subscribe, and indeed, it works. I think it is a bug in news.

Thanks

**Comment by BernhardPosselt** [comment]
Contact the feed author, we've encountered the issue multiple times and it's bad server setups that refuse the request because they think our user agent string is an SQL injection ;)

**Comment by BernhardPosselt** [comment]
Unless ofc you can back it up with exceptions in your error log ;)
