### ISSUE TITLE
Bug with Cyrillic symbols

### ISSUE THREAD

**Issue by rakshazi** [owncloud/news#919]
Hello!

## Enviroment

Owncloud 8.2.2
News 7.1.1
Chrome 48.0.2564.97 (64-bit)
PHP 7.0.2-4+deb.sury.org~trusty+1 (cli) ( NTS )
Ubuntu 14.04.xx

## Problem

I have atom feed with russian text: https://s2a.svart.xyz/convert.php?url=https://vk.com/sci_one
But in OwnCloud News app items from this feed shown not properly, here is one of entries:
```
РџСЏС‚С‹Р№ РїР°Р»РµС† РїР»РµР·РёРѕР·Р°РІСЂР° РїРѕР·РІРѕР»РёР» РІС‹РґРµР»РёС‚СЊ РµРіРѕ РІ РѕС‚РґРµР»СЊРЅС‹Р№ РІРёРґ
Р РѕСЃСЃРёР№СЃРєРёРµ СѓС‡РµРЅС‹Рµ РѕРїРёСЃР°Р»Рё РЅРѕРІС‹Р№ РІРёРґ РїР»РµР·РёРѕР·Р°РІСЂРѕРІ Polycotylus sopozcovi sp. Nov., Р¶РёРІС€РёС… 65 РјРёР»Р»РёРѕРЅРѕРІ Р»РµС‚ РЅР°Р·Р°Рґ. РћРєР°РјРµРЅРµРІС€РёРµ РѕСЃС‚Р°РЅРєРё РјРѕСЂСЃРєРѕРіРѕ СЏС‰РµСЂР° Р±С‹Р»Рё РЅР°Р№РґРµРЅС‹ РІ 2015 РіРѕРґСѓ РІ РћСЂРµРЅР±СѓСЂРіСЃРєРѕР№ РѕР±Р»Р°СЃС‚Рё. РћР± РёСЃСЃР»РµРґРѕРІР°РЅРёРё СЃРѕРѕР±С‰Р°РµС‚ РўРђРЎРЎ.
РЈС‡РµРЅС‹Рµ РѕР±РЅР°СЂСѓР¶РёР»Рё РѕС‚РЅРѕСЃРёС‚РµР»СЊРЅРѕ С†РµР»С‹Рµ С„СЂР°РіРјРµРЅС‚С‹ СЃРєРµР»РµС‚Р°, РІ С‚РѕРј С‡РёСЃР»Рµ С„СЂР°РіРјРµРЅС‚С‹ С‡РµСЂРµРїР°, РїР»РµС‡РµРІРѕРіРѕ РїРѕСЏСЃР°, РїРµСЂРµРґРЅРµР№ Рё Р·Р°РґРЅРµР№ РєРѕРЅРµС‡РЅРѕСЃС‚РµР№. Р­С‚Рѕ Р±С‹Р» СЏС‰РµСЂ РґР»РёРЅРѕР№ 4 вЂ” 7 РјРµС‚СЂРѕРІ СЃ РєСЂСѓРїРЅРѕР№ РіРѕР»РѕРІРѕР№ Рё РјРѕС‰РЅРѕР№ С€РµРµР№.
РЈ РЅР°Р№РґРµРЅРЅРѕРіРѕ РґРёРЅРѕР·Р°РІСЂР° Р±С‹Р»Рѕ РїСЏС‚СЊ РїР°Р»СЊС†РµРІ РЅР° Р»Р°РїР°С…, СЃРѕРѕР±С‰Р°СЋС‚ РёСЃСЃР»РµРґРѕРІР°С‚РµР»Рё, Рё СЌС‚Рѕ РїРѕР·РІРѕР»РёР»Рѕ РѕС‚РЅРµСЃС‚Рё РµРіРѕ Рє РЅРѕРІРѕРјСѓ РІРёРґСѓ. РЈ РІСЃРµС… РїСЂРµРґСЃС‚Р°РІРёС‚РµР»РµР№ СЂРѕРґР° Polycotylus, РЅР°Р№РґРµРЅРЅС‹С… РґРѕ СЌС‚РѕРіРѕ, Р±С‹Р»Рѕ С‚РѕР»СЊРєРѕ С‡РµС‚С‹СЂРµ РїР°Р»СЊС†Р° РЅР° Р»Р°РїР°С…-Р»Р°СЃС‚Р°С…. РќРѕРІС‹Р№ РІРёРґ РЅР°Р·РІР°Р»Рё РІ С‡РµСЃС‚СЊ РіР»Р°РІРЅРѕРіРѕ Р°РІС‚РѕСЂР° РЅР°С…РѕРґРєРё, РіРµРѕР»РѕРіР° Р“Р°Р»РёРЅС‹ РЎРѕРїРѕС†РєРѕ.
РџР»РµР·РёРѕР·Р°РІСЂС‹ вЂ” РјРѕСЂСЃРєРёРµ СЏС‰РµСЂС‹, РѕР±РёС‚Р°РІС€РёРµ РЅР° Р—РµРјР»Рµ РІ РїРµСЂРёРѕРґ СЃ С‚СЂРёР°СЃРѕРІРѕРіРѕ РїРѕ РјРµР»РѕРІРѕР№ РїРµСЂРёРѕРґ (РїСЂРёРјРµСЂРЅРѕ 200 вЂ” 65 РјРёР»Р»РёРѕРЅРѕРІ Р»РµС‚ РЅР°Р·Р°Рґ). РЈ РЅРёС… Р±С‹Р»Рё С‡РµС‚С‹СЂРµ РєРѕРЅРµС‡РЅРѕСЃС‚Рё, РїСЂРµРѕР±СЂР°Р·РѕРІР°РЅРЅС‹Рµ РІ Р»Р°СЃС‚С‹ Рё Р±РѕС‡РєРѕРѕР±СЂР°Р·РЅРѕРµ С‚РµР»Рѕ. РћСЃС‚Р°РЅРєРё РїР»РµР·РёРѕР·Р°РІСЂРѕРІ РѕР±РЅР°СЂСѓР¶РµРЅС‹ РЅР° РІСЃРµС… РєРѕРЅС‚РёРЅРµРЅС‚Р°С…, РІ С‚РѕРј С‡РёСЃР»Рµ Рё РІ РђРЅС‚Р°СЂРєС‚РёРґРµ. 
Р?СЃС‚РѕС‡РЅРёРє: https://nplus1.ru/news/2016/02/01/new-Plesiosauria
```

How can I fix it?

Best regards, Nikita.

**Comment by BernhardPosselt** [comment]
Works fine for me :)

**Comment by BernhardPosselt** [comment]
Locale issues on your server?

**Comment by rakshazi** [comment]
@BernhardPosselt how can I check it? 
It works for me if I directly open atom feed in browser, but when I try to load it via OwnCloud News - I got bug with encoding :(

Do you have any idea to check problem and fix it?

**Comment by BernhardPosselt** [comment]
<img width="1251" alt="screen shot 2016-02-02 at 14 05 42" src="https://cloud.githubusercontent.com/assets/195053/12750249/34d6e3ea-c9b6-11e5-9274-1a3a4e8f29c1.png">

**Comment by rakshazi** [comment]
![index-php-apps-news-1454418480203](https://cloud.githubusercontent.com/assets/3428087/12750288/d2ee70ae-c9be-11e5-99cc-29bff4713851.png)

:(

**Comment by BernhardPosselt** [comment]
Check your database schema locale, your system locales. I can't give you further advice since I can't reproduce it and I am not really familiar with these issues.

**Comment by BernhardPosselt** [comment]
@bugsbane @LukasReschke @cosenal @cmweike @tflidd

**Comment by rakshazi** [comment]
Oh... i think, problem has been solved itself O_O
I don't know how
![index-php-apps-news-1454418573060](https://cloud.githubusercontent.com/assets/3428087/12750314/0c7e5cda-c9bf-11e5-9449-febb7e940d92.png)

**Comment by rakshazi** [comment]
Sorry for disturb. Ok, I'll go to Mage Academy for now. I need to know  which kind of damnation was it!

Have a nice day @BernhardPosselt :sweat_smile:
