### ISSUE TITLE
Activation of fulltext of feed fails

### ISSUE THREAD

**Issue by donkeyDau** [owncloud/news#923]
Trying to activate fulltext of a feed. It fails with error

`{
  "reqId": "I2FdL0rgf0vu0PDgpGSy",
  "remoteAddr": "178.5.228.37",
  "app": "index",
  "message": "Exception: {\"Exception\":\"Doctrine DBAL Exception InvalidFieldNameException\",\"Message\":\"An exception occurred while executing 'UPDATE `oc_news_feeds` SET `full_text_enabled` = ?,`etag` = ?,`last_modified` = ? WHERE `id` = ?' with params [true, \"\", 0, 2]:nnSQLSTATE[42S22]: Column not found: 1054 Unknown column 'full_text_enabled' in 'field list'\",\"Code\":0,\"Trace\":\"#0 /var/www/oc/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine DBAL Driver AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine DBAL Driver PDOException))n#1 /var/www/oc/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(172): Doctrine DBAL DBALException::driverExceptionDuringQuery(Object(Doctrine DBAL Driver PDOMySql Driver), Object(Doctrine DBAL Driver PDOException), 'UPDATE `oc_news...', Array)n#2 /var/www/oc/lib/public/appframework/db/mapper.php(250): Doctrine DBAL Statement->execute()n#3 /var/www/oc/lib/public/appframework/db/mapper.php(186): OCP AppFramework Db Mapper->execute('UPDATE `*PREFIX...', Array)n#4 /var/www/oc/apps/news/service/feedservice.php(437): OCP AppFramework Db Mapper->update(Object(OCA News Db Feed))n#5 /var/www/oc/apps/news/controller/feedcontroller.php(289): OCA News Service FeedService->patch(2, 'fabi', Array)n#6 [internal function]: OCA News Controller FeedController->patch(2, NULL, true, NULL, NULL, NULL, NULL)n#7 /var/www/oc/lib/private/appframework/http/dispatcher.php(159): call_user_func_array(Array, Array)n#8 /var/www/oc/lib/private/appframework/http/dispatcher.php(89): OC AppFramework Http Dispatcher->executeController(Object(OCA News Controller FeedController), 'patch')n#9 /var/www/oc/lib/private/appframework/app.php(108): OC AppFramework Http Dispatcher->dispatch(Object(OCA News Controller FeedController), 'patch')n#10 /var/www/oc/lib/private/appframework/routing/routeactionhandler.php(45): OC AppFramework App::main('FeedController', 'patch', Object(OC AppFramework DependencyInjection DIContainer), Array)n#11 [internal function]: OC AppFramework routing RouteActionHandler->__invoke(Array)n#12 /var/www/oc/lib/private/route/router.php(291): call_user_func(Object(OC AppFramework routing RouteActionHandler), Array)n#13 /var/www/oc/lib/base.php(851): OC Route Router->match('/apps/news/feed...')n#14 /var/www/oc/index.php(41): OC::handleRequest()n#15 {main}\",\"File\":\"/var/www/oc/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php\",\"Line\":71}",
  "level": 3,
  "time": "2016-02-14T09:00:34+00:00"
}`

**Comment by donkeyDau** [comment]
Running v7.1.1

**Comment by BernhardPosselt** [comment]
I've added a FAQ entry since this issue surfaces from time to time, please follow https://github.com/owncloud/news#i-am-getting-doctrine-dbal-exception-invalidfieldnameexception-column-not-found-1054-unknown-column-some_column-or-badfunctioncallexception-column-is-not-a-valid-attribute

**Comment by donkeyDau** [comment]
Thx a lot. The update trick solved my problem.
