### ISSUE TITLE
User content filters for feeds

### ISSUE THREAD

**Issue by Loki3000** [owncloud/news#933]
It's to be good to add user filters for feeds.
For example if I not want to get entitys of specified autors or contains some keywords, I just add filters to feed and filtered posts automatically marks as read. I want to read feed about programming, but don't want to see entitys about C++. So i'll set filter "title:'C++'" and all entitys with C++ in title automatically marks as read while feed updates.

**Comment by BernhardPosselt** [comment]
dup of #776 and #768
