### ISSUE TITLE
Fix proposed version from appstore for OC 8.1.6

### ISSUE THREAD

**Issue by tflidd** [owncloud/news#934]
## Explain the Problem
I updated to OC 8.1.6 (from OC 8.1.5) and need to enable my apps again. In the app page, the app store offers an update:
![screenshot](https://cloud.githubusercontent.com/assets/8111200/13648564/91497224-e639-11e5-81b4-8166b3fd61ac.PNG)

When I click on update, it says that this version is not compatible with my OC version. Why was it offered in the first place? Isn't it possible to ship different versions of your app depending on the OC version used?

**Comment by BernhardPosselt** [comment]
No idea, I've marked the app as compatible with 8.2 and 9

**Comment by BernhardPosselt** [comment]
So basically this option should not be displayed by ownclouf

**Comment by tflidd** [comment]
Ok, I reported this to the appstore-bugtracker: https://github.com/owncloud/appstore-issues/issues/50
