### ISSUE TITLE
After search  items not marks as read

### ISSUE THREAD

**Issue by Loki3000** [owncloud/news#935]
## Explain the Problem
While scrolling search result items not marks as readed.

## Steps to Reproduce
1. open news on OC
2. select feed
3. click search icon and enter search string. Hit Enter (appears search result)
4. scroll items. Scrolled items not marks as readed.
5. Hit F5. Page refreshes.
6. scroll items and now scrolled items marks as readed.

## System Information
* News app version:  7.1.2
* ownCloud version: 9.0.0
* PHP version: 5.5.9
* Database and version: 5.5.47
* Browser and version: FF 45.0 

## Contents of Browser Error Console
```
TypeError: e is null   jquery.min.js:4:5189
TypeError: lastResults is null  search.js:260:1
```

**Comment by BernhardPosselt** [comment]
Can not reproduce. The JavaScript errors are not related to our code and are not triggered on my test instance

**Comment by Loki3000** [comment]
It was core search error (https://github.com/owncloud/core/issues/23182#issuecomment-196722628). It hangs JS error, so news app stop working properly. After fixing all works well.
