### ISSUE TITLE
Podcast / comic friendly news reader

### ISSUE THREAD

**Issue by dbenoy** [owncloud/news#937]
Would it be possible to improve the news reader for podcasts, web comics, and other materials that you would want to subscribe to and read every article _sequentially_, _without missing any_?

Here's a couple really simple and unobtrusive changes that would greatly improve the experience:
- Adding the ability to override the 'read as you scroll' only for specific feeds, just like how you can override the sort order.
- A 'quick scroll' button that brings you to the next unread article.

**Comment by BernhardPosselt** [comment]
Thanks for your contribution! I'm on the phone so I will keep this short ;)

Marking read is simply clicking on the article, no button needed. There's an open issue which aims to improve mouse and keyboard usage, so that one might make the click to read more obvious. 

Jumping to the next unread article is very simple in unread articles only mode, I see no need to add a custom shortcut, especially because auto paging is problematic here.

As for custom scroll to read settings: I don't understand why you would want to set this per feed. The ordering was added specifically for reading comics whole keeping the newest first ordering for news

**Comment by dbenoy** [comment]
Oh! You can click on articles to make them read? Cool. Now I know.

I tried 'unread articles only mode' but something is messed up for me and it makes entire feeds completely disappear sometimes in the left pane. I was planning on filing a separate issue for that if I can figure out what's causing it.

Hm... I don't think I explained the override thing well enough. I'll try again.

It's possible to override the global sort order. That's good for web comics. But it doesn't seem possible to override the global "mark articles read as you scroll', which is bad for web comics.

I have, in practice, gotten 'false reads' where I didn't quite realize what I was doing and ended up skipping ahead because something got unintentionally marked read and I ended up reading a spoiler.

So my solution was to turn it off globally, since there is no granular control, then turn it back on temporarily to mark things read. (Now that I know you can click, that will make things easier! but it would still be nice to have granular control.)

Also, it would be nice to be able to apply the sort order / scrollread to an entire group of feeds at once.

**Comment by BernhardPosselt** [comment]
What browser are you using?

**Comment by dbenoy** [comment]
Chrome
Gentoo Linux

**Comment by BernhardPosselt** [comment]
OK and the feeds that have this behavior?

**Comment by dbenoy** [comment]
I figured it out. Looks like the entire feeds disappear (can't do anything to them. Can't delete them, can't change the sort order, can't even see them) when I finish reading every article in them, but they come back when a new news item arrives in them, or I go back to 'show all articles'.

**Comment by BernhardPosselt** [comment]
Yep read feeds are hidden in only unread articles mode

**Comment by dbenoy** [comment]
I'll edit the original post to remove the 'marked read' bit, since that's already implemented. If you think the remaining items aren't worth implementing, go ahead and close the ticket.

I may end up adding these features to my own instance myself, in which case I hope you would be open-minded to a pull request.

Thanks :)

**Comment by BernhardPosselt** [comment]
The only thing that came to my mind would be keyboard shortcuts for toggling settings. Eg 

alt + a    for toggling the show unread articles

Jumping to the next unread article could probably also be implemented and should probably jump to the very bottom if no unrest article is loaded (triggers auto paging). 


Here's the file to edit should be pretty straight forward https://github.com/owncloud/news/blob/master/js/gui/KeyboardShortcuts.js

**Comment by BernhardPosselt** [comment]
The readme in the is directory explains how to run all the tools !)

**Comment by BernhardPosselt** [comment]
Any progress on this?

**Comment by dbenoy** [comment]
No. I'll close this issue for now. I find I'm becoming somewhat comfortable with using the app without these features.

I'll still be looking into making improvements, though.

**Comment by BernhardPosselt** [comment]
Awesome :) thanks!

BTW, you've closed the 800th issue ;)
