### ISSUE TITLE
Support for password protected feeds

### ISSUE THREAD

**Issue by n00b12345** [owncloud/news#938]
I'm not sure if this is supported yet. The feeds I tried (locally created for testing) didn't work. 

Do consider adding support for this.

**Comment by BernhardPosselt** [comment]
Solution here should probably be to warn users that the password will be stored in plain text and to disallow adding non https feeds with basic authentication.

If anyone is interested in working on this, feel free to ask for help and tipps, I probably won't have the time to do this so marking this feature as contributors needed

**Comment by BernhardPosselt** [comment]
@n00b12345 btw, something that just came to my mind: can you try if this works already by using the http basic auth url? http://youruser:yourpassword@feed.com/password-protected/feed.rss?

**Comment by n00b12345** [comment]
@BernhardPosselt yeah I tried it earlier in the day using a locally generally feed. Didn't work unfortunately. The feed just failed to load even with a 300 second timeout.

**Comment by BernhardPosselt** [comment]
https://github.com/fguillot/picoFeed/pull/258

**Comment by BernhardPosselt** [comment]
@n00b12345 do you have a feed that I can easily test?

**Comment by n00b12345** [comment]
@Bernard I'm so terribly sorry, I don't. My Apache server running OwnCloud is nothing but a raspberry pi.

 I'm basically using Shaarli (the bookmarking client) to generate local RSS feeds, whose Apache powered page is protected by a password; therefore the need to have the ability to read password protected feeds. Shaarli is here on GitHub. You could, if possible, test it though at your end, since it requires no setup and won't take much of your time. 

Again, so terribly sorry about this. Apologies.

**Comment by n00b12345** [comment]
Sorry to open this again, but I've a feed you can test.

This is the RSS feed link : http://shaarlidemo.tuxfamily.org/Shaarli/?do=rss&searchtags=test

This is the username and password: demo, demo

Needless to say, you can go to http://shaarlidemo.tuxfamily.org/Shaarli to check this. I've added a link with the test tag.

**Comment by BernhardPosselt** [comment]
@n00b12345 did you try the latest version? Basic Auth is already implemented

**Comment by n00b12345** [comment]
Oh okay. I didn't realise that. I'll have to update my OwnCloud installation. Unfortunately my repository is still stuck in 8.2.3. 

Thanks for the help!
