### ISSUE TITLE
Add support of youtube subscriptions

### ISSUE THREAD

**Issue by sprnza** [owncloud/news#940]
Hi there!
Thank you for you job!
We definitely need support of youtube subscriptions, currently a list of new videos is receiving but items are empty! See a [screenshot ](http://i.imgur.com/TXrahXs.png)

# IMPORTANT

Read and tick the following checkbox after you have created the issue or place an x inside the brackets ;)

* [X] I have read the [CONTRIBUTING.md](https://github.com/owncloud/news/blob/master/CONTRIBUTING.md) and followed the provided tips

**Comment by BernhardPosselt** [comment]
Did you try to turn on full text feed yet for the feed?

**Comment by sprnza** [comment]
How can I do that?

**Comment by BernhardPosselt** [comment]
It's in the 3 dot menu for a feed

**Comment by sprnza** [comment]
Yep, it works for youtube subscriptions. Is there a way to turn it on globally? It doesn't work for embedded videos in LJ feeds though.

**Comment by sprnza** [comment]
I think it's LiveJournal issue, because even Feedly doesn't show embedded videos. So I close the issue. Thank you for support!

**Comment by BernhardPosselt** [comment]
No it's per feed. We had it globally before but the update process slows down 50-x fold (depending on the item count in the feed) and not every feed profits from it.
