### ISSUE TITLE
Add "Open in a website" link

### ISSUE THREAD

**Issue by sprnza** [owncloud/news#941]
Hi there!
Another cool feature I miss is an ability to open a source post in other tab. It's necessary when the page is rendering not correctly or you want to read comments for example.

**Comment by BernhardPosselt** [comment]
Every link should open in a new tab right now if you click on the title. What do you mean by not rendering correctly?

**Comment by sprnza** [comment]
Yep, it works for standard view, but doesn't for compact one. By not rendering correctly I mean videos that are not displayed in feeds.

**Comment by BernhardPosselt** [comment]
Hit o for  open or click the world icon

**Comment by sprnza** [comment]
Yay! Thank you very much!!
