### ISSUE TITLE
Ability to determine feed polling time/feed boosting time

### ISSUE THREAD

**Issue by n00b12345** [owncloud/news#942]
Not every feed needs the same feed kind of feed polling. Also, if one has a large number of feeds, frequent feed polling can consume a large amount of data.

It would really be great to have the ability to set feed polling time for individual feeds. 

Just a thought.

**Comment by BernhardPosselt** [comment]
This is solved by using http caching. No need to worry about the interval, most feeds support it and it won't really matter.

**Comment by BernhardPosselt** [comment]
Question answered :)?

**Comment by n00b12345** [comment]
Of course it's been answered :)

I'm so sorry for the late response. Been a bit busy. Apologies

**Comment by BernhardPosselt** [comment]
NP :)
