### ISSUE TITLE
Non-latin search is case sensitive

### ISSUE THREAD

**Issue by Loki3000** [owncloud/news#944]
## Explain the Problem
Search feeds with non-latin chars is case sensitive.

## Steps to Reproduce
in search field type ```одного``` and hit Enter

## Expected:
filter the entity
```
Одного из израильских генералов спросили, можно ли простить террориста?
На это он ответил:
— Бог простит. Наша задача организовать их встречу.
```

## Actual:
Empty result

## System Information
* News app version: 7.1.2
* ownCloud version: 9.0.0
* PHP version: 7.0.4
* Database and version: mysql 5.5.47

**Comment by BernhardPosselt** [comment]
Feel free to submit a fix, I unfortunately can not test this very well on a Latin only keyboard. Relevant section should be here: https://github.com/owncloud/news/blob/master/db/itemmapper.php#L71

Solution is probably to replace **strtolower** with **mb_strtolower**, please try if this works and submit a pull request

**Comment by BernhardPosselt** [comment]
Ah right, same issue here where it creates the index https://github.com/owncloud/news/blob/master/db/item.php#L219

**Comment by BernhardPosselt** [comment]
You will need to readd the feed to check if it worked btw

**Comment by Loki3000** [comment]
Thanks!
Now search works well.

**Comment by BernhardPosselt** [comment]
Can you create a pull request to fix it for everyone ;D?
