### ISSUE TITLE
Settings not persistent

### ISSUE THREAD

**Issue by badarg** [owncloud/news#948]
# IMPORTANT

Read and tick the following checkbox after you have created the issue or place an x inside the brackets ;)

* [X] I have read the [CONTRIBUTING.md](https://github.com/owncloud/news/blob/master/CONTRIBUTING.md) and followed the provided tips

## Explain the Problem
I can change settings via the settings menu (like enabling the "compact view") and they work fine, but if I reload the page (or visit it again later) the settings are back to the defaults (all checkboxes are cleared).
I don't know if this is intentional, but I would like my changes to be persistent.

## Steps to Reproduce
1. Go to the ownCloud News page.
2. Open the settings menu (click on the gear at the bottom left). All checkboxes will be cleared.
3. Enable some checkboxes (for example, "compact view"). The new settings will take effect immediately.
4. Refresh or revisit the page.
5. Open the settings menu again. All checkboxes will be cleared again (despite having checked some in step 3).

## System Information
* News app version: 7.1.2
* ownCloud version: 9.0.0 (stable)
* PHP version: 7.0.4
* Database and version: PostgreSQL 9.5.1
* Browser and version: Chromium 49.0.2623.87 (64-bit) & Firefox 45.0.1
* Distribution and version: Arch Linux ARM (up to date)

## Contents of owncloud/data/owncloud.log
No logs are written while reproducing the problem.

## Contents of Browser Error Console
Nothing is output to the browser console while reproducing the problem.

**Comment by BernhardPosselt** [comment]
Hm, there should be logs. Most likely problem is that the app cant write into the data/ directory where the config is stored, can you check?

**Comment by BernhardPosselt** [comment]
Ok, weird, can reproduce it :) one sec

**Comment by badarg** [comment]
Hello, thank you for the quick response.
The permissions look right to me: the web server owns the data directory and all the files and subdirectories in it. Still, no logs.
I do get log messages from the ownCloud cron jobs, though.
¿When should the logs be written, when the page loads or when I change the settings?

Thank you.

**Comment by BernhardPosselt** [comment]
First guess is a regression in core stable9 and postgresql, works fine for me on sqlite. One sec ;)

**Comment by BernhardPosselt** [comment]
Yes, it's a bug in core, here's the issue https://github.com/owncloud/core/issues/23583

**Comment by BernhardPosselt** [comment]
Ok, it seems there are some inconsistencies when saving boolean values, I've changed it to saving strings so the issue should be resolved now in master
