### ISSUE TITLE
Starred icon looks like enabled, when hovered

### ISSUE THREAD

**Issue by bbBowser** [owncloud/news#949]
The star icons are not showing any feedback, when feeds are de-starred and the mouse stil hovers over the icon. This is quite irritating and could be solved by changing the icons hover appearance.

**Comment by BernhardPosselt** [comment]
Yellow outline maybe? What do you think?

**Comment by bbBowser** [comment]
Yes. Or a higher contrasted yellow for the whole hovered icon.

**Comment by BernhardPosselt** [comment]
Would you mind giving it a try? The images are here: https://github.com/owncloud/news/tree/master/img  (active_star.svg, inactive_star.svg). You can use inkscape to create another image. 

Here is the CSS for the hover style https://github.com/owncloud/news/blob/master/css/content.css#L284
