### ISSUE TITLE
14.04 no more supported ?

### ISSUE THREAD

**Issue by jajaX** [owncloud/news#950]
Hi (sorry for my bad english)

I update my php to 5.5.9 to 5.6 for have last update.
 
But I see Ubuntu 16.04 support.
 
No more for 14.04 ?

regards

jaja

## System Information
* News app version: 7.1.2
* ownCloud version:9.0
* PHP version:5.6
* Database and version:
* Browser and version:
* Distribution and version: Kubuntu 14.04

**Comment by BernhardPosselt** [comment]
Yes, but you can simply upgrade to a newer PHP version: https://www.digitalocean.com/community/tutorials/how-to-upgrade-to-php-7-on-ubuntu-14-04

**Comment by BernhardPosselt** [comment]
Reasons for dropping 5.5 support:
* Latest phpunit requires PHP 5.6
* Security support for 5.5 will run out in 3 months: http://php.net/supported-versions.php
* 16.04 stable release date is 21. April
* I've been deprecating a whole lot of other versions and wanted to do it all at once. Background is an upgraded CI build environmnet (Ubuntu 14.04) which does not ship older db versions anymore.
