### ISSUE TITLE
Cannot enable: `Unable to parse malformed url: http://` 

### ISSUE THREAD

**Issue by kuba-orlik** [owncloud/news#953]
* [x] I have read the [CONTRIBUTING.md](https://github.com/owncloud/news/blob/master/CONTRIBUTING.md) and followed the provided tips

## Explain the Problem
I cannot enable the News app. An error message saying `Unable to parse malformed url: http://` shows up.

## Steps to Reproduce
Explain what you did to encounter the issue
1. Log in as admin
2. Go to `/settings/apps?category=multimedia`
3. Find "News" and click "Enable"
3. An error message show up: 

```
Unable to parse malformed url: http://
```

## System Information

**I'm using OwnCloud's Docker container, version 9.0.0**

* News app version: 8.0.0
* ownCloud version: 9.0.0
* PHP version: 5.6
* Database and version: SQLite
* Browser and version: Firefox 45.0
* Distribution and version:  Ubuntu 14.04.3 LTS

## Contents of owncloud/data/owncloud.log

```json
{"reqId":"n1lklqi7gSS8oG9ovZh3","remoteAddr":"188.146.134.121","app":"PHP","message":"Undefined index: extension at \/var\/www\/html\/lib\/private\/installer.php#272","level":3,"time":"2016-03-28T09:38:31+00:00"}
{"reqId":"n1lklqi7gSS8oG9ovZh3","remoteAddr":"188.146.134.121","app":"core","message":"Unable to parse malformed url: http:\/\/","level":3,"time":"2016-03-28T09:38:31+00:00"}
```

## Contents of Browser Error Console
No errors

**Comment by BernhardPosselt** [comment]
See this issue https://github.com/owncloud/appstore-issues/issues/55

For now, download the package from the github releases page (news.tar.gz) https://github.com/owncloud/news/releases/tag/8.0.0

**Comment by kuba-orlik** [comment]
Thank you for your response. I've downloaded the `news.tar.gz` file into the docker container and unpacked it into `/var/www/html/apps`, so there's a `news` directory owned by the `www-data` user, but I still cannot enable the application - the same error appears:

    Unable to parse malformed url: http://

What am I missing?

**Comment by BernhardPosselt** [comment]
Can you try to extract it to /var/www/html/owncloud/apps ? I'm unsure if a separarte apps directory is supported. Works for me when using a fresh install btw.

**Comment by benediktg** [comment]
For me the workaround with manually download the app and activating it with
```
sudo -u www-data php /var/www/owncloud/occ app:enable news
```
did the job. It seems to work with the news folder owned by root – or is it better if I give the ownership to www-data?

**Comment by BernhardPosselt** [comment]
www-data otherwise core can't update/delete the app

**Comment by BernhardPosselt** [comment]
It seems that the correct download is now online, can you check? Probably caching issues on the appstore's side

**Comment by kuba-orlik** [comment]
I tried enabling it now and it shows another error: 
    
    App can't be installed because the version in info.xml/version is not the same as the version reported from the app store

**Comment by BernhardPosselt** [comment]
OK, this happens because the uploaded archive does not overwrite the old one, nothing I can do

**Comment by kuba-orlik** [comment]
Ok, I managed to enable the app via the [terminal command](https://github.com/owncloud/news/issues/953#issuecomment-202626365). Thanks! :)

**Comment by BernhardPosselt** [comment]
Closing this on favor of #958 which has a better description
