### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by openmatl** [owncloud/news#954]
* [x] I have read the [CONTRIBUTING.md](https://github.com/owncloud/news/blob/master/CONTRIBUTING.md) and followed the provided tips

## Explain the Problem
What problem did you encounter?
1. Downloaded news app as zip file from github
2. Unziped file on server
3. Enabled the app in my owncloud
4. Update was not successful:
`Updating ownCloud to version 9.0.0, this may take a while.

Preparing update
Set log level to debug
Turned on maintenance mode
Checking whether the database schema can be updated (this can take a long time depending on the database size)
Checked database schema update
Checking updates of apps
Checked database schema update for apps
Updating database schema
Updated database
An error occurred.`

## Steps to Reproduce
Explain what you did to encounter the issue
1. 
2. 
3. 
4. 

## System Information
* News app version: 8.0.0
* ownCloud version: 9.0.0
* PHP version: 7.0.4
* Database and version: mysqld 10.1.13-MariaDB
* Browser and version: Firefox 45.0.1
* Distribution and version: Windows / AntergOS

## Contents of owncloud/data/owncloud.log

```json

Log is currently damaged. Sorry, but nothing to see here.

```

**Comment by BernhardPosselt** [comment]
You've downloaded the source file which starting with 8.0.0 does not contain thirdparty libs and compiled JavaScript anymore. Either you build it manuall (see https://github.com/owncloud/news/blob/master/CONTRIBUTING.md#how-to-set-up-a-development-environment) or download the news.tar.gz here https://github.com/owncloud/news/releases/tag/8.0.0  

It's mentioned in the changelog btw ;)

**Comment by openmatl** [comment]
Oh I overlooked that the zip-files is not precompiled. It's now working again. Thanks for your help and sorry for the inconvenience. ;-)

Regards
matl
