### ISSUE TITLE
Short Description

### ISSUE THREAD

**Issue by aspdye** [owncloud/news#956]
Change this repositories Short Description to: :newspaper: News app for ownCloud

**Comment by BernhardPosselt** [comment]
I can't because I don't have admin rights for the repo, summoning @DeepDiver1975 @MorrisJobke 

Probably would go for a description that mentions RSS and atom however ;)

**Comment by MorrisJobke** [comment]
Maybe @icewind1991 or @butonic could help out here ;)

**Comment by MorrisJobke** [comment]
@icewind1991 fixed it :)
