### ISSUE TITLE
Authentication error CloudNotes/CloudNews/QOwnNotes

### ISSUE THREAD

**Issue by handswork** [owncloud/news#960]
Hi,

I would like report a issue, I will just link to the original report

See this;
https://github.com/owncloud/core/issues/23739

Thanks

**Comment by BernhardPosselt** [comment]
Sorry, does not make sense to duplicate this issue 3 times since this looks like a core and ldap issue (since you've mentioned that new users work just fine). There's nothing I can do to fix this in this app, therefore closing ;)

Bug should be handled in the intial core repo

**Comment by handswork** [comment]
That's fine, I'm not a programmer and did just what I was told :)

**Comment by handswork** [comment]
It seems that upgrading to php7 from php5.6 and reinstalling redis for php7 solve the issue
It also solve some issues I had with the news app on the web interface. I had some issues activating the app. And it solved a cronjob issue I also had.

**Comment by BernhardPosselt** [comment]
Great to hear :)

Thans for the infos, will be helpful for other users
