### ISSUE TITLE
Update to 8.1.0 failed

### ISSUE THREAD

**Issue by LIyoai** [owncloud/news#961]
## Explain the Problem
When I try to update from 7.1.2 to 8.1.0 I get the message 
`App can't be installed because the version in info.xml/version is not the same as the version reported from the app store`

## Steps to Reproduce
Explain what you did to encounter the issue
1. Login to OwnCloud
2. Go to Apps
3. Update to 8.1.0

## System Information
* News app version: 7.1.2
* ownCloud version: 9.0.0
* PHP version: 5.6.17
* Database and version: MySQL 5.5.47
* Browser and version: Firefox 45
* Distribution and version: Debian 8

apps/news/appinfo/info.xml
`<version>7.1.2</version>`

**Comment by BernhardPosselt** [comment]
DUP of #958
