### ISSUE TITLE
App not updating

### ISSUE THREAD

**Issue by n00b12345** [owncloud/news#963]
I just update OC from 8.2 to 8.2.3 (stable channel, updated from web UI). News app version currently installed is - 7.1.2. 

I'm getting a new button asking me to update the News app to 8.1.0 but upon pressing it, this is what I get - "App can't be installed because it is not compatible with this version of ownCloud". 

Could you please help?

**Comment by BernhardPosselt** [comment]
8.0.0 requires owncloud 9

**Comment by n00b12345** [comment]
Oh! I got confused because the notification to update the app came up. Sorry about this.
