### ISSUE TITLE
 Add URL to subscribe to feed [feature_request]

### ISSUE THREAD

**Issue by selivan** [owncloud/news#964]
* [x] I have read the [CONTRIBUTING.md](https://github.com/owncloud/news/blob/master/CONTRIBUTING.md) and followed the provided tips

I use Chrome [RSS subscription extension](https://chrome.google.com/webstore/detail/rss-subscription-extensio/nlbjncdgjeocebhnmkbbbdekmmmcbfjd). Only option to handle RSS is to subscribe with Bloglines, but extension also supports custom URLs. It would be useful to have such URL in News app, something like `https://owncloud.example.net/index.php/app/news?subscribe=%s`, where `%s` is feed address.

**Comment by BernhardPosselt** [comment]
Try ?subscribe_to=%s instead ?subscribe=%s

**Comment by selivan** [comment]
It works, thank you :+1: 

May be it would be useful to mention this somewhere in help tip in news interface? It is not obvious now.

**Comment by BernhardPosselt** [comment]
It's registered for the rss feed, unfortunately chrome does not support this feature I suppose https://github.com/owncloud/news/blob/master/js/gui/ExternSubscription.js#L46

**Comment by selivan** [comment]
No, I mean something like adding "Subscribe URL" below "Keyboard shortcuts" in Settings drawer(that is opened with little gear button). It will open pop-up with instruction about `?subscribe_to=%s` and may be links to required Chrome and Firefox extensions.

**Comment by BernhardPosselt** [comment]
Does this usually have to be accessed by users? If not I'd put it into the developer wiki section instead

**Comment by selivan** [comment]
If somebody is using News app, it probably means he/she uses RSS often, and probably would like to have subscribe action more convenient with less steps to make. Well, I suppose so.

**Comment by BernhardPosselt** [comment]
Yeah what I mean is: Is this mainly developer information for writing plugins/apps that interface with the News app or is this something a normal user needs?

**Comment by selivan** [comment]
I think that this may be useful for normal users.

**Comment by BernhardPosselt** [comment]
ok, marking this as enhancment :)

Would you like to give it a try?

**Comment by selivan** [comment]
I am not a web developer, but I will look at it when I have free time. Seems to be easy.

**Comment by BernhardPosselt** [comment]
Here's the template: https://github.com/owncloud/news/blob/master/templates/part.settings.php#L10

I'd just clone the keyboard settings section and add an input field. I will take over the JS part and fill it with the correct url ;)

**Comment by BernhardPosselt** [comment]
Or wait, I'll implement it ;)

**Comment by BernhardPosselt** [comment]
I've added a link to the documentation/wiki and added it there. Adding the full URL and explanation in the settings area was too much, loading a separate page like for the shortcuts was too little content. Apart from that this has the added benefit, that people will be able to launch the docs very quickly

**Comment by selivan** [comment]
@BernhardPosselt: I got backward idea about how to do it better. Add (?) icon next to (gear) icon. It will show pop-up with help both about keys and URL for adding new bookmark, and also it will have link to wiki. User needs less actions to get help (it's not obvious that it is hidden inside "configure"), interface becomes more clear and compact. IMHO.

**Comment by BernhardPosselt** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
Is it a subscribe bookmarklet? Then it should go into the bottom left settings section.

**Comment by BernhardPosselt** [comment]
Something like that, yeah. Did not think about the bookmarklet functionality, but sounds reasonable xD

**Comment by BernhardPosselt** [comment]
@jancborchardt oh, my bad :D 
OP is asking specifically asks for the URL which he then wants to copy into settings of various browser addons

**Comment by BernhardPosselt** [comment]
Closing because of a misunderstanding :)

Also we dropped the subscriblet as an enhancement way back then
