### ISSUE TITLE
PHP Version incompatible with Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by aproposnix** [owncloud/news#967]
# IMPORTANT

Read and tick the following checkbox after you have created the issue or place an x inside the brackets ;)

* [x ] I have read the [CONTRIBUTING.md](https://github.com/owncloud/news/blob/master/CONTRIBUTING.md) and followed the provided tips

## Explain the Problem
Since upgrading the server (Ubuntu 14.04) and files to v9.0.1 OC News no longer works. When I go to the apps store page in see the following error in the OC News app: 

> This app cannot be installed because the following dependencies are not fulfilled:
> PHP 5.6 or higher is required.

I fully understand that you have switched to a newer version of PHP which is not supported by Ubuntu 14.04.  The issue was that I was given no warning at all and the app was automatically updated to 8.2.0 (which is backwards incompatible if I understand correctly) when I updated the server. 

How do I revert back to the pre-8.2.x version? Since this version is not backwards compatible, will I have to completely remove OC News before downgrading?  If so, how can I save my feeds? 

## Steps to Reproduce
Explain what you did to encounter the issue
1. Upgrade to OC 9.0.1 on an Ubuntu 14.04 server
2. Try to enable News
3. See PHP version error

## System Information
* News app version:8.2.x
* ownCloud version: 9.0.1
* PHP version: PHP 5.5.9-1ubuntu4.14
* Database and version: MySQL Ver 14.14 Distrib 5.5.47
* Browser and version: Chrome 49.0.2623.112 (64-bit)
* Distribution and version: Ubuntu 14.04 LTS

**Comment by BernhardPosselt** [comment]
Two solutions: either install a newer php version on 14.04 or download an older news version on the the releases page. Instructions are in the readme

**Comment by BernhardPosselt** [comment]
This is the last working version using PHP 5.5 https://github.com/owncloud/news/releases/tag/7.1.2

Here's the section how to install it https://github.com/owncloud/news#installing-from-archive

**Comment by hifigraz** [comment]
What was the main reason for switching to php 5.6? Do you think patching the news app so that it works with php 5.5 again is a big task? I would help if wanted.

**Comment by BernhardPosselt** [comment]
Check https://github.com/owncloud/news/issues/970#issuecomment-208875205

It's mainly a support and time issue as in: libraries, different functions, CI where you have to make special adjustments for 5.5.

Sure you could patch 5.5 support back in once which will fix it for now, however this will be a constant effort to keep the 5.5 compatibility. Given that 5.5 will run out of mainline security support in 2 months, I don't think it's worth the trouble.  

@hifigraz are you willing to provide php 5.5 support? As in creating a branch or fork which keeps up with the changes and fixes all the 5.5 issues?
