### ISSUE TITLE
Releases without git in vendor

### ISSUE THREAD

**Issue by xf-** [owncloud/news#973]
Noticed 8.5.0 release (tar.gz) gone from old releases < 950KB to 13,2MB.
Build releases without .git e.g. with `composer install --prefer-dist`.

**Comment by BernhardPosselt** [comment]
Releases are built automatically by Travis, no idea why it uploaded the whole thing

**Comment by BernhardPosselt** [comment]
Should be fixed now, can you check?

**Comment by xf-** [comment]
fixed :)
