### ISSUE TITLE
old news are newest since last update

### ISSUE THREAD

**Issue by jajaX** [owncloud/news#974]
Hi (sorry for my bad english !) 

# IMPORTANT

Read and tick the following checkbox after you have created the issue or place an x inside the brackets ;)

* [ ] I have read the [CONTRIBUTING.md](https://github.com/owncloud/news/blob/master/CONTRIBUTING.md) and followed the provided tips

## Explain the Problem
What problem did you encounter?

since last update (8.50), old news (one/two year) are newest again !

see this image =>

http://pix.toile-libre.org/upload/original/1460720742.jpg

## Steps to Reproduce
Explain what you did to encounter the issue
1.go to "news"
2.see unread article
3.see older news who date one or two year

## System Information
* News app version: 8.50
* ownCloud version:9.01
* PHP version: PHP 5.6.20-1+deb.sury.org~trusty+1
* Database and version: mysql 5.5.47
* Browser and version: google chrome 50.0.2661.75 (64-bit)
* Distribution and version: Kubuntu 14.04.1 (64 bits)

## Contents of owncloud/data/owncloud.log

```json

Paste output here

```

## Contents of Browser Error Console
Read http://ggnome.com/wiki/Using_The_Browser_Error_Console if you are unsure what to put here

```

Paste output here

```

**Comment by BernhardPosselt** [comment]
They are listed on top because your feed published them ;)

From which version did you upgrade? 8.3.0 renamed the http caching columns, so they simply reappeared once :)

**Comment by jajaX** [comment]
ok. good :)
