### ISSUE TITLE
App "News" cannot be installed because the following dependencies are not fulfilled: PHP 5.6 or higher is required.

### ISSUE THREAD

**Issue by Apkahym** [owncloud/news#976]
`# php -v
PHP 7.0.5-2+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
`

Why i have this error?

**Comment by BernhardPosselt** [comment]
I'd guess that the PHP cli launches a newer/different version than your webserver

**Comment by BernhardPosselt** [comment]
I'm running PHP 7 locally and I don't get that error message

**Comment by Apkahym** [comment]
I have solved, i forget some php7.0 libraries. Thanks
