### ISSUE TITLE
Expose failing feed updates over API

### ISSUE THREAD

**Issue by Pantos** [owncloud/news#977]
* [x] I have read the [CONTRIBUTING.md](https://github.com/owncloud/news/blob/master/CONTRIBUTING.md) and followed the provided tips

I'm using my android app to read news articles. So in the past I didn't noticed when a feed couldn't be updated/fetched. Is it possible to implement a mail notification if the feed update failed for a longer time? At the moment there is a notification in the news app only...

Thanks for such a great app!!

**Comment by BernhardPosselt** [comment]
So basically we should also expose these update errors through the API so that your Android app will notify you of feeds that failed to update.

As for Mail: This will only spam your Inbox, so I think handling this through the API is a better way to do this.

**Comment by Pantos** [comment]
Notification via API sounds good.

Concerning mail: I thought of sending notification mails if a breakpoint (eg. 50 failed updates...) is reached. But I think your way is the better one...
