### ISSUE TITLE
[oc News 8.7.1] News App Prompts Firefox for Master Password

### ISSUE THREAD

**Issue by zirydy** [owncloud/news#980]
## Explain the Problem
I just installed ownCloud 9.0.1 and realized that the News App triggers a Master Password prompt in Firefox, even when I'm already logged into ownCloud.

This didn't happen in News App 7.1.2 on ownCloud 8.2 so I'm wondering if it might be a bug? even if a very minor one.

## Steps to Reproduce
1. Install ownCloud 9.0.1 and News App 8.7.1
2. Log into ownCloud on Firefox
3. Go to News App
4. Firefox Asks for the Master Password
(ownCloud Username and Password must saved in Firefox with a Master Password)

## System Information
* News app version: 8.7.1
* ownCloud version: 9.0.1
* PHP version: 5.6
* Database and version: MySQL 5.5.47
* Browser and version: Firefox 45.0.2
* Distribution and version: Ubuntu 15.10

**Comment by BernhardPosselt** [comment]
Sometimes the master password question in Firefox is delayed a bit. I'd try to clear all passwords. If this is a bug, the bug is in core, therfore closing
