### ISSUE TITLE
News update on hosted webspace impossible

### ISSUE THREAD

**Issue by frederikheld** [owncloud/news#986]
# IMPORTANT

Read and tick the following checkbox after you have created the issue or place an x inside the brackets ;)

* [x] I have read the [CONTRIBUTING.md](https://github.com/owncloud/news/blob/master/CONTRIBUTING.md) and followed the provided tips

## Explain the Problem
While OC is getting better and better to be installed and run on hosted webspaces, you decided to make the News app useless on such environents. I can't run system cron and I can't run python scripts. A quite common setting for hosting packages.

I would be really happy to see News updates via webcron back in the next version of this app.

Thanks for the wonderful app anyway, but this version is absolutely useless for me :-(

## System Information
* News app version: 8.7.1
* ownCloud version: 9.0.1

**Comment by BernhardPosselt** [comment]
See https://github.com/owncloud/news/issues/971#issuecomment-210620289

Basically someone could build upon this, no one is interested in working on it yet however

**Comment by BernhardPosselt** [comment]
Apart from that Webcron is available through the updater API. You can install the news-updater on any machine with internet access and Python 3 (even on a 5$ raspberry pi)

**Comment by frederikheld** [comment]
Thanks for the hint @BernhardPosselt! In fact I do have a RasPi running with an LDAP directory for an OC instance. But this is not for my private instance and I don't want to mix things up. And to set up a RasPi just to update the News app adds a lot of complexity that shouldn't be necessary :-P
