### ISSUE TITLE
Mismatch in autoPurgeCount description

### ISSUE THREAD

**Issue by FriedCircuits** [owncloud/news#987]
Hi,

Just wanted to point out that the description for what the Auto Purge does is different on Github verses the admin panel. Which is correct? Unread or read?

Github:
autoPurgeCount: Defines the minimum amount of articles that can be unread per feed before they get deleted, a negative value will turn off deleting articles completely

Admin panel:
Maximum read count per feed
Defines the maximum amount of articles that can be read per feed which won't be deleted by the cleanup job; if old articles reappear after being read, increase this value; negative values such as -1 will turn this feature off completely

In my case I would want unread or stared to never to be deleted but old read articles could be deleted but possible time based and or the count as is now.

**Comment by BernhardPosselt** [comment]
Readme is wrong, can you create a pull request for the readme with the same contents as the admin panel?
