### ISSUE TITLE
Key navigation broken in compact view

### ISSUE THREAD

**Issue by dbeniamine** [owncloud/news#988]
# Description

I upgraded Owncloud to version 9.0.2 this morning (from 9.0.1) and news app to 8.7.3. Since these upgrades, when I navigate with j/n keys in compact view with expand articles on key navigation checked the first key goes to the next article without expanding it, and the second scrolls down one page.

The navigations works perfectly in not compact mod or without auto expansion (pressing `j` then `e`).

I can reproduce the issue with Firefox and chromium

# Steps to Reproduce

1. Set compact view and expand articles on key navigation
2. Select an article
3. Hit `j` once
4. The next article is not expanded, Hitting `j` again will scroll one page

## System Information
* News app version: 8.7.3
* ownCloud version: 9.0.2
* PHP version: 5.6.20-0+deb8u1
* Database and version: mysql Ver 14.14 Distrib 5.5.49
* Browser and version: Firefox 45.0.2 / Chromium 49.0.2623.108
* Distribution and version: Debian Jessie 

## Contents of Browser Error Console

```
Content Security Policy: Directive 'frame-src' has been deprecated. Please use directive 'child-src' instead. <unknown>
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://myowncloud.fndn.something 'unsafe-eval'"). news
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create es6-shim.min.js:10:23991
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create panel.js:5813:3
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ panel.js:3522:3 not well-formed
```

**Comment by BernhardPosselt** [comment]
Fixed

**Comment by dbeniamine** [comment]
I confirm that It works just fine on 8.7.4, thanks for your (very quick) fix !
