### ISSUE TITLE
Something goes wrong on upgrading

### ISSUE THREAD

**Issue by paroj** [owncloud/news#989]
# IMPORTANT

Read and tick the following checkbox after you have created the issue or place an x inside the brackets ;)

* [x] I have read the [CONTRIBUTING.md](https://github.com/owncloud/news/blob/master/CONTRIBUTING.md) and followed the provided tips

## Explain the Problem
The following error appears in the log when updating the news app. Note that this was not just introduced with the most recent update, but its just me finally reporting this.

## Steps to Reproduce
Explain what you did to encounter the issue
1. update the news app using the owncloud updater
2. check the log

## System Information
* News app version: 8.7.4
* ownCloud version: 9.0.2
* PHP version: 7.0.5
* Database and version:
* Browser and version:
* Distribution and version:

## Contents of owncloud/data/owncloud.log

```json
{"reqId":"qrODXNeGf59YH0Hh67UI","remoteAddr":"192.168.178.xx","app":"PHP","message":"unlink(): No such file or directory at \/var\/www\/owncloud\/lib\/private\/helper.php#227","level":3,"time":"2016-05-05T16:36:50+02:00","method":"POST","url":"\/index.php\/settings\/ajax\/updateapp.php","user":"me"}
{"reqId":"qrODXNeGf59YH0Hh67UI","remoteAddr":"192.168.178.xx","app":"PHP","message":"rmdir(\/tmp\/oc_tmp_56egK8-folder\/news\/vendor\/bin): Directory not empty at \/var\/www\/owncloud\/lib\/private\/helper.php#225","level":3,"time":"2016-05-05T16:36:50+02:00","method":"POST","url":"\/index.php\/settings\/ajax\/updateapp.php","user":"me"}
{"reqId":"qrODXNeGf59YH0Hh67UI","remoteAddr":"192.168.178.xx","app":"PHP","message":"rmdir(\/tmp\/oc_tmp_56egK8-folder\/news\/vendor): Directory not empty at \/var\/www\/owncloud\/lib\/private\/helper.php#225","level":3,"time":"2016-05-05T16:36:50+02:00","method":"POST","url":"\/index.php\/settings\/ajax\/updateapp.php","user":"me"}
{"reqId":"qrODXNeGf59YH0Hh67UI","remoteAddr":"192.168.178.xx","app":"PHP","message":"rmdir(\/tmp\/oc_tmp_56egK8-folder\/news): Directory not empty at \/var\/www\/owncloud\/lib\/private\/helper.php#225","level":3,"time":"2016-05-05T16:36:50+02:00","method":"POST","url":"\/index.php\/settings\/ajax\/updateapp.php","user":"me"}
{"reqId":"qrODXNeGf59YH0Hh67UI","remoteAddr":"192.168.178.xx","app":"PHP","message":"rmdir(\/tmp\/oc_tmp_56egK8-folder): Directory not empty at \/var\/www\/owncloud\/lib\/private\/helper.php#231","level":3,"time":"2016-05-05T16:36:50+02:00","method":"POST","url":"\/index.php\/settings\/ajax\/updateapp.php","user":"me"}
```

## ls /tmp/oc_tmp_56egK8-folder/news/vendor/bin/

```
picofeed
```

**Comment by BernhardPosselt** [comment]
Not a news issue, delete the directory and try again

**Comment by paroj** [comment]
yes, thats what I did the last updates before opening this issue. Any idea where/ if this is tracked?

**Comment by BernhardPosselt** [comment]
No idea. If it is it should be in the core repo
