### ISSUE TITLE
Make a cache for feed favicons and serve them from owncloud server

### ISSUE THREAD

**Issue by Revertron** [owncloud/news#991]
# IMPORTANT

Read and tick the following checkbox after you have created the issue or place an x inside the brackets ;)

* [x] I have read the [CONTRIBUTING.md](https://github.com/owncloud/news/blob/master/CONTRIBUTING.md) and followed the provided tips

## Explain the Problem
The favicons are loaded every time from sites of the feeds. It would be better to load them and save to some cache folder and link to that folder on owncloud server. It would be more secure.

## System Information
* News app version: 8.7.4
* ownCloud version: 9.0.2
* PHP version: 5.6
* Database and version: mysql 5.5
* Browser and version: Firefox 46.0.1
* Distribution and version: Debian jessie

## Contents of Browser Error Console
Read http://ggnome.com/wiki/Using_The_Browser_Error_Console if you are unsure what to put here

```

Did you see even one time how much problems are there?

```

**Comment by BernhardPosselt** [comment]
Nope, actually it would be less secure since the same origin policy would be defeated :)

Did you read https://github.com/owncloud/news#my-browser-shows-a-mixed-content-warning-connection-is-not-secure ?
