### ISSUE TITLE
Make a button on main owncloud bar for "Mark as read"

### ISSUE THREAD

**Issue by Revertron** [owncloud/news#992]
Did you see the big button "Mark all as read" in inoreader, for example?
It is much comfortable to click that button instead of pressing shift+a.

**Comment by BernhardPosselt** [comment]
There is a button, click the 3 dots and hit the checkmark icon ;)

**Comment by Revertron** [comment]
You name it useful like this? I know about that micro-option in that menu.

**Comment by BernhardPosselt** [comment]
So what's the issue? Just enable the mark read on scroll option or use the keyboard shortcut if you want an immediate effect

**Comment by Revertron** [comment]
Mark on scroll on list-mode? O_o
I want the button on upper-bar. Is it possible at all or owncloud doesn't give such possibility?

**Comment by BernhardPosselt** [comment]
It was a design decision to implement it like this. Early versions had the button on top, but it was incorporated into the menu at some point. There will not be a button on top. If you want to use the app in the most efficient manner, use keyboard shortcuts instead (If two clicks are too much for you for marking items as read).

**Comment by Revertron** [comment]
Most efficient manner for me is drinking a cup of coffee in one hand and clicking one big button after going through titles of feed-items in compact mode. Isn't it efficient?
