### ISSUE TITLE
Error downloading news, seems related to encoding

### ISSUE THREAD

**Issue by flixman** [owncloud/news#994]
# IMPORTANT

Read and tick the following checkbox after you have created the issue or place an x inside the brackets ;)

* [x] I have read the [CONTRIBUTING.md](https://github.com/owncloud/news/blob/master/CONTRIBUTING.md) and followed the provided tips

## Explain the Problem
In the news app I am downloading some news feeds, but some of the news do not appear in the app. 

## Steps to Reproduce
Explain what you did to encounter the issue
1. Just download the RSS feeds from the app.
2.
3.

## System Information
* News app version: 8.7.4
* ownCloud version: 9.0.1
* PHP version: 5.6.20-1
* Database and version: mysql  Ver 14.14 Distrib 5.6.30, for debian-linux-gnu (x86_64)                                                                                                                         
* Browser and version: Firefox 49.0a1 nightly
* Distribution and version: Debian testing

## Contents of owncloud/data/owncloud.log

{"reqId":"krZNCzqqSOJIr9nrfaZh","remoteAddr":"","app":"news","message":"Unexpected error when updating feed An exception occurred while executing 'INSERT INTO `oc_news_items`(`status`,`url`,`guid`,`guid_hash`,`pub_date`,`last_modified`,`rtl`,`title`,`author`,`body`,`search_index`,`fingerprint`,`feed_id`) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)' with params [2, \"http:\\\/\\\/gaussianos.com\\\/no-los-experimentos-aleatorios-independientes-no-tienen-memoria\\\/\", \"9992da9edf04b4a273c864a622c0ec17\", \"9992da9edf04b4a273c864a622c0ec17\", 1460979000, 1463031004, false, \"No, los experimentos aleatorios independientes no tienen memoria\", \"^DiAmOnD^\", \"<p><strong>\\u201cCuanto m\\u00e1s llevas sin ganar, m\\u00e1s probable es que ganes el siguiente\\u201d<\\\/strong>. Esta afirmaci\\u00f3n, que podr\\u00eda parecer cierta, en realidad no tiene mucho sentido en t\\u00e9rminos de probabilidad. En los pr\\u00f3ximos p\\u00e1rrafos analizaremos el porqu\\u00e9.<br \\\/>Antes de comenzar, quiero dejar claras las condiciones del tema que vamos a comentar. Lo que sigue se refiere a experimentos aleatorios <strong>independientes<\\\/strong> (es decir, su resultado en un momento dado no influye en el resultado del mismo experimento en otro momento, como puede pasar al lanzar un dado o una moneda) con un n\\u00famero finito de resultados en el que conocemos la probabilidad de cada uno de ellos.<\\\/p>\\n<p><img src=\\\"http:\\\/\\\/gaussianos.com\\\/wp-content\\\/uploads\\\/2016\\\/04\\\/dados.jpg\\\" alt=\\\"dados.jpg\\\" \\\/><\\\/p>\\n<p>Vamos al tema. Esta entrada me vino a la mente despu\\u00e9s de ver un tuit del famoso tuitero deportivo <strong><a target=\\\"_blank\\\" rel=\\\"noreferrer\\\" href=\\\"https:\\\/\\\/twitter.com\\\/2010MisterChip\\\">@2010MisterChip<\\\/a><\\\/strong>. Otro tuitero, <strong><a target=\\\"_blank\\\" rel=\\\"noreferrer\\\" href=\\\"https:\\\/\\\/twitter.com\\\/ScottiePeppino\\\">@ScottiePeppino<\\\/a><\\\/strong>, le comentaba lo siguiente a ra\\u00edz de una apuesta que el primero hab\\u00eda realizado:<\\\/p>\\n<blockquote><p><a target=\\\"_blank\\\" rel=\\\"noreferrer\\\" href=\\\"https:\\\/\\\/twitter.com\\\/2010MisterChip\\\">@2010MisterChip<\\\/a> hombre, siendo un hombre de estad\\u00edsticas como eres, apostar por el equipo que lleva sin ganar en ese estadio 30 partidos\\u2026<\\\/p>\\n<p>\\u2014 Scottie Peppino (@ScottiePeppino) <a target=\\\"_blank\\\" rel=\\\"noreferrer\\\" href=\\\"https:\\\/\\\/twitter.com\\\/ScottiePeppino\\\/status\\\/719317801593384962\\\">11 de abril de 2016<\\\/a><\\\/p><\\\/blockquote>\\n\\n<p>A lo que MisterChip contestaba lo siguiente<\\\/p>\\n<blockquote><p>Cuanto m\\u00e1s llevas sin ganar, m\\u00e1s probable es que ganes el siguiente. Estad\\u00edstica pura y dura <img src=\\\"https:\\\/\\\/s.w.org\\\/images\\\/core\\\/emoji\\\/72x72\\\/1f609.png\\\" alt=\\\"\\ud83d\\ude09\\\" \\\/><a target=\\\"_blank\\\" rel=\\\"noreferrer\\\" href=\\\"https:\\\/\\\/t.co\\\/ylyJpoVa6g\\\">https:\\\/\\\/t.co\\\/ylyJpoVa6g<\\\/a><\\\/p>\\n<p>\\u2014 MisterChip (Alexis) (@2010MisterChip) <a target=\\\"_blank\\\" rel=\\\"noreferrer\\\" href=\\\"https:\\\/\\\/twitter.com\\\/2010MisterChip\\\/status\\\/719318153831059456\\\">11 de abril de 2016<\\\/a><\\\/p><\\\/blockquote>\\n\\n<p>Si acced\\u00e9is al mismo pod\\u00e9is ver mi respuesta<\\\/p>\\n<blockquote><p><a target=\\\"_blank\\\" rel=\\\"noreferrer\\\" href=\\\"https:\\\/\\\/twitter.com\\\/2010MisterChip\\\">@2010MisterChip<\\\/a> Esto\\u2026Hablando de azar (si citas \\\"estad\\u00edstica\\\" supongo que te refieres a eso), lo que has dicho no es para nada correcto<\\\/p>\\n<p>\\u2014 gaussianos (@gaussianos) <a target=\\\"_blank\\\" rel=\\\"noreferrer\\\" href=\\\"https:\\\/\\\/twitter.com\\\/gaussianos\\\/status\\\/719325690596892672\\\">11 de abril de 2016<\\\/a><\\\/p><\\\/blockquote>\\n\\n<p>y algunas m\\u00e1s de otros tuiteros. Todos intent\\u00e1bamos hacerle ver que hab\\u00eda ca\\u00eddo en una famosa falacia estad\\u00edstica, pero, hasta el d\\u00eda de hoy, la \\u00fanica respuesta que he visto de MisterChip es la siguiente (si hay alguna m\\u00e1s dec\\u00eddmelo):<\\\/p>\\n<blockquote><p>Cambia \\\"jugador\\\" por \\\"mal jugador\\\" y estaremos de acuerdo. <a target=\\\"_blank\\\" rel=\\\"noreferrer\\\" href=\\\"https:\\\/\\\/t.co\\\/03oXVSLo9H\\\">https:\\\/\\\/t.co\\\/03oXVSLo9H<\\\/a><\\\/p>\\n<p>\\u2014 MisterChip (Alexis) (@2010MisterChip) <a target=\\\"_blank\\\" rel=\\\"noreferrer\\\" href=\\\"https:\\\/\\\/twitter.com\\\/2010MisterChip\\\/status\\\/719319236674498560\\\">11 de abril de 2016<\\\/a><\\\/p><\\\/blockquote>\\n\\n<p>Si analizamos el tema de manera probabil\\u00edstica (entiendo que \\u00e9sa era la intenci\\u00f3n de MisterChip al hablar de \\u201cestad\\u00edstica\\u201d), el asunto es como sigue: estamos ante un experimento aleatorio con dos posibles resultados (victoria de equipo de casa o victoria del equipo visitante, no consideramos el empate) en el que tenemos la probabilidad de cada uno de ellos (se podr\\u00eda hablar de c\\u00f3mo se determinan dichas probabilidades, pero eso es otro tema). Adem\\u00e1s, dichos resultados son independientes.<\\\/p>\\n<p>Si realizamos el experimento, podemos obtener cualquiera de los dos resultados. Imaginemos que gana el equipo de casa. Si volvemos a realizar el experimento, la pregunta es la siguiente: <strong>\\u00bfha aumentado la probabilidad de que gane el equipo visitante?<\\\/strong> La respuesta es <strong>NO<\\\/strong>. Para hacer un an\\u00e1lisis probabil\\u00edstico correcto, en este caso <strong>tenemos que considerar que el resultado obtenido en un enfrentamiento no influye en lo que pasar\\u00e1 en el enfrentamiento siguiente<\\\/strong> (los resultados son <strong>independientes<\\\/strong>).<\\\/p>\\n<p>La creencia de que muchos resultados \\u201chacia un lado\\u201d aumentan la probabilidad de que en la siguiente ocasi\\u00f3n la cosa ir\\u00e1 \\u201chacia el otro lado\\u201d o, m\\u00e1s en general, que los resultados obtenidos influyen en los siguientes (vamos, que el juego \\u201ctiene memoria\\u201d) se denomina <strong>falacia del jugador<\\\/strong>. Uno de los ejemplos m\\u00e1s conocidos de esta falacia es el caso que se dio el 18 de agosto de 1913 en una de las ruletas del casino de Monte Carlo. En aquella ocasi\\u00f3n, la bolita cay\\u00f3 la friolera de \\u00a1\\u00a126 veces seguidas!! en el negro. Lo que ocurri\\u00f3 es que, a medida que iban saliendo \\u201cnegros\\u201d, los jugadores iban apostando cada vez m\\u00e1s al \\u201crojo\\u201d, porque entend\\u00edan que con tantas apariciones del negro era mucho m\\u00e1s probable que en la siguiente tirada saliera rojo. Y no, esto no es as\\u00ed: <strong>la probabilidad de rojo no aumentaba<\\\/strong> en este caso. Tomando la ruleta como un juego de probabilidades, y dando un 0.5 al rojo y un 0.5 al negro (esto no exacto, pero para el caso en el que estamos nos vale), esas probabilidades se mantienen en cada tirada independientemente de lo que saliera en tiradas anteriores (la ruleta \\u201cno tiene memoria\\u201d). \\u00bfQu\\u00e9 ocurri\\u00f3? Pues no es dif\\u00edcil imaginarlo: el casino gan\\u00f3 much\\u00edsimo dinero en ese rato.<\\\/p>\\n<p>\\u00bfPor qu\\u00e9 entonces pensamos de esta err\\u00f3nea manera (y, si somos jugadores, tan perjudicial para nuestro bolsillo)? Pues porque <strong>tendemos a pensar que si los resultados anteriores se desv\\u00edan sustancialmente de lo que marcan las probabilidades, dicha desviaci\\u00f3n se corregir\\u00e1 pronto para dejarlo todo \\u201ccomo debe ser\\u201d<\\\/strong> (en este caso, mismo n\\u00famero de rojos que de negros). Eso es, a todas luces, falso. Y de este error por nuestra parte se aprovechan a veces los organizadores de este tipo de juegos, d\\u00e1ndonos, por ejemplo, los <em>n\\u00fameros calientes<\\\/em> y los <em>n\\u00fameros fr\\u00edos<\\\/em> (intentando as\\u00ed influir en nuestra percepci\\u00f3n sobre las probabilidades de cada n\\u00famero en la siguiente tirada). De hecho, en juegos tipo la ruleta, en una situaci\\u00f3n como \\u00e9sta de tantos \\u201cnegros\\u201d seguidos podr\\u00eda ser m\\u00e1s razonable pensar que dicha ruleta est\\u00e1 \\u201ctrucada\\u201d (premeditadamente o no, eso no es importante) para que salgan m\\u00e1s \\u201cnegros\\u201d que \\u201crojos\\u201d, por lo que quiz\\u00e1s tendr\\u00eda m\\u00e1s sentido volver a apostar al \\u201cnegro\\u201d en la tirada siguiente (esta forma de razonar se conoce como <em>principio de Hume<\\\/em>).<\\\/p>\\n<p>Y un \\u00faltimo detalle. Es tambi\\u00e9n interesante distinguir entre \\u201cn\\u00famero de veces que se ha producido cada resultado\\u201d y \\u201cprobabilidad de cada resultado\\u201d. Que las probabilidades sean iguales no significa, ni mucho menos, que conforme aumentamos el n\\u00famero de realizaciones del experimento las veces en las que sale cada resultado tiendan a igualarse. Voy a poner un ejemplo para intentar explicar qu\\u00e9 quiero decir:<\\\/p>\\n<blockquote><p>Imaginemos que tiramos una moneda 100 veces y salen 40 caras y 60 cruces. En este caso, llevar\\u00edamos un 40% de caras y un 60% de cruces. Imaginemos que seguimos tirando la monda y llegamos a 1000 tiradas, obteniendo 460 caras y 540 cruces. Las probabilidades se van acercando, 0.46 para \\u201ccara\\u201d y 0.54 para \\u201ccruz\\u201d, pero la distancia entre el n\\u00famero de veces de cada una es mayor (antes era 20 y ahora es 80).<\\\/p><\\\/blockquote>\\n<p>Recordad: la probabilidades en estos casos se calculan dividiendo casos favorables entre casos posibles. Por ello, aunque las probabilidades se vayan igualando, la diferencia de las veces que sale cada uno de los resultados puede ser cada vez mayor.<\\\/p>\\n\\n<p>Se ha escrito mucho sobre la falacia del jugador, y en internet pod\\u00e9is encontrar gran cantidad de art\\u00edculos sobre el tema. Os dejo \\u00e9ste del maestro <strong>Adri\\u00e1n Paenza<\\\/strong>: <a target=\\\"_blank\\\" rel=\\\"noreferrer\\\" href=\\\"http:\\\/\\\/www.pagina12.com.ar\\\/diario\\\/contratapa\\\/13-257349-2014-10-12.html\\\">La falacia del jugador<\\\/a>.<\\\/p>\\n\\n<p>Sobre la manera de determinar las probabilidades de cada uno de los resultados quer\\u00eda hacer un comentario. \\u00bfTiene sentido tomar los resultados anteriores entre ambos equipos para determinar dicha probabilidad? Si la respuesta es afirmativa, el hecho de que un equipo haya perdido los \\u00faltimos enfrentamientos directos deber\\u00eda entonces, bajo mi punto de vista, hacer que la probabilidad de victoria del \\u201cperdedor habitual\\u201d baje respecto a estimaciones anteriores, pero <strong>nunca<\\\/strong> que suba. Y si no lo veis, ah\\u00ed va un ejemplo:<\\\/p>\\n<blockquote><p>Imaginemos que el Granada ha perdido 20 veces seguidas en el Bernab\\u00e9u, y que \\u201csu\\u201d probabilidad de victoria era de 0.1. \\u00bfSignifica eso que si vuelven a jugar ahora en el Bernab\\u00e9u tienen una probabilidad mayor de ganar?<\\\/p><\\\/blockquote>\\n<p>Pues yo creo que no. A ver qu\\u00e9 pens\\u00e1is vosotros.<\\\/p>\\n\\n<p>Y sobre el hecho de que los resultados anteriores puedan influir en la mente de los jugadores del equipo \\u201cperdedor habitual\\u201d, cabr\\u00edan las dos posibilidades. Podr\\u00eda ser de manera positiva (m\\u00e1s ganas de romper la mala racha) o de manera negativa (como llevan muchos a\\u00f1os perdiendo no se ven con capacidad de ganar). Pero eso significar\\u00eda que introducimos efectos externos en el an\\u00e1lisis (podr\\u00edan a\\u00f1adirse m\\u00e1s: la buena o mala temporada que est\\u00e1 haciendo cada uno, la moral que se tiene en esa \\u00e9poca, si se juegan algo importante en ese momento o no\\u2026), efectos que no tienen que ver con la probabilidad. Por ello no cabr\\u00eda hablar de estad\\u00edstica en este caso.<\\\/p>\\n\\n<p>Este art\\u00edculo participa en la <a target=\\\"_blank\\\" rel=\\\"noreferrer\\\" href=\\\"http:\\\/\\\/pimedios.es\\\/2016\\\/04\\\/07\\\/edicion-7-3-del-carnaval-de-matematicas\\\/\\\">Edici\\u00f3n 7.3<\\\/a> del <a target=\\\"_blank\\\" rel=\\\"noreferrer\\\" href=\\\"http:\\\/\\\/carnavaldematematicas.bligoo.es\\\/\\\">Carnaval de Matem\\u00e1ticas<\\\/a>, que en esta ocasi\\u00f3n organiza <a target=\\\"_blank\\\" rel=\\\"noreferrer\\\" href=\\\"http:\\\/\\\/pimedios.es\\\/\\\">Pimedios.es<\\\/a>.<\\\/p>\", \"\\u201ccuanto m\\u00e1s llevas sin ganar, m\\u00e1s probable es que ganes el siguiente\\u201d. esta afirmaci\\u00f3n, que podr\\u00eda parecer cierta, en realidad no tiene mucho sentido en t\\u00e9rminos de probabilidad. en los pr\\u00f3ximos p\\u00e1rrafos analizaremos el porqu\\u00e9.antes de comenzar, quiero dejar claras las condiciones del tema que vamos a comentar. lo que sigue se refiere a experimentos aleatorios independientes (es decir, su resultado en un momento dado no influye en el resultado del mismo experimento en otro momento, como puede pasar al lanzar un dado o una moneda) con un n\\u00famero finito de resultados en el que conocemos la probabilidad de cada uno de ellos.\\n\\nvamos al tema. esta entrada me vino a la mente despu\\u00e9s de ver un tuit del famoso tuitero deportivo @2010misterchip. otro tuitero, @scottiepeppino, le comentaba lo siguiente a ra\\u00edz de una apuesta que el primero hab\\u00eda realizado:\\n@2010misterchip hombre, siendo un hombre de estad\\u00edsticas como eres, apostar por el equipo que lleva sin ganar en ese estadio 30 partidos\\u2026\\n\\u2014 scottie peppino (@scottiepeppino) 11 de abril de 2016\\n\\na lo que misterchip contestaba lo siguiente\\ncuanto m\\u00e1s llevas sin ganar, m\\u00e1s probable es que ganes el siguiente. estad\\u00edstica pura y dura  https:\\\/\\\/t.co\\\/ylyjpova6g\\n\\u2014 misterchip (alexis) (@2010misterchip) 11 de abril de 2016\\n\\nsi acced\\u00e9is al mismo pod\\u00e9is ver mi respuesta\\n@2010misterchip esto\\u2026hablando de azar (si citas \\\"estad\\u00edstica\\\" supongo que te refieres a eso), lo que has dicho no es para nada correcto\\n\\u2014 gaussianos (@gaussianos) 11 de abril de 2016\\n\\ny algunas m\\u00e1s de otros tuiteros. todos intent\\u00e1bamos hacerle ver que hab\\u00eda ca\\u00eddo en una famosa falacia estad\\u00edstica, pero, hasta el d\\u00eda de hoy, la \\u00fanica respuesta que he visto de misterchip es la siguiente (si hay alguna m\\u00e1s dec\\u00eddmelo):\\ncambia \\\"jugador\\\" por \\\"mal jugador\\\" y estaremos de acuerdo. https:\\\/\\\/t.co\\\/03oxvslo9h\\n\\u2014 misterchip (alexis) (@2010misterchip) 11 de abril de 2016\\n\\nsi analizamos el tema de manera probabil\\u00edstica (entiendo que \\u00e9sa era la intenci\\u00f3n de misterchip al hablar de \\u201cestad\\u00edstica\\u201d), el asunto es como sigue: estamos ante un experimento aleatorio con dos posibles resultados (victoria de equipo de casa o victoria del equipo visitante, no consideramos el empate) en el que tenemos la probabilidad de cada uno de ellos (se podr\\u00eda hablar de c\\u00f3mo se determinan dichas probabilidades, pero eso es otro tema). adem\\u00e1s, dichos resultados son independientes.\\nsi realizamos el experimento, podemos obtener cualquiera de los dos resultados. imaginemos que gana el equipo de casa. si volvemos a realizar el experimento, la pregunta es la siguiente: \\u00bfha aumentado la probabilidad de que gane el equipo visitante? la respuesta es no. para hacer un an\\u00e1lisis probabil\\u00edstico correcto, en este caso tenemos que considerar que el resultado obtenido en un enfrentamiento no influye en lo que pasar\\u00e1 en el enfrentamiento siguiente (los resultados son independientes).\\nla creencia de que muchos resultados \\u201chacia un lado\\u201d aumentan la probabilidad de que en la siguiente ocasi\\u00f3n la cosa ir\\u00e1 \\u201chacia el otro lado\\u201d o, m\\u00e1s en general, que los resultados obtenidos influyen en los siguientes (vamos, que el juego \\u201ctiene memoria\\u201d) se denomina falacia del jugador. uno de los ejemplos m\\u00e1s conocidos de esta falacia es el caso que se dio el 18 de agosto de 1913 en una de las ruletas del casino de monte carlo. en aquella ocasi\\u00f3n, la bolita cay\\u00f3 la friolera de \\u00a1\\u00a126 veces seguidas!! en el negro. lo que ocurri\\u00f3 es que, a medida que iban saliendo \\u201cnegros\\u201d, los jugadores iban apostando cada vez m\\u00e1s al \\u201crojo\\u201d, porque entend\\u00edan que con tantas apariciones del negro era mucho m\\u00e1s probable que en la siguiente tirada saliera rojo. y no, esto no es as\\u00ed: la probabilidad de rojo no aumentaba en este caso. tomando la ruleta como un juego de probabilidades, y dando un 0.5 al rojo y un 0.5 al negro (esto no exacto, pero para el caso en el que estamos nos vale), esas probabilidades se mantienen en cada tirada independientemente de lo que saliera en tiradas anteriores (la ruleta \\u201cno tiene memoria\\u201d). \\u00bfqu\\u00e9 ocurri\\u00f3? pues no es dif\\u00edcil imaginarlo: el casino gan\\u00f3 much\\u00edsimo dinero en ese rato.\\n\\u00bfpor qu\\u00e9 entonces pensamos de esta err\\u00f3nea manera (y, si somos jugadores, tan perjudicial para nuestro bolsillo)? pues porque tendemos a pensar que si los resultados anteriores se desv\\u00edan sustancialmente de lo que marcan las probabilidades, dicha desviaci\\u00f3n se corregir\\u00e1 pronto para dejarlo todo \\u201ccomo debe ser\\u201d (en este caso, mismo n\\u00famero de rojos que de negros). eso es, a todas luces, falso. y de este error por nuestra parte se aprovechan a veces los organizadores de este tipo de juegos, d\\u00e1ndonos, por ejemplo, los n\\u00fameros calientes y los n\\u00fameros fr\\u00edos (intentando as\\u00ed influir en nuestra percepci\\u00f3n sobre las probabilidades de cada n\\u00famero en la siguiente tirada). de hecho, en juegos tipo la ruleta, en una situaci\\u00f3n como \\u00e9sta de tantos \\u201cnegros\\u201d seguidos podr\\u00eda ser m\\u00e1s razonable pensar que dicha ruleta est\\u00e1 \\u201ctrucada\\u201d (premeditadamente o no, eso no es importante) para que salgan m\\u00e1s \\u201cnegros\\u201d que \\u201crojos\\u201d, por lo que quiz\\u00e1s tendr\\u00eda m\\u00e1s sentido volver a apostar al \\u201cnegro\\u201d en la tirada siguiente (esta forma de razonar se conoce como principio de hume).\\ny un \\u00faltimo detalle. es tambi\\u00e9n interesante distinguir entre \\u201cn\\u00famero de veces que se ha producido cada resultado\\u201d y \\u201cprobabilidad de cada resultado\\u201d. que las probabilidades sean iguales no significa, ni mucho menos, que conforme aumentamos el n\\u00famero de realizaciones del experimento las veces en las que sale cada resultado tiendan a igualarse. voy a poner un ejemplo para intentar explicar qu\\u00e9 quiero decir:\\nimaginemos que tiramos una moneda 100 veces y salen 40 caras y 60 cruces. en este caso, llevar\\u00edamos un 40% de caras y un 60% de cruces. imaginemos que seguimos tirando la monda y llegamos a 1000 tiradas, obteniendo 460 caras y 540 cruces. las probabilidades se van acercando, 0.46 para \\u201ccara\\u201d y 0.54 para \\u201ccruz\\u201d, pero la distancia entre el n\\u00famero de veces de cada una es mayor (antes era 20 y ahora es 80).\\nrecordad: la probabilidades en estos casos se calculan dividiendo casos favorables entre casos posibles. por ello, aunque las probabilidades se vayan igualando, la diferencia de las veces que sale cada uno de los resultados puede ser cada vez mayor.\\n\\nse ha escrito mucho sobre la falacia del jugador, y en internet pod\\u00e9is encontrar gran cantidad de art\\u00edculos sobre el tema. os dejo \\u00e9ste del maestro adri\\u00e1n paenza: la falacia del jugador.\\n\\nsobre la manera de determinar las probabilidades de cada uno de los resultados quer\\u00eda hacer un comentario. \\u00bftiene sentido tomar los resultados anteriores entre ambos equipos para determinar dicha probabilidad? si la respuesta es afirmativa, el hecho de que un equipo haya perdido los \\u00faltimos enfrentamientos directos deber\\u00eda entonces, bajo mi punto de vista, hacer que la probabilidad de victoria del \\u201cperdedor habitual\\u201d baje respecto a estimaciones anteriores, pero nunca que suba. y si no lo veis, ah\\u00ed va un ejemplo:\\nimaginemos que el granada ha perdido 20 veces seguidas en el bernab\\u00e9u, y que \\u201csu\\u201d probabilidad de victoria era de 0.1. \\u00bfsignifica eso que si vuelven a jugar ahora en el bernab\\u00e9u tienen una probabilidad mayor de ganar?\\npues yo creo que no. a ver qu\\u00e9 pens\\u00e1is vosotros.\\n\\ny sobre el hecho de que los resultados anteriores puedan influir en la mente de los jugadores del equipo \\u201cperdedor habitual\\u201d, cabr\\u00edan las dos posibilidades. podr\\u00eda ser de manera positiva (m\\u00e1s ganas de romper la mala racha) o de manera negativa (como llevan muchos a\\u00f1os perdiendo no se ven con capacidad de ganar). pero eso significar\\u00eda que introducimos efectos externos en el an\\u00e1lisis (podr\\u00edan a\\u00f1adirse m\\u00e1s: la buena o mala temporada que est\\u00e1 haciendo cada uno, la moral que se tiene en esa \\u00e9poca, si se juegan algo importante en ese momento o no\\u2026), efectos que no tienen que ver con la probabilidad. por ello no cabr\\u00eda hablar de estad\\u00edstica en este caso.\\n\\neste art\\u00edculo participa en la edici\\u00f3n 7.3 del carnaval de matem\\u00e1ticas, que en esta ocasi\\u00f3n organiza pimedios.es.^diamond^no, los experimentos aleatorios independientes no tienen memoriahttp:\\\/\\\/gaussianos.com\\\/no-los-experimentos-aleatorios-independientes-no-tienen-memoria\\\/\", \"08b5f3e64d5426293e85ed83760f6b05\", 8]:\n\nSQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\xF0\\x9F\\x98\\x89\" ...' for column 'body' at row 1","level":3,"time":"May 12, 2016 07:30:04","method":"--","url":"--","user":"--"}

**Comment by BernhardPosselt** [comment]
Check this issue: https://github.com/owncloud/news/issues/813

**Comment by BernhardPosselt** [comment]
It's a core issue, update your mysql to 4byte encoding ;)
