### ISSUE TITLE
App is not compliant with 9.0.2

### ISSUE THREAD

**Issue by ptibubu** [owncloud/news#996]
Hi,

Since 9.0.2 upgrade, the android news app does not work anymore:
- the app indicates that something goes wrong
- nothing obvious in the OC log.
- the web interface works as expected.

Not sure if it is an issue of the android app or from the web app, but I tried to check app code and:
```
occ app:check-code news:

ownCloud is in maintenance mode - no app have been loaded
Analysing [...]/apps/news/config/appconfig.php
1 errors
line 88: Backgroundjob::addRegularTask - Method of deprecated class must not be called
Analysing [...]/apps/news/templates/part.settings.php
2 errors
line 79: OCP\Util::linkToRoute - Method of deprecated class must not be called
line 121: OCP\Util::linkToRoute - Method of deprecated class must not be called
App is not compliant
```

Other point:
occ app:list indicates that the version is "true" (instead of the 8.7.5).

OC 9.0.2 / news apps 8.7.5 / PHP 5.6.20 / mariaDB 10.0.23 / nginx 1.6.2 / debian 8.4

**Comment by BernhardPosselt** [comment]
Compliance has nothing to do with the app not working. Could you fill out the issue template?

**Comment by BernhardPosselt** [comment]
Also remove maintenance mode

**Comment by BernhardPosselt** [comment]
This should fix it: https://github.com/owncloud/News-Android-App/issues/506
