### ISSUE TITLE
App chould not be updated (occ stop while updating news)

### ISSUE THREAD

**Issue by fleixi** [owncloud/news#997]
# IMPORTANT

Read and tick the following checkbox after you have created the issue or place an x inside the brackets ;)

* [x ] I have read the [CONTRIBUTING.md](https://github.com/owncloud/news/blob/master/CONTRIBUTING.md) and followed the provided tips

## Explain the Problem
What problem did you encounter?

occ update stop while upgrading news app and need to be killed

## Steps to Reproduce
Explain what you did to encounter the issue
1. Update Owncloud to 9.0.2.2
2. run "occ upgrade"

## System Information
* ownCloud version:
* PHP version: 7.0.6
* Database and version: mysql Ver 14.14 Distrib 5.6.30
* Distribution and version: Debian stretch

## Contents of owncloud/data/owncloud.log

"reqId":"fbcEzWTXHj2jfccahzjT","remoteAddr":"","app":"core","message":"starting upgrade from 9.0.2.2 to 9.0.2.2","level":0,"$
{"reqId":"fbcEzWTXHj2jfccahzjT","remoteAddr":"","app":"news","message":"Configuration value \"proxyHost\" does not exist. Ign$
{"reqId":"fbcEzWTXHj2jfccahzjT","remoteAddr":"","app":"news","message":"Configuration value \"proxyPort\" does not exist. Ign$
{"reqId":"fbcEzWTXHj2jfccahzjT","remoteAddr":"","app":"news","message":"Configuration value \"proxyUser\" does not exist. Ign$
{"reqId":"fbcEzWTXHj2jfccahzjT","remoteAddr":"","app":"news","message":"Configuration value \"proxyPassword\" does not exist.$
{"reqId":"lNx1ZHbLUAiM3CMfHXU+","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\APCu not available for local $
{"reqId":"lNx1ZHbLUAiM3CMfHXU+","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\APCu not available for distri$
{"reqId":"lNx1ZHbLUAiM3CMfHXU+","remoteAddr":"","app":"cron","message":"Update required, skipping cron","level":0,"time":"201$

Shell output (useless)

sudo -u www-data php occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Checking whether the database schema can be updated (this can take a long time depending on the database size)
Checked database schema update
Checking updates of apps
Checked database schema update for apps
Updating database schema
Updated database
Updating <news> ...

----------------------------------------------------------

I chould only disable the news app to get a working owncloud back

**Comment by BernhardPosselt** [comment]
The update performed a database migration. If you kill it it will break. Furthermore updating is not handled by the news app, so I can't fix this issue (if this is one at all), closing hence

**Comment by BernhardPosselt** [comment]
You could try to rerun the automatic update, there is a guide in the FAQ section. On my phone, so making this quick ;)

**Comment by BernhardPosselt** [comment]
Readme

**Comment by fleixi** [comment]
I have looked with version i have had install bevor (8.3.0) and after that i have made the desition to delete my database and reinstall the news app without a databaseentry. Luckilly im the only user of this part of my owncloud installation. But thankyou for your fast help
