### ISSUE TITLE
Feeds without favicon do not show in the list

### ISSUE THREAD

**Issue by Revertron** [owncloud/news#998]
# IMPORTANT

Read and tick the following checkbox after you have created the issue or place an x inside the brackets ;)

* [x] I have read the [CONTRIBUTING.md](https://github.com/owncloud/news/blob/master/CONTRIBUTING.md) and followed the provided tips

## Explain the Problem
If I add some feed that is without favicon (the site is not providing it) the feed is added but not shown in the list or folder. I can see its items (news) only if I select the folder.

## Steps to Reproduce
Explain what you did to encounter the issue
1. Try to add a feed of the site without favicon (i.e. from opennicproject.org), in some folder if that matters.
2. The feed is added, shows its items, but it is not shown in the list/folder.

## System Information
* News app version: 8.7.5
* ownCloud version: 9.0.2
* PHP version: 5.5
* Database and version: MySQL 5.5.47-0+deb7u1
* Browser and version: Firefox
* Distribution and version: Debian 8

**Comment by BernhardPosselt** [comment]
Can not reproduce

**Comment by BernhardPosselt** [comment]
Works fine inside and outside of any folder

**Comment by BernhardPosselt** [comment]
Can you paste the browser console output like requested in the template and turn off all browser addons?

**Comment by BernhardPosselt** [comment]
Another thing: How can you use 8.7.5 on PHP 5.5

**Comment by Revertron** [comment]
Ah, that was Adguard firefox extension. It's social filter was hiding feeds that has default icon.

My php version is 5.5.33-1~dotdeb+7.1. News is working normally, I guess.

**Comment by BernhardPosselt** [comment]
You are on your own if you are not using the versions which are required. There are issues with searching and PHP 5.5 btw.
